// SOUL belongs to the character, not to each figure, and lasts for this battle.
advanceUltimateCooldowns=cooldownBaseV218;
figureSoulV218=a=>Math.max(0,Number(a?.soulPointsV220)||0);
let soulAoeV220=null;
const soulClausesBaseV220=soulClausesV218;soulClausesV218=function(text){const labels='HP|MP|ATK|DEF|MAG|MND|SPD|命中率|回避率|会心率|ダメージ軽減|物理ダメージ軽減|魔法ダメージ軽減|全属性耐性|状態異常耐性|[火水雷風地光闇無]属性(?:耐性|与ダメージ|ダメージ軽減)',pattern=new RegExp('((?:'+labels+')(?:[と・](?:'+labels+'))+)(を(?:\\d+ターンの間)?\\d+(?:\\.\\d+)?%(?:アップ|ダウン)(?:する|させる)?)','g');return soulClausesBaseV220(String(text).replace(/ダメージ軽減率/g,'ダメージ軽減').replace(pattern,(_,names,suffix)=>names.split(/[と・]/).map(n=>n+suffix).join('、')));};
const soulAoeBaseV220=playerAoeDamage;playerAoeDamage=async function(...args){const old=soulAoeV220;soulAoeV220={seen:new Set()};try{return await soulAoeBaseV220(...args);}finally{soulAoeV220=old;}};
function gainSoulV220(a,n){if(!a||a.type==='enemy'||!state.battle?.allies.includes(a))return;a.soulPointsV220=figureSoulV218(a)+n;updateSoulBadgesV220();}
const soulHitBaseV220=applyEnemyDamageTo;applyEnemyDamageTo=function(a,e,...args){const before=e?.hp,r=soulHitBaseV220(a,e,...args);if(before>0&&a&&state.battle?.allies.includes(a)){if(!state.battle.figureSoulCastingV220&&(!soulAoeV220||!soulAoeV220.seen.has(a.id))){gainSoulV220(a,1);soulAoeV220?.seen.add(a.id);}if(e.hp<=0)gainSoulV220(a,2);}return r;};
function updateSoulBadgesV220(){for(const a of state.battle?.allies||[]){const card=$(`[data-ally-id="${a.id}"]`);if(!card)continue;let badge=$('.soul-orb-v220',card);if(!badge){badge=document.createElement('span');badge.className='soul-orb-v220';card.append(badge);}badge.textContent=figureSoulV218(a);badge.setAttribute('aria-label',`${a.name} ソウルポイント ${figureSoulV218(a)}`);}const a=activeAlly();if(a&&document.getElementById('figureSoulBarV218'))$$('[data-soul]',$('#figureSoulBarV218')).forEach(btn=>{const f=figureById(btn.dataset.soul);if(f?.soul){btn.classList.toggle('ready',figureSoulV218(a)>=f.soul.cost);$('small',btn).textContent=`${figureSoulV218(a)}/${f.soul.cost}`;}});}
useFigureSoulV218=async function(a,id){const b=state.battle,f=figureById(id);if(!b||b.busy||b.finished||activeAlly()!==a||!figureActiveV218(a,id))return false;const cost=f.soul.cost;if(figureSoulV218(a)<cost){await narrationDialog(`${f.soul.name}\n${f.soul.text}\nソウルポイント ${figureSoulV218(a)} / 必要 ${cost}`);return false;}b.busy=true;setCommandDisabled(true);try{if(await narrationDialog(`${f.soul.name}\n${f.soul.text}\nSOUL ${cost}消費（ターン消費なし）`,[['発動','yes','primary'],['戻る','no']])!=='yes')return false;if(state.battle!==b||b.finished||a.dead||figureSoulV218(a)<cost)return false;a.soulPointsV220-=cost;b.figureSoulCastingV220=true;await soulCutinV218(f);await applySoulTextV218(f,a,livingField(),livingEnemies(),f.soul.text);if(!livingEnemies().length)await handleEnemyWaveClear();return true;}finally{b.figureSoulCastingV220=false;if(state.battle===b&&!b.finished){b.busy=false;renderBattle();}}};
const soulFeedbackBaseV220=applySoulTextV218;applySoulTextV218=async function(f,a,own,enemies,text,piece=false){const before=new Map([...own,...enemies].map(t=>[t,{hp:t.hp,mp:t.mpNow,effects:JSON.stringify(t.soulEffectsV218||[]),status:JSON.stringify(t.status||{})}])),r=await soulFeedbackBaseV220(f,a,own,enemies,text,piece);if(piece)return r;renderBattle();for(const t of [...own,...enemies]){const prev=before.get(t),host=enemies.includes(t)?enemyVisual(t.uid)?.closest('.enemy-unit'):$(`[data-ally-id="${t.id}"]`),changed=prev.hp!==t.hp||prev.mp!==t.mpNow||prev.effects!==JSON.stringify(t.soulEffectsV218||[])||prev.status!==JSON.stringify(t.status||{});if(host&&changed){const pop=document.createElement('span');pop.className='soul-feedback-v220 '+(enemies.includes(t)?'debuff':'buff');pop.textContent=t.hp>prev.hp?'HP回復':t.mpNow>prev.mp?'MP回復':prev.status!==JSON.stringify(t.status||{})?'状態変化':enemies.includes(t)?'効果発動 ↓':'効果発動 ↑';host.append(pop);setTimeout(()=>pop.remove(),1200);}}notice(`${f.soul?.name||f.name} 発動！`,/ダウン|状態に|ひるみ/.test(text)?'status':'buff',1100);await fixedDelay(480);return r;};
const balanceBuildBaseV220=buildEnemyFromTemplate;buildEnemyFromTemplate=function(t,...args){const e=balanceBuildBaseV220(t,...args);if(e.legendV218){e.maxHp=Math.round(e.maxHp*4/9);e.hp=e.maxHp;e.atk=Math.round(e.atk*1.3);e.mag=Math.round(e.mag*1.3);}else if(e.isBoss||t?.category==='boss'||e.eventV163||e.story179Kind){e.atk=Math.round(e.atk*1.15);e.mag=Math.round(e.mag*1.15);}return e;};
function mochiLayoutV220(){const b=state.battle,screen=$('#battleScreen'),mochi=b?.enemies?.some(e=>e.mochiV218!==undefined);screen.classList.toggle('mochi-battle-v220',!!mochi);if(!mochi)return;const adds=b.enemies.filter(e=>e.mochiV218===4&&e.hp>0);for(const e of b.enemies){const unit=$(`[data-enemy-target="${e.uid}"]`);if(!unit)continue;unit.classList.toggle('mochi-chief-v220',e.mochiV218!==4);if(e.mochiV218===4){const i=adds.indexOf(e);unit.classList.add('mochi-add-v220');unit.style.setProperty('--mochi-x',[20,80,7,93][Math.max(0,i)]+'%');unit.style.setProperty('--mochi-y',i<2?'58%':'36%');}const img=$('.enemy-sprite',unit);if(img){const size=()=>{const maxW=screen.clientWidth*(e.mochiV218===4?.15:.37),maxH=screen.clientHeight*(e.mochiV218===4?.10:.20),ratio=(img.naturalWidth||1)/(img.naturalHeight||1),w=Math.min(maxW,maxH*ratio);img.style.setProperty('width',w+'px','important');img.style.setProperty('height',w/ratio+'px','important');};size();if(!img.complete)img.addEventListener('load',size,{once:true});}}}
const battleUiBaseV220=renderBattle;renderBattle=function(...args){const r=battleUiBaseV220(...args);updateSoulBadgesV220();mochiLayoutV220();return r;};
const sizeBaseV220=applyEnemyVisualSizes;applyEnemyVisualSizes=function(...args){const r=sizeBaseV220(...args);mochiLayoutV220();return r;};
const storyGuestBaseV220=storyShowGuest;storyShowGuest=async function(key,...args){const r=storyGuestBaseV220(key,...args);$('#storyScene').classList.toggle('mochi-story-v220',String(key).startsWith('mochi218-'));return r;};
PRE_V179.mochi=[
 [['say','pink','みなさん\nお餅は好きでありますか？'],['jumpSayV179','denden','大好きでやんす～！'],['say','desert','まあ、嫌いではない'],['say','money','う～ん\nあまり食べないかな'],['say','pink','草原には\n餅つき名人がいるであります！'],['jumpSayV179','denden','お餅が食べれるでやんすか！'],['mochiEntranceV218',0],['say','pink','たしかこんな感じの・・'],['say','denden','お餅一つ～！\nでやんす！'],['say','money','なんか違うみたいよ？'],['say','pink','こっちに来るでやんす！']],
 [['mochiEntranceV218',1],['say','money','あれ？\nさっきのやつまたいるわよ'],['say','pink','なにか食べているであります！'],['say','denden','お餅でやんすか！？'],['say','desert','よく見ろ\nあれは葉っぱだ'],['say','money','きっと草食なのね'],['say','denden','ちょっと欲しいでやんす']],
 [['mochiEntranceV218',2],['say','denden','ビームでやんす～！'],['say','pink','かっけ～であります！'],['say','desert','油断するな\nこちらを狙っているぞ'],['say','money','お餅関係ないじゃない！'],['say','denden','良いお餅には良い水でやんす！']],
 [['mochiEntranceV218',3],['say','denden','ほぅ～！'],['say','pink','やや！ややや！！'],['say','money','お餅発見！'],['say','desert','なんという手際の良さだ'],['mochiHopV220'],['say','money','こっちに来るわよ！']]
];
POST_V179.mochi=[
 [['say','desert','ふぅ～・・'],['sayDual','pink','油断してたでありますね～','denden','油断してたでやんすね～'],['shakeSayV179','money','あらら～？'],['say','desert','俺もまだまだか・・']],
 [['say','pink','戦闘中も\nムシャムシャでありました'],['jumpSayV179','denden','ペッペ！\n苦いでやんす～！'],['say','desert','葉っぱだからな'],['say','money','え？葉っぱって苦いの？']],
 [['say','money','ん・・？\n何かいい匂いしない？'],['say','denden','今度こそお餅でやんす～！'],['jumpSayV179','pink','レッツゴーであります！']],
 [['say','pink','お餅、、\nモンスターでありましたね'],['jumpSayV179','denden','オイラ、\n食べたかったでやんす、、'],['say','money','まあ\nこんなもんよね'],['say','desert','砂漠にも\nお餅はあるぞ'],['say','denden','ほぅ～！！'],['say','pink','レッツゴー！！\nであります！！']]
];
const mochiStepsBaseV220=runStoryStepsV179;runStoryStepsV179=async function(steps){for(const st of steps){if(st[0]==='mochiHopV220'){await animateV157($('#storyGuest'),[{translate:'0 0'},{translate:'0 -28px'},{translate:'0 0'},{translate:'0 -35px'},{translate:'0 0'}],650);}else await mochiStepsBaseV220([st]);}};
