for(const [id,extra]of [['004',[...eneImgV96(51,56),...bossImgV96(9,9),...['40','51'].map(n=>`fig/${n}.png`)]],['010',[...eneImgV96(51,61),...bossImgV96(4,4),...['39','56','57'].map(n=>`fig/${n}.png`)]],['011',[...eneImgV96(10,17),...bossImgV96(4,4),...bossImgV96(27,30),...['59','60','68','69'].map(n=>`fig/${n}.png`)]]])FIGURE_GACHAS_V96.find(b=>b.id===id).extra=extra;
const GACHA_PATTERNS_V220=[{id:'wood',rate:60,line:'見つけたであります！'},{id:'choice',rate:24.5,line:'ど、どっちが正解でありますか⁉'},{id:'gold',rate:12,line:'金ピカであります〜！'},{id:'rainbow',rate:3,line:'こんなの見たことないであります‼'},{id:'rush',rate:.5,line:'ゆ、夢でありますか⁉'}];
function selectGachaPatternV220(random=Math.random()){let n=random*100;for(const p of GACHA_PATTERNS_V220){n-=p.rate;if(n<0)return p;}return GACHA_PATTERNS_V220.at(-1);}
function gachaFeaturedV220(b){const pool=gachaPoolV96(b),explicit=(b.pickup||[]).map(figureByImageV96).filter(f=>pool.includes(f));if(explicit.length)return explicit;const local=b.extra.map(figureByImageV96).filter(Boolean),rank={R:0,SR:1,SSR:2,UR:3,MOB:4},max=Math.max(...local.map(f=>rank[f.rarity]));return local.filter(f=>rank[f.rarity]===max);}
function rollRareGachaV220(b){const pool=gachaPoolV96(b),groups={};for(const f of pool)if(['SSR','UR','MOB'].includes(f.rarity))(groups[f.rarity]??=[]).push(f);const rows=Object.entries({SSR:85,UR:13,MOB:2}).filter(([r])=>groups[r]?.length),total=rows.reduce((n,[,v])=>n+v,0);let n=Math.random()*total;for(const [r,w]of rows){n-=w;if(n<0)return pick(groups[r]);}return pool.find(f=>f.rarity==='SSR');}
function prepareGachaV220(b,count,pattern=selectGachaPatternV220()){const figs=Array.from({length:count},(_,i)=>pattern.id==='rush'?rollRareGachaV220(b):gachaRollV96(b,count===10&&i===9));const slot=Math.floor(Math.random()*count),featured=gachaFeaturedV220(b);if(pattern.id==='gold'||pattern.id==='choice'&&Math.random()<.5)figs[slot]=rollRareGachaV220(b);if(['rainbow','rush'].includes(pattern.id))figs[slot]=pick(featured);if(figs.some(f=>!f))throw new Error('排出対象がありません');return{pattern,figs};}
function chestMarkupV220(kind){return `<div class="treasure-v220 ${kind}" aria-label="${{wood:'木',gold:'金',rainbow:'虹'}[kind]}の宝箱"><i class="treasure-lid-v220"></i><i class="treasure-base-v220"></i><b>◆</b></div>`;}
async function pinkGachaV220(pattern){const ov=gachaSurfaceV219(),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;ov.innerHTML=`<section class="pink-stage-v220 ${pattern.id}"><div class="pink-speech-v220">行ってくるであります‼</div><div class="pink-runner-v220"><img src="${player('pink').image}" alt="モブピンク"></div><div class="treasure-row-v220"></div><div class="pink-rays-v220"></div><small>モブピンクがお宝を探しています…</small></section>`;const stage=$('.pink-stage-v220',ov);await fixedDelay(reduced?120:1200);stage.classList.add('returned');$('.pink-speech-v220',ov).textContent=pattern.line;$('.treasure-row-v220',ov).innerHTML=(pattern.id==='choice'?['wood','gold']:pattern.id==='rush'?['gold','rainbow','gold','rainbow','gold']:[pattern.id==='wood'?'wood':pattern.id==='rainbow'?'rainbow':'gold']).map(chestMarkupV220).join('');$('small',stage).textContent='タカラモノ、見つけたであります！';await fixedDelay(reduced?120:1700);stage.classList.add('opened');await fixedDelay(reduced?120:850);}
drawGachaV96=async function(b,count){if(gachaBusyV110||![1,10].includes(count)||!b?.unlock())return;gachaBusyV110=true;try{ensureGachaOverlayV96().hidden=true;if(await dialog('このガチャを引くの？',[['はい','yes','primary'],['いいえ','no']],'モブメープル','play/009.png')!=='yes')return;const cost=count===10?50:5;if((Number(state.meta.diamonds)||0)<cost){await facilityTalk('ダイヤが足りないよ！','モブメープル','play/009.png');return;}const {pattern,figs}=prepareGachaV220(b,count);state.meta.diamonds-=cost;const entries=figs.map(awardGachaFigureV115);saveMeta();await Promise.all([pinkGachaV220(pattern),preloadFigureRowsV110(figs,3200)]);await showGachaResultV115(b,entries);}finally{gachaBusyV110=false;closeGachaV219(b.id);}};
const gachaOpenBaseV220=openGachaDetailV96;openGachaDetailV96=function(id){gachaOpenBaseV220(id);const b=FIGURE_GACHAS_V96.find(b=>b.id===id),ov=ensureGachaOverlayV96();if(!b?.unlock()||ov.hidden||gachaBusyV110)return;const line=$('[data-lineup]',ov);if(line&&!$('[data-ruby-v220]',ov)){const button=document.createElement('button');button.dataset.rubyV220='';button.textContent='ルビーで交換';line.after(button);button.onclick=()=>showRubyExchangeV220(b);}const rate=document.createElement('p');rate.className='gacha-rates-v220';rate.textContent='宝箱演出：木60% / 迷う24.5%（50%でSSR以上） / 金12%（SSR以上確定） / 虹3%（目玉確定） / ラッシュ0.5%（全てSSR以上＋目玉確定）';$('.gacha-panel-v219',ov)?.append(rate);};
const lineupBaseV220=showGachaLineupV96;showGachaLineupV96=function(b){lineupBaseV220(b);const ov=ensureGachaOverlayV96(),grid=$('.gacha-grid-v219',ov),note=$('section>small',ov);if(note)note.textContent='虹・ラッシュでこの目玉フィギュアから1体確定（指定前の仮設定）';if(grid){grid.innerHTML=gachaFeaturedV220(b).map(f=>`<button data-feature="${f.id}">${gachaImageV219(f)}<small>${f.rarity}</small><b>${f.name}</b></button>`).join('');$$('[data-feature]',grid).forEach(btn=>btn.onclick=()=>gachaDetailV219(figureById(btn.dataset.feature),ov));}};
let rubyBusyV220=false;
function showRubyExchangeV220(b){if(!b.unlock())return;const ov=gachaSurfaceV219();ov.innerHTML=`<section class="gacha-panel-v219"><button data-back>← ガチャへ戻る</button><h2>ルビーで交換</h2><p>所持ルビー <b>${rubyOwnedV115()}</b></p><p>フィギュアを選んで性能・必要数を確認</p><div class="gacha-grid-v219">${gachaPoolV96(b).map(f=>`<button data-exchange="${f.id}">${gachaImageV219(f)}<b>${f.name}</b><small>必要 ♦${figureRubyCostV115(f)}</small><em>${figureOwned(f.id)?'強化 +'+figurePlusV218(f.id):'未所持'}</em></button>`).join('')}</div></section>`;$('[data-back]',ov).onclick=()=>openGachaDetailV96(b.id);$$('[data-exchange]',ov).forEach(btn=>btn.onclick=()=>{const f=figureById(btn.dataset.exchange),cost=figureRubyCostV115(f),pop=document.createElement('div');pop.className='gacha-detail-v219';pop.innerHTML=`<section><button data-close>← 一覧へ戻る</button>${figureDetailMarkupV96(f)}<p>所持ルビー ${rubyOwnedV115()} / 必要ルビー ${cost}</p><button data-confirm ${figureOwned(f.id)&&figurePlusV218(f.id)>=9?'disabled':''}>${figureOwned(f.id)&&figurePlusV218(f.id)>=9?'最大強化済み':'このフィギュアと交換する'}</button></section>`;ov.append(pop);$('[data-close]',pop).onclick=()=>pop.remove();$('[data-confirm]',pop).onclick=async()=>{if(rubyBusyV220||!b.unlock())return;rubyBusyV220=true;try{ov.hidden=true;const answer=await dialog(`${f.name}をルビー${cost}個で交換しますか？\n所持ルビー ${rubyOwnedV115()}`,[['交換する','yes'],['やめる','no']],'モブメープル','play/009.png');if(answer!=='yes'){ov.hidden=false;return;}const r=rubyExchangeFigureV115(f);if(!r.ok)await facilityTalk(r.msg,'モブメープル','play/009.png');else await facilityTalk(`${f.name}を交換したよ！`,'モブメープル','play/009.png');showRubyExchangeV220(b);}finally{rubyBusyV220=false;}};});}
const shopUiBaseV220=renderFigureGachaShopV98;renderFigureGachaShopV98=function(...args){const r=shopUiBaseV220(...args),card=$('.maple-shop-card',$('#tavernFigurePopup')),note=$('.gacha-rate-note-v96',card);if(note)note.textContent='通常抽選 R50% / SR30% / SSR15% / UR4.5% / MOB0.5%（宝箱による昇格あり）';return r;};renderFigureGachaShopV96=renderFigureGachaShopV98;
window.__mobBuildVersion='v220';
