/* Shared integration points are deliberately after all content modules. */
const storyPartyBaseV218=storyDisplayPartyIds;storyDisplayPartyIds=function(...args){if(eventRunV174?.storyV179==='mochi')return partyV179('mochi').map(x=>x[0]);return storyPartyBaseV218(...args);};
const mochiStatusBaseV218=enemyAction;
// Wind resistance penalties and accuracy use the same timed effect storage as SOUL.
const incomingBaseV218=playerBaseElementResistanceV104;playerBaseElementResistanceV104=function(a,el){return incomingBaseV218(a,el)+soulEffectValueV218(a,'baseResist:'+el);};
const accuracyBaseV218=playerAttackHitChance;playerAttackHitChance=function(a,e,...args){return clamp(accuracyBaseV218(a,e,...args)+soulEffectValueV218(a,'accuracy')-(a.accuracyDownTurnsV218>0?a.accuracyDownV218||0:0),0,1);};
const tickBaseV218=tickBuffs;tickBuffs=function(...args){const r=tickBaseV218(...args);for(const a of state.battle?.allies||[])if(a.accuracyDownTurnsV218>0)a.accuracyDownTurnsV218--;return r;};
const helperStatsBaseV218=buildAlly;
buildAlly=function(p,lv,...args){const a=helperStatsBaseV218(p,lv,...args);if(!p.helperV218)return a;
 const weapons=blacksmithShopWeapons().filter(w=>!w.types?.includes('メダル')&&w.type!=='メダル').sort((x,y)=>Object.values(y.stats||{}).reduce((a,b)=>a+b,0)-Object.values(x.stats||{}).reduce((a,b)=>a+b,0));
 const main=weapons.find(w=>w.attribute===p.attribute)||weapons[0];a.equipment={...emptyEquipment(),main:main?.id||null};
 const stats=weaponStatsForEquipment(p,lv,a.equipment);for(const k of ['maxHp','maxMp','atk','mag','def','res','spd'])a[k]=Math.round(stats[k]*.9);if(p.helperV218==='高いHP')a.maxHp=Math.round(a.maxHp*1.4);
 const pool=FIGURES.filter(f=>f.rarity==='SR'&&cpuFigureAvailableV218(f));a.figureEquipment=shuffleV96(pool).slice(0,4).map(f=>f.id);const fe=emptyFigureEffects();for(const id of a.figureEquipment){const f=figureById(id);mergeFigureEffects(fe,{...parseFigureEffectText(f.traitText),stats:parseFigureStatsText(f.statsText)});}a.figureEffects=fe;for(const [k,v]of Object.entries(fe.stats))a[k]+=v;a.hp=a.maxHp;a.mpNow=a.maxMp;return a;
};
const helperMagicBaseV218=availableMagicSkillsV104;availableMagicSkillsV104=function(a){if(!a?.helperV218)return helperMagicBaseV218(a);return(MOB_DATA.magicCatalog||[]).filter(s=>s.element===a.attribute||s.supportKind||s.kind==='statusMagic').filter(s=>s.id!=='mira-mob-poison');};
const helperTechBaseV218=availableTechniqueSkillsV104;availableTechniqueSkillsV104=function(a){if(!a?.helperV218)return helperTechBaseV218(a);return(MOB_DATA.techniqueCatalog||[]).filter(s=>s.element===a.attribute);};
const raidRoundBaseV218=startRound;startRound=async function(...args){const b=state.battle;for(const e of b?.enemies||[]){const q=e.legendV218;if(!q)continue;const force=q.key==='mu'&&b.turn%3===0||q.key==='gene'&&Math.random()<.08;e.v144ActionMin=force?5:3;e.v144ActionMax=5;e.legendShieldV218=q.key==='mu'&&force?.5:0;if(e.legendRageV218){e.atk/=1.5;e.mag/=1.5;e.legendRageV218=false;}if(q.key==='gene'&&force){e.atk*=1.5;e.mag*=1.5;e.legendRageV218=true;}}return raidRoundBaseV218(...args);};
const raidCalcBaseV218=calcDamage;calcDamage=function(a,type,power,crit,e=targetEnemy()){const r=raidCalcBaseV218(a,type,power,crit,e);if(e?.legendV218&&r&&!r.miss){const k=e.legendV218.key,chance=k==='magnum'?.2:k==='caramel'?0:.1;r.value=Math.round(r.value*(1-(e.legendShieldV218||0))*(Math.random()<chance?.9:1));}if(e?.extraBossV218==='katchin'&&r?.crit)r.value=Math.round(r.value*.3);return r;};
const raidHpBaseV218=checkBattleHpDialogue;checkBattleHpDialogue=async function(...args){const r=await raidHpBaseV218(...args);if(state.battle?.config?.legendV218)await eventDrainV163();return r;};
const raidAvoidBaseV218=weaponEvasion;weaponEvasion=function(a){return actingEnemy()?.legendV218?.key==='magnum'?0:raidAvoidBaseV218(a);};
const raidIncomingBaseV218=damageAlly;damageAlly=async function(a,...args){const e=actingEnemy(),original=a.figureEffects,critical=enemyCriticalV163;try{if(e?.legendV218?.key==='magnum')a.figureEffects={...original,evade:0,aoeEvade:0};if(e?.extraBossV218)enemyCriticalV163=Math.random()<(e.eventV163?.crit||0);return await raidIncomingBaseV218(a,...args);}finally{a.figureEffects=original;enemyCriticalV163=critical;}};
const raidSpecialBaseV218=legendSpecialV218;legendSpecialV218=async function(e){if(e.legendV218.key!=='caramel'||Math.random()<.5)return raidSpecialBaseV218(e);const b=state.battle,old=b.actingEnemyId;b.actingEnemyId=e.uid;try{await actionCutin('キャロットノタネ','danger',650);let total=0;for(let i=0;i<2;i++){const a=pick(livingField());if(a)total+=await damageAlly(a,1.05,'magic',false,'火');}e.hp=Math.min(e.maxHp,e.hp+Math.round(total*.25));renderBattle();}finally{b.actingEnemyId=old;}};

// Normal tag tiers replace one another; adjacency remains a separate pass.
function pieceTagEffectsV218(text){const out={},map={ライフ:'lifePct',HP:'lifePct',アタック:'attackPct',ATK:'attackPct',ディフェンス:'defensePct',DEF:'defensePct',スピード:'speedPct',SPD:'speedPct'};for(const clause of String(text||'').normalize('NFKC').split(/&|、/)){const enemy=/相手|敵/.test(clause),center=/センター/.test(clause);for(const m of clause.matchAll(/(ライフ|HP|アタック|ATK|ディフェンス|DEF|スピード|SPD)\s*([+-]?)(\d+)\s*%\s*(アップ|UP|ダウン|DOWN)?/g)){let key=map[m[1]],v=+m[3]/100*(m[2]==='-'||/ダウン|DOWN/.test(m[4]||'')?-1:1);if(center)key='center'+key[0].toUpperCase()+key.slice(1);if(enemy)key='enemy'+key[0].toUpperCase()+key.slice(1);out[key]=(out[key]||0)+v;}const all=clause.match(/全ステータス\+(\d+)%/);if(all)for(let key of ['lifePct','attackPct','defensePct','speedPct']){if(center)key='center'+key[0].toUpperCase()+key.slice(1);out[key]=(out[key]||0)+ +all[1]/100;}}return out;}
for(const row of CATALOG_V218.tags){const t=figureTagById(row.id);if(t){if(row.pieceTwo)t.pieceTwo={label:row.pieceTwo,effects:pieceTagEffectsV218(row.pieceTwo)};if(row.pieceThree)t.pieceThree={label:row.pieceThree,effects:pieceTagEffectsV218(row.pieceThree)};}}
const pieceRowsBaseV218=pieceFightersV133;pieceFightersV133=function(hand,other,side,center=2){const rows=pieceRowsBaseV218(hand,other,side,center),own=handTagEffectsV96(hand).effects,opp=handTagEffectsV96(other).effects;for(const r of rows){r.spd=Math.max(1,Math.round(r.spd*Math.max(.1,1+(own.speedPct||0)+(r.index===center?own.centerSpeedPct||0:0)+(opp.enemySpeedPct||0)+(r.index===center?opp.enemyCenterSpeedPct||0:0))));if(r.index===center){r.atk=Math.max(1,Math.round(r.atk*(1+(opp.enemyCenterAttackPct||0))));r.def=Math.max(1,Math.round(r.def*(1+(opp.enemyCenterDefensePct||0))));}}return rows;};
const figureParseBaseV218=parseFigureEffectText;parseFigureEffectText=function(text){let s=String(text||'').normalize('NFKC').replace(/ダメージ軽減率/g,'ダメージ軽減');const normal=s.match(/通常攻撃会心率\s*\+?\s*(\d+)%/);if(normal)s=s.replace(normal[0],'');const o=figureParseBaseV218(s);if(normal)o.normalCritV218=+normal[1]/100;return o;};
const mergeBaseV218=mergeFigureEffects;mergeFigureEffects=function(a,b){const n=(a.normalCritV218||0)+(b?.normalCritV218||0);const r=mergeBaseV218(a,b);r.normalCritV218=n;return r;};
const normalCritBaseV218=calcDamage;calcDamage=function(a,type,power,crit=0,e=targetEnemy()){if(state.battle?.weaponAttackContext?.normal)crit+=Number(a?.figureEffects?.normalCritV218||0);return normalCritBaseV218(a,type,power,crit,e);};
const penetrationBaseV218=calcDamage;calcDamage=function(a,type,power,crit,e=targetEnemy()){const r=penetrationBaseV218(a,type,power,crit,e),p=state.battle?.weaponAttackContext?.figurePenetrationV218||0,cut=e?.damageReduction||0;if(p&&cut>0&&cut<1&&r&&!r.miss)r.value=Math.round(r.value*(1-cut*(1-p))/(1-cut));return r;};
const statusResistanceBaseV218=figureStatusResistance;figureStatusResistance=function(pid,key){const a=allyById(pid);return clamp(statusResistanceBaseV218(pid,key)+(a?soulEffectValueV218(a,'status:'+key)+soulEffectValueV218(a,'status:all'):0),0,1);};
const mpCutBaseV218=weaponMagicMpCut;weaponMagicMpCut=function(a,el){return clamp(mpCutBaseV218(a,el)+soulEffectValueV218(a,'mpCut'),0,.8);};

const eventLoadBaseV218=startBattleLoaded;startBattleLoaded=async function(config){if(config.eventQuestV163?.key==='summoner'){const d=config.eventQuestV163.difficulty,q=EVENT_BOSSES_V163.find(q=>q.key==='summoner');config={...config,enemyConfigs:[...config.enemyConfigs,{template:{id:'gaman218',name:'モブガマン',image:'spenemy/68.png',attribute:'火',category:'boss',gamanV218:true,actionCount:1,forceActionCount:true,v144ActionMin:1,v144ActionMax:2,evasion:d===2?.05:0,permanentDamageReduction:true},level:q.levels[d]}]};config.enemyConfigs[0].template={...config.enemyConfigs[0].template,name:'モブマグサモン'};}await eventLoadBaseV218(config);if(config.legendV218&&state.battle?.config?.legendV218!==config.legendV218)throw new Error('レジェンド戦闘の準備に失敗しました');};
const gamanActionBaseV218=enemyAction;enemyAction=async function(index=1,uid){const e=enemyByUid(uid)||actingEnemy(),b=state.battle;if(!e?.gamanV218)return gamanActionBaseV218(index,uid);if(!b||b.finished||e.hp<=0)return;for(const k of ['sleep','stun','paralyze'])if(e.status[k]>0){e.status[k]--;return;}const old=b.actingEnemyId,crit=enemyCriticalV163;b.actingEnemyId=e.uid;enemyCriticalV163=true;try{await beginEnemyLunge(e.uid);if(Math.random()<.2){for(const a of livingField())await damageAlly(a,1,'physical',false,'火');}else livingField().forEach(a=>showMiss(a.id));}finally{endEnemyLunge();b.actingEnemyId=old;enemyCriticalV163=crit;}};
const gamanHitBaseV218=applyEnemyDamageTo;applyEnemyDamageTo=function(a,e,...args){const before=e?.hp,r=gamanHitBaseV218(a,e,...args);if(e?.gamanV218){if(e.hp>0&&e.hp/e.maxHp<=.5){e.v144ActionMin=2;e.v144ActionMax=3;}if(before>0&&e.hp<=0&&!e.explodedV218){e.explodedV218=true;eventQueueV163(async()=>{const b=state.battle,old=b.actingEnemyId,crit=enemyCriticalV163;b.actingEnemyId=e.uid;enemyCriticalV163=true;try{await eventSpecialV218(e,{name:'ラスト・ビッグバン',all:true,power:3});}finally{b.actingEnemyId=old;enemyCriticalV163=crit;}});}}return r;};
const cassetteRewardBaseV218=grantEventRewardV163;grantEventRewardV163=function(b,win){if(b.eventRewardV163)return b.eventRewardV163;const r=cassetteRewardBaseV218(b,win);if(win&&b.config.eventQuestV163.key==='cassette'&&b.config.eventQuestV163.difficulty===2&&r.figure){const n=r.figure.f.image==='eventfig/46.png'?47:46;r.extraFigureV218=awardGachaFigureV115(figureByImageV96(`eventfig/${n}.png`));saveMeta();}return r;};
const cassetteResultBaseV218=showEventResultV163;showEventResultV163=async function(b,r){await cassetteResultBaseV218(b,r);if(r.extraFigureV218){const f=r.extraFigureV218,el=document.createElement('div');el.className='event-drop-v163';el.innerHTML=`${figureImageTagV101(f.f)}<b>${f.f.name}</b><small>${f.converted?'ルビー +'+f.ruby:f.plus?'強化 +'+f.plus:'GET!'}</small>`;$('[data-event-result-close]',eventOverlayV163()).before(el);}};
const mochiAreaBaseV218=startSavannaAreaV174;startSavannaAreaV174=async function(...args){if(eventRunV174?.storyV179==='mochi'){state.meta.storyEventSeenV175??={};state.meta.storyEventSeenV175.mochi=true;saveMeta();}return mochiAreaBaseV218(...args);};
const homeGuardBaseV218=renderHome;renderHome=function(...args){const r=homeGuardBaseV218(...args);if(!mapleShopUnlocked())$('#shelfButtonV218')?.remove();return r;};
const gachaResultBaseV218=showGachaResultV115;showGachaResultV115=function(b,entries){return gachaResultBaseV218(b,entries.map(e=>e.plus?{...e,f:{...e.f,name:`${e.f.name} +${e.plus}（自動合成）`}}:e));};
const raidStartBaseV218=startLegendV218;startLegendV218=async function(q,helpers){if(helpers.some(id=>!HELPERS_V218.some(row=>row[0]===id)))return false;try{return await raidStartBaseV218(q,helpers);}catch(error){console.error('[v218 legend start]',error);eventOverlayV163().hidden=true;showScreen('training');eventViewV163='legend';renderEventQuestsV163();$('#trainingFeaturePopup').hidden=false;toast('戦闘の準備に失敗しました。もう一度お試しください。');return false;}};

pieceTagEffectsV218=function(text){
 const map={ライフ:'lifePct',HP:'lifePct',アタック:'attackPct',ATK:'attackPct',ディフェンス:'defensePct',DEF:'defensePct',スピード:'speedPct',SPD:'speedPct'},out={};
 const labels=Object.keys(map).join('|'),group=new RegExp('((?:'+labels+')(?:・(?:'+labels+'))+)\\s*([+-]?\\d+)%','g');
 const expanded=String(text||'').normalize('NFKC').replace(group,(_,names,n)=>names.split('・').map(name=>name+n+'%').join(' & '));let enemy=false,center=false;
 for(const clause of expanded.split(/&|、/)){
  if(/相手|敵/.test(clause)){enemy=true;center=/センター/.test(clause);}else if(/味方|センター|他の/.test(clause)){enemy=false;center=/センター/.test(clause);}
  const add=(key,v)=>{if(center)key='center'+key[0].toUpperCase()+key.slice(1);if(enemy)key='enemy'+key[0].toUpperCase()+key.slice(1);out[key]=(out[key]||0)+v;};
  for(const m of clause.matchAll(new RegExp('('+labels+')\\s*([+-]?)(\\d+)\\s*%\\s*(アップ|UP|ダウン|DOWN)?','g')))add(map[m[1]],+m[3]/100*(m[2]==='-'||/ダウン|DOWN/.test(m[4]||'')?-1:1));
  const all=clause.match(/全ステータス\+(\d+)%/);if(all)for(const key of ['lifePct','attackPct','defensePct','speedPct'])add(key,+all[1]/100);
 }
 return out;
};
for(const row of CATALOG_V218.tags){const t=figureTagById(row.id);if(t){if(row.pieceTwo)t.pieceTwo={label:row.pieceTwo,effects:pieceTagEffectsV218(row.pieceTwo)};if(row.pieceThree)t.pieceThree={label:row.pieceThree,effects:pieceTagEffectsV218(row.pieceThree)};}}
function pieceSoulBoostV218(hand){const counts={};for(const id of hand)for(const tag of figureById(id)?.tags||[])counts[tag]=(counts[tag]||0)+1;let boost=0;for(const [id,count]of Object.entries(counts)){if(count<2)continue;const t=CATALOG_V218.tags.find(t=>t.id===id),text=count>=3?t?.pieceThree:t?.pieceTwo;boost+=+(text?.match(/フィギュアスキルの数値効果\+(\d+)%/)?.[1]||0)/100;}return boost;}
for(const f of FIGURES)if(!f.mobPieceV115&&!f.pending){const b=MOB_PIECE_BASE_V100[f.rarity]||MOB_PIECE_BASE_V100.R;f.mobPieceV115={cost:mobPieceCostV100(f),hp:b.life,attack:b.power,defense:b.defense,speed:b.speed};}
const fillFiguresBaseV218=fillTestItemsV100;fillTestItemsV100=function(...args){const r=fillFiguresBaseV218(...args);state.meta.figurePlusV218??={};for(const f of FIGURES)if(!f.pending){state.meta.figures[f.id]=1;state.meta.figurePlusV218[f.id]=9;}saveMeta();return r;};
const effectsParseFinalV218=parseFigureEffectText;parseFigureEffectText=function(text){let s=String(text||'').normalize('NFKC').replace(/会心率、回避率\s*\+(\d+)%/g,'会心率+$1% & 回避率+$1%').replace(/光属性\s*&\s*雷属性\s*与ダメージ\s*\+(\d+)%/g,'光属性与ダメージ+$1% & 雷属性与ダメージ+$1%').replace(/水属性与ダメージ、火属性ダメージ軽減\s*\+(\d+)%/g,'水属性与ダメージ+$1% & 火属性ダメージ軽減+$1%');const o=effectsParseFinalV218(s);o.passiveChanceV218=+(s.match(/特殊効果発動率\s*\+(\d+)%/)?.[1]||0)/100;o.debuffCutV218=+(s.match(/デバフ軽減\s*\+(\d+)%/)?.[1]||0)/100;return o;};
const effectsMergeFinalV218=mergeFigureEffects;mergeFigureEffects=function(a,b){const x={};for(const k of ['passiveChanceV218','debuffCutV218'])x[k]=(a[k]||0)+(b?.[k]||0);const r=effectsMergeFinalV218(a,b);Object.assign(r,x);return r;};
const passiveBaseV218=passiveChance;passiveChance=function(rate,...args){return passiveBaseV218(Math.min(1,rate+(activeAlly()?.figureEffects?.passiveChanceV218||0)),...args);};
const timedEffectsBaseV218=soulEffectValueV218;soulEffectValueV218=function(a,key){const v=timedEffectsBaseV218(a,key);return v<0?v*(1-clamp(a.figureEffects?.debuffCutV218||0,0,.9)):v;};

// Native swipe navigation with a stable panel and element-colored quest cards.
const questPresentationBaseV218=renderEventQuestsV163;
renderEventQuestsV163=function(...args){const r=questPresentationBaseV218(...args),panel=$('.event-panel-v163',$('#trainingFeaturePanel'));if(!panel)return r;
 panel.classList.add('quest-enter-v218');const grid=$('.quest-cards-v218',panel);if(!grid)return r;
 const cards=[...grid.children].filter(x=>x.tagName==='BUTTON'),colors={火:'#ff956b',水:'#65dfff',雷:'#ffe07b',風:'#86ecc8',地:'#e8b87d',光:'#ffe6a1',闇:'#c995ff',無:'#b2c9ff'};
 cards.forEach(card=>{const q=EVENT_BOSSES_V163.find(x=>x.key===card.dataset.eventBoss)||LEGENDS_V218.find(x=>x.key===card.dataset.legend);if(q)card.style.setProperty('--card-glow',colors[q.attribute]||colors.無);});
 grid.setAttribute('aria-label','左右にスワイプしてクエストを選択');const nav=document.createElement('nav');nav.className='quest-nav-v218';nav.setAttribute('aria-label','クエスト切替');nav.innerHTML='<button type="button" aria-label="前のクエスト">‹</button><span><b></b>左右にスワイプして選択</span><button type="button" aria-label="次のクエスト">›</button>';grid.before(nav);
 const buttons=nav.querySelectorAll('button'),label=nav.querySelector('b');let selected=0;
 function update(){const center=grid.getBoundingClientRect().left+grid.clientWidth/2;selected=cards.reduce((best,c,i)=>Math.abs(c.getBoundingClientRect().left+c.offsetWidth/2-center)<Math.abs(cards[best].getBoundingClientRect().left+cards[best].offsetWidth/2-center)?i:best,0);label.textContent=cards.length?`${selected+1} / ${cards.length}`:'クエスト準備中';buttons[0].disabled=selected===0;buttons[1].disabled=selected>=cards.length-1;}
 buttons.forEach((b,i)=>b.onclick=()=>{const c=cards[Math.max(0,Math.min(cards.length-1,selected+(i?1:-1)))];if(c)grid.scrollBy({left:c.getBoundingClientRect().left-grid.getBoundingClientRect().left-(grid.clientWidth-c.offsetWidth)/2,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});});grid.addEventListener('scroll',update,{passive:true});update();return r;
};
