STORY179.nightmare={title:'ネオン街の悪夢',world:'neon',oneTime:true,image:'back/neon4.png',diffs:[{name:'追憶',level:95,coins:0,diamonds:0,figures:[]}]};
const nmOpenBaseV239=openV179;
openV179=function(key,d=0){return key==='nightmare'?d===0&&(!!state.meta.gameCleared||testAllQuestsV171())&&!recordsV179(key).clear:nmOpenBaseV239(key,d);};
const nmMenuBaseV239=renderEventQuestsV163;
renderEventQuestsV163=function(...args){const selected=selectedStoryV179;if(selected==='nightmare')selectedStoryV179=null;let r;try{r=nmMenuBaseV239(...args);}finally{if(selected==='nightmare')selectedStoryV179=selected;}if(eventViewV163!=='story')return r;const panel=$('#trainingFeaturePanel .event-panel-v163');if(!panel)return r;if(selectedStoryV179===null){const b=document.createElement('button');b.className='event-story-card-v174 nm-card-v239';b.dataset.nightmareV239='';b.innerHTML='<small>STORY / 全4 AREA</small><strong>ネオン街の悪夢</strong><img src="back/neon4.png" alt="ネオン街"><small></small>';$('small:last-child',b).textContent=recordsV179('nightmare').clear?'CLEAR':openV179('nightmare')?'挑戦する':'本編クリア後に解放';b.onclick=()=>{selectedStoryV179='nightmare';renderEventQuestsV163();};($('.event-story-list-v177',panel)||panel).append(b);}else if(selectedStoryV179==='nightmare'){panel.innerHTML='<button data-nm-back>戻る</button><div class="nm-event-detail-v239"><img src="back/neon4.png" alt="ネオン街"><h2>ネオン街の悪夢</h2><p>全4 AREA / 推奨 Lv.95</p><p>戦闘：現在のパーティー</p><button class="primary-btn" data-nm-start></button></div>';$('[data-nm-back]',panel).onclick=()=>{selectedStoryV179=null;renderEventQuestsV163();};const b=$('[data-nm-start]',panel);b.disabled=!openV179('nightmare');b.textContent=recordsV179('nightmare').clear?'CLEAR':openV179('nightmare')?'物語を始める':'本編クリア後に解放';b.onclick=()=>startV179('nightmare',0);}return r;};
const nmStartBaseV239=startV179;
startV179=async function(key,d=0){if(key!=='nightmare')return nmStartBaseV239(key,d);if(eventRunV174||!openV179(key,d))return false;if(!await confirmStoryChallengeV179('ネオン街の悪夢','全4 AREA / 推奨 Lv.95'))return false;eventRunV174={storyV179:key,difficulty:0,area:0,vitals:{},rewarded:false};$('#trainingFeaturePopup').hidden=true;await startSavannaAreaV174();return true;};
function nmWaveV239(area){
 const make=(base,lv,kind,min,max=min)=>({template:{...base,id:kind==='yami'?'nightmare239-yami':base.id,nightmareV239:kind,noEscape:true,actionCount:min,forceActionCount:true,v144ActionMin:min,v144ActionMax:max,permanentDamageReduction:true,...(kind==='gladi'?{damageReduction:.15}:{} )},level:lv});
 if(area===1)return[make(trainingEnemyTemplate('c-cockpit'),90,'cockpit',2),make(trainingEnemyTemplate('boss-mira'),93,'mira',3),make(trainingEnemyTemplate('c-cockpit'),90,'cockpit',2)];
 if(area===2)return[make(trainingEnemyTemplate('boss-gladi'),93,'gladi',3,4)];
 return[make(trainingEnemyTemplate('boss-yami-money'),96,'yami',4)];
}
const nmBuildBaseV239=buildEnemyFromTemplate;
buildEnemyFromTemplate=function(t,...args){const e=nmBuildBaseV239(t,...args);if(t.nightmareV239){e.nightmareV239=t.nightmareV239;e.actionCount=e.v144ActionMin=t.nightmareV239==='cockpit'?2:t.nightmareV239==='yami'?4:3;e.v144ActionMax=t.nightmareV239==='gladi'?4:e.actionCount;e.forceActionCount=true;}return e;};
const nmEnemyBaseV239=enemyAction;
enemyAction=async function(index=1,uid){const e=enemyByUid(uid),b=state.battle;if(!e?.nightmareV239||!['gladi','yami'].includes(e.nightmareV239))return nmEnemyBaseV239(index,uid);if(!b||b.finished||e.hp<=0||statusStopsActionV235(e))return;if(e.status.confuse>0)return confusedActionV235(e,true);const prev=b.actingEnemyId,old=b.enemy;b.actingEnemyId=e.uid;b.enemy=e;try{if(e.nightmareV239==='gladi'){if(index===1){const special=b.gladiSpecialReady&&b.turn>=Number(b.gladiSpecialTurnV178||0)?{special:'グラビディ・グラディエーター',kind:'aoeStun',power:1.55,chance:.70,skillElement:'無',skillType:'physical'}:{special:e.special,kind:e.kind,power:e.power,skillType:e.skillType,skillElement:e.skillElement||e.attribute};if(special.special==='グラビディ・グラディエーター')b.gladiSpecialReady=false;await bossSpecial(special);}else await bossNormal();}else{if(index===1&&b.turn%(e.specialEvery||TEMP_BALANCE.bossSpecialEvery)===0)await bossSpecial(enemySpecialSpec(e));else await bossNormal();}}finally{b.actingEnemyId=prev;b.enemy=old;renderBattle();}};
// Before turn 3's commands are made available; this event is applied exactly once.
const nmRoundBaseV239=startRound;
startRound=async function(...args){const b=state.battle,e=b?.enemies?.find(e=>e.nightmareV239==='yami');if(e&&b.turn===3&&!b.nightmareHelpV239&&!b.finished){b.nightmareHelpV239=true;b.busy=true;await nmBattleHelpV239(e);e.damageReduction=0;e.magicDamageReductionV180=0;e.def=Math.max(1,Math.round(e.def*.4));e.defBuff=0;renderBattle();}return nmRoundBaseV239(...args);};
async function nmBattleHelpV239(e){await enemyStoryCutin({...e,name:'モブマニー'},'（たす・・けて・・）');await allyStoryCutin('jessie','モブマニー・・！！');await actionCutin('ヤミモブマニーのダメージ軽減とDEFが大幅ダウン！\n今のうちに攻撃だ！','buff',1500);}
const nmAreaBaseV239=startSavannaAreaV174;
startSavannaAreaV174=async function(...args){const r=eventRunV174;if(r?.storyV179!=='nightmare')return nmAreaBaseV239(...args);eventOverlayV163().hidden=true;try{await nmSceneV239('pre');if(r.area===0){nmResultV239(true);return;}const bg=storySceneBg('neon',r.area);await startBattleLoaded({mode:'eventStory174',storyEventV174:true,storyV179:'nightmare',nightmareV239:true,worldId:'neon',returnScreen:'training',party:state.party,questVitals:r.vitals,enemyConfigs:nmWaveV239(r.area),bg:bg.bg,fallbackBg:bg.fallback});$('#battleModeLabel').textContent=`ネオン街の悪夢 / AREA ${r.area+1}`;}catch(error){console.error('[nightmare239]',error);returnSavannaV174();toast('イベントの準備に失敗しました。もう一度お試しください。');}};
const nmFinishBaseV239=finishSavannaV174;
finishSavannaV174=async function(b,win){const r=eventRunV174;if(r?.storyV179!=='nightmare')return nmFinishBaseV239(b,win);if(b.finished)return;b.finished=true;b.auto=false;setCommandDisabled(true);$('#battleScreen').classList.add('mint-battle-preparing-v237');if(win){for(const a of b.allies)r.vitals[a.id]={hp:a.hp,mp:a.mpNow,dead:a.dead,status:{...a.status}};applyProgressRewards(b,r.vitals);await nmSceneV239('post');if(r.area===3){recordsV179('nightmare').clear=true;saveMeta();}}nmResultV239(win);};
function nmResultV239(win){const r=eventRunV174,ov=eventOverlayV163(),last=r.area===3;ov.innerHTML=`<section class="event-result-v163 nm-result-v239"><small>ネオン街の悪夢</small><h2>${win?(last?'QUEST CLEAR':'AREA CLEAR'):'DEFEAT'}</h2><p>AREA ${r.area+1}</p><button class="primary-btn" data-nm-next>${win&&!last?'次のAreaへ':'クエストへ戻る'}</button></section>`;ov.hidden=false;$('[data-nm-next]',ov).onclick=async function(){this.disabled=true;if(win&&!last){r.area++;await startSavannaAreaV174();}else returnSavannaV174();};}
const nmReturnBaseV239=returnSavannaV174;
returnSavannaV174=function(...args){document.querySelector('.nm-stage-v239')?.remove();$('#adventureScreen').classList.remove('nm-underlay-v239');return nmReturnBaseV239(...args);};
window.__mobBuildVersion='v239';
