function passiveTwoV221(id){return id==='yusha'?state.meta.bookCompleted===true:id==='money'?state.meta.moneyFriendsUnlocked===true:id==='desert'?state.meta.desertMiraPowerV120===true:false;}
player('lilith').image='boss/21.png';
for(const spec of PARTY_SPEC_V221){const p=player(spec.id);if(!p)continue;p.passive=spec.passive;PASSIVE_DESCRIPTIONS_V172[p.id]=spec.passiveText;for(let i=0;i<spec.ults.length;i++)if(p.ults[i]){p.ults[i].name=spec.ults[i].name;p.ults[i].desc=spec.ults[i].desc;}if(PASSIVE_EFFECTS_V175[p.id])PASSIVE_EFFECTS_V175[p.id]=spec.passiveText;}
function patchUltV221(id,index,fields){Object.assign(player(id).ults[index],fields);}
patchUltV221('yusha',0,{attackElement:'光'});patchUltV221('yusha',2,{attackElement:'雷',type:'magic'});patchUltV221('yusha',3,{attackElement:'火',type:'magic'});
patchUltV221('pink',0,{attackElement:'無'});patchUltV221('pink',2,{attackElement:'無',type:'magic'});patchUltV221('pink',3,{attackElement:'光'});
patchUltV221('nyoro',0,{kind:'aoeBurn',type:'physical',chance:.10});patchUltV221('nyoro',1,{kind:'aoeDamage',type:'physical'});
patchUltV221('nekoku',0,{sure:true});patchUltV221('nekoku',2,{chance:.50});
patchUltV221('denden',0,{hits:[1,3]});patchUltV221('riro',3,{kind:'riroFinalV221'});
patchUltV221('tetsu',0,{kind:'tetsuSweepV221'});patchUltV221('tetsu',3,{kind:'tetsuFinal'});
['kaijinFearV221','kaijinEvadeV221','kaijinGuardV221','kaijinFinalV221'].forEach((kind,i)=>patchUltV221('kaijin',i,{kind,attackElement:'闇',type:i===2?'magic':'physical',power:[1.65,2.2,2.2,2.72][i]}));
patchUltV221('lilith',1,{kind:'lilithSisters',power:1.3});patchUltV221('lilith',2,{kind:'aoeCrit',power:2.72,crit:.10});patchUltV221('lilith',3,{kind:'teamHealMpGuard'});

const detailBaseV221=openPlayerDetail;openPlayerDetail=function(pid){detailBaseV221(pid);if(!passiveTwoV221(pid))return;const spec=PARTY_SPEC_V221.find(p=>p.id===pid),section=document.createElement('section');section.className='player-passive-v172';const descriptions={yusha:'あのヒーローに変身中、味方が攻撃を受けると10%の確率で敵全体に通常攻撃の120%で反撃。',money:'ヤミモブマニーに変身中、バブルネオンは極大ダメージ、レッドブルーボムは極大全体攻撃に強化。',desert:'会心時、通常攻撃の100%で追撃し、耐性を無視して毒を付与。'};section.innerHTML=`<h3>パッシブⅡ</h3><b>${spec.secondary}</b><p>${descriptions[pid]}</p>`;$('#playerDetailBody')?.append(section);};
const ultBaseV221=performUltimate;performUltimate=async function(a,u,...args){if(String(a?.id).startsWith('helper218-'))return false;const saved={kind:u.kind,power:u.power};if(a.id==='money'&&a.transformedMoney&&passiveTwoV221('money')){if(u===a.ults[0])u.power=2.72;if(u===a.ults[1]){u.kind='aoeDamage';u.power=2.72;}}try{return await ultBaseV221(a,u,...args);}finally{Object.assign(u,saved);}};
let miraFollowupV221=false;
const hitBaseV221=applyEnemyDamageTo;applyEnemyDamageTo=function(a,e,...args){const r=hitBaseV221(a,e,...args);if(a?.id==='desert'&&passiveTwoV221('desert')&&r?.crit&&!r.miss&&e.hp>0&&!miraFollowupV221){miraFollowupV221=true;try{hitBaseV221(a,e,1,'physical',0);if(e.hp>0){(e.status??={}).poison=Math.max(e.status.poison||0,3);notice('ミラモブソウル','status');}}finally{miraFollowupV221=false;}}return r;};
const damageBaseV221=damageAlly;damageAlly=async function(a,...args){const b=state.battle,source=actingEnemy(),d=await damageBaseV221(a,...args);if(d>0&&state.battle===b&&!b.finished){const hero=livingField().find(x=>x.id==='yusha'&&x.transformed);if(hero&&passiveTwoV221('yusha')&&passiveChance(.10)){await reactivePassiveBeat(hero,'あのヒーローにやっつけてもらおう');await playerAoeDamage(hero,1.2,'physical');}if(a.id==='lilith'&&!a.dead&&source?.hp>0&&passiveChance(.10)){const spells=availableMagicSkillsV104(a).filter(s=>s.power>0);if(spells.length){await reactivePassiveBeat(a,'薔薇の魔女');const s=pick(spells),context=b.weaponAttackContext;b.weaponAttackContext={normal:false,element:s.element||'闇'};try{await skillSprite(s.frames||[],'enemy',s.mode);applyEnemyDamageTo(a,source,s.power,'magic');}finally{b.weaponAttackContext=context;}}}}return d;};
let doubleMagicV221=false;
const magicBaseV221=performMagic;performMagic=async function(a,skill,...args){const chosen=skill?.id?skill:defaultMagicFor(a),r=await magicBaseV221(a,skill,...args);if(r!==false&&!doubleMagicV221&&a.id==='jessie'&&normalizeElement(chosen.element||a.attribute)==='雷'&&livingEnemies().length&&passiveChance(.80)){doubleMagicV221=true;const mp=a.mpNow;try{await passiveBeat(a,'ダブルサンダー');a.mpNow=a.maxMp;await magicBaseV221(a,skill,...args);}finally{a.mpNow=mp;doubleMagicV221=false;}}return r;};
const roundBaseV221=startRound;startRound=async function(...args){const a=livingField().find(a=>a.id==='kaijin');if(a&&passiveChance(.10+.20*(1-a.hp/a.maxHp))){await passiveBeat(a,'理由は無いけど役目なの');for(const t of livingField())if(t!==a){t.damageCut=Math.max(t.damageCutTurns>0?t.damageCut:0,.20);t.damageCutTurns=1;}}return roundBaseV221(...args);};
const bombUltimateBaseV221=performUltimate;performUltimate=async function(a,u,...args){const previous=a.multiElementsV221;if(a.id==='money'&&u===a.ults[1])a.multiElementsV221=['火','水','光'];try{return await bombUltimateBaseV221(a,u,...args);}finally{a.multiElementsV221=previous;}};
const elementalDamageBaseV221=calcDamage;calcDamage=function(a,type,power,crit,e=targetEnemy()){const context=state.battle?.weaponAttackContext;if(!a?.multiElementsV221||!context)return elementalDamageBaseV221(a,type,power,crit,e);const old=context.element;context.element=[...a.multiElementsV221].sort((x,y)=>elementDamageMultiplier(y,e.attribute)-elementDamageMultiplier(x,e.attribute))[0];try{return elementalDamageBaseV221(a,type,power,crit,e);}finally{context.element=old;}};
const finishPartyBaseV221=finishBattle;finishBattle=function(...args){const b=state.battle;if(b?.config?.legendV218){resetBookTransformV216(b);for(const a of b.allies||[])if(a.transformedMoney){a.transformedMoney=false;a.allBuff=0;a.allBuffTurns=0;a.moneyFriendsMagicCrit=0;a.moneyFriendsStatusResist=0;}}return finishPartyBaseV221(...args);};
