/* Rush-only formation, global tier gates and cancellable hologram presentations. */
const rushQuestLevelV255=(q,t)=>Math.max(RUSH_DATA_V252.difficulties[t].minLevel,q.recommendedLevel+RUSH_DATA_V252.difficulties[t].levelOffset);
const rushTierCountV255=t=>RUSH_DATA_V252.quests.filter(q=>rushTierV254(q,t)).length;
function rushTierGateLabelV255(t){return t?`${RUSH_DATA_V252.difficulties[t-1].name}全8件クリアで解放（${rushTierCountV255(t-1)}/8）`:'地域条件で解放';}
rushTierOpenV254=(q,t=rushDifficultyV254)=>!!q&&rushUnlockedV252(q)&&(t===0||RUSH_DATA_V252.quests.every(row=>rushTierV254(row,t-1)));
function rushPartyErrorV255(q,rows){if(!Array.isArray(rows)||rows.length!==4)return '4人ちょうどを選んでください';const ids=rows.map(row=>row?.[0]);if(new Set(ids).size!==4)return '同じ仲間は重複できません';if(!ids.includes(q.requiredCharacter))return `${player(q.requiredCharacter)?.name}が必須です`;if(rows.some(row=>!state.party.some(p=>p[0]===row[0]&&p[1]===row[1])))return '加入済みの仲間を選んでください';return '';}
function rushFormationV255(q){let el=$('#rushFormationV255');if(!el){el=document.createElement('div');el.id='rushFormationV255';el.className='rush-formation-v255';document.body.append(el);}el.hidden=false;const roster=state.party.filter(row=>player(row[0])),required=roster.find(row=>row[0]===q.requiredCharacter),free=roster.filter(row=>row[0]!==q.requiredCharacter);
 el.innerHTML=`<section role="dialog" aria-modal="true" aria-label="ラッシュ専用編成"><h2>${rushTextV252(q.title)}</h2><p>必須1人＋自由3人 / 4人限定</p><div class="rush-required-v255"><img src="${player(q.requiredCharacter).image}" alt=""><b>${rushTextV252(player(q.requiredCharacter).name)} 必須</b><small>${required?'Lv.'+required[1]:rushTextV252(q.requiredCharacterHelp)}</small></div>${[0,1,2].map(i=>`<label>自由枠${i+1}<select data-rush-slot>${free.map(([id,lv],j)=>`<option value="${id}" ${j===i?'selected':''}>${rushTextV252(player(id).name)} Lv.${lv}</option>`).join('')}</select></label>`).join('')}<p data-rush-party-error></p><small>通常の編成・レベルは変更しません<br>スーパーサブ・控え交代なし</small><button class="primary-btn" data-rush-deploy>この4人で挑戦</button><button data-rush-formation-close>戻る</button></section>`;bindImages(el);
 const rows=()=>[required,...$$('[data-rush-slot]',el).map(e=>roster.find(row=>row[0]===e.value))].filter(Boolean),refresh=()=>{const error=!required?q.requiredCharacterHelp:roster.length<4?RUSH_DATA_V252.partyRule.rosterHelp:rushPartyErrorV255(q,rows());$('[data-rush-party-error]',el).textContent=error;$('[data-rush-deploy]',el).disabled=!!error;};$$('[data-rush-slot]',el).forEach(e=>e.onchange=refresh);$('[data-rush-formation-close]',el).onclick=()=>{el.hidden=true;};$('[data-rush-deploy]',el).onclick=async function(){this.disabled=true;const team=rows();if(rushPartyErrorV255(q,team)){refresh();return;}el.hidden=true;await startRushV252(q.id,team);};refresh();
}
rushWavesV252=function(q,index){const tier=eventRunV174?.tier??rushDifficultyV254,diff=RUSH_DATA_V252.difficulties[tier];return q.areas[index].waves.map(w=>w.map(row=>{const t=clone(RUSH_DATA_V252.enemies[row.enemy]);t.mods={...t.mods,hp:(t.mods?.hp||1)*diff.hp,atk:(t.mods?.atk||1)*diff.attack,mag:(t.mods?.mag||1)*diff.attack};return {template:t,level:Math.max(diff.minLevel,row.level+diff.levelOffset)};}));};
startRushV252=async function(id,party){const q=rushQuestV252(id),tier=rushDifficultyV254;if(rushStartingV252||eventRunV174||!rushTierOpenV254(q,tier))return false;if(!party){rushFormationV255(q);return false;}const error=rushPartyErrorV255(q,party);if(error){toast(error);return false;}rushStartingV252=true;try{if(!await confirmStoryChallengeV179(q.title,`${RUSH_DATA_V252.difficulties[tier].name} / クエストLv.${rushQuestLevelV255(q,tier)} / 4人限定`))return false;if(eventRunV174||!rushTierOpenV254(q,tier)||rushPartyErrorV255(q,party))return false;eventRunV174={rushV252:id,tier,difficulty:0,area:0,wave:0,vitals:{},rewarded:false,party:clone(party)};$('#trainingFeaturePopup').hidden=true;await startRushAreaV252(eventRunV174);return true;}catch(e){console.error('[rush255]',e);await returnRushV252();toast('準備に失敗しました');return false;}finally{rushStartingV252=false;}};
// Config-local party keeps normal formation, saveParty and all reserve ownership intact.
const rushBeginBaseV255=beginBattle;
beginBattle=async function(config){if(config?.rushV252){const r=eventRunV174,q=rushQuestV252(config.rushV252);if(!r||r.closing||r.rushV252!==q?.id)throw Error('Inactive rush');const error=rushPartyErrorV255(q,config.party);if(error||JSON.stringify(config.party)!==JSON.stringify(r.party))throw Error(error||'Rush party changed');}return rushBeginBaseV255(config);};
const rushLoadedBaseV255=startBattleLoaded;
startBattleLoaded=async function(config){if(config?.rushV252){const r=eventRunV174;if(!r||r.closing)return;config={...config,party:clone(r.party)};}return rushLoadedBaseV255(config);};
let rushFxCancelV255=null;
function rushFxV255(kind,r,bosses=[]){if(eventRunV174!==r)return Promise.resolve();rushFxCancelV255?.();let el=$('#rushFxV255');if(!el){el=document.createElement('div');el.id='rushFxV255';document.body.append(el);}const spec=RUSH_DATA_V252.presentation,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,ms=reduced?spec.reducedMs:spec[kind==='start'?'startMs':kind==='boss'?'bossMs':'endMs'];el.className=`rush-fx-v255 ${kind==='boss'?'boss':''} ${reduced?'reduced':''}`;el.hidden=false;
 el.innerHTML=`<section role="dialog" aria-modal="true" aria-label="${kind==='boss'?'ボス出現':'ホログラム転送'}"><div class="rush-code-v255" aria-hidden="true">${Array.from({length:12},(_,i)=>`<span style="--i:${i}">01 MOB 10<br>101001<br>RUSH 010<br>011 110<br>MATRIX<br>101001</span>`).join('')}</div><div class="rush-scan-v255"></div><div class="rush-ring-v255"></div><small>${kind==='boss'?'BOSS SIGNAL / OVERDRIVE':'MOB HOLO / MATRIX LINK'}</small><div class="rush-fx-art-v255">${(kind==='boss'?bosses:[RUSH_DATA_V252.narrator]).filter(x=>x.image).map(x=>`<img src="${x.image}" alt="${rushTextV252(x.name)}">`).join('')}</div><h2>${rushTextV252(spec[kind])}</h2>${kind==='boss'?`<p>${bosses.map(e=>rushTextV252(e.name)).join(' / ')}</p>`:''}<p data-rush-fx-phase>データ走査中</p><progress max="100" value="0"></progress><button data-rush-fx-skip>演出を短縮</button>${!r.closing?'<button data-rush-fx-abort>中断して戻る</button>':''}</section>`;bindImages(el);
 return new Promise(resolve=>{let done=false;const start=performance.now();let timer,tick;const finish=()=>{if(done)return;done=true;clearTimeout(timer);clearInterval(tick);el.hidden=true;if(rushFxCancelV255===finish)rushFxCancelV255=null;resolve();};rushFxCancelV255=finish;tick=setInterval(()=>{const p=Math.min(100,(performance.now()-start)/ms*100);$('progress',el).value=p;$('[data-rush-fx-phase]',el).textContent=p<35?'データ走査中':p<75?'ホログラム再構成中':'転送準備完了';},60);timer=setTimeout(finish,ms);$('[data-rush-fx-skip]',el).onclick=()=>{if(performance.now()-start>=150)finish();else setTimeout(finish,150);};$('[data-rush-fx-abort]',el)?.addEventListener('click',()=>{void returnRushV252();});});
}
const rushDialogueBaseV255=rushDialogueV252;
rushDialogueV252=async function(lines,r){if(r.closing||eventRunV174!==r)return;if(!r.introDone){r.introDone=true;await rushFxV255('start',r);}const b=state.battle,q=rushQuestV252(r.rushV252);if(b?.config?.rushV252===r.rushV252&&b.finished&&(!b.rushWonV252||r.area===q.areas.length-1)&&!r.outroDone){r.outroDone=true;await rushFxV255(b.rushWonV252?'win':'defeat',r);}if(!r.closing&&eventRunV174===r)return rushDialogueBaseV255(lines,r);};
const rushRoundBaseV255=startRound;
startRound=async function(...args){const r=eventRunV174,b=state.battle;if(b?.config?.rushV252&&r){if(r.closing||b.finished||r.bossPending)return;const key=`${r.area}:${r.wave}`,bosses=b.enemies.filter(e=>['boss','elite'].includes(e.category)||['boss','elite'].includes(RUSH_DATA_V252.enemies[e.id]?.category)||e.story179Kind==='phoenix');r.bossSeen??={};if(bosses.length&&!r.bossSeen[key]){r.bossSeen[key]=true;r.bossPending=true;b.busy=true;try{await rushFxV255('boss',r,bosses);}finally{r.bossPending=false;}if(eventRunV174!==r||r.closing||state.battle!==b||b.finished)return;b.busy=false;}}return rushRoundBaseV255(...args);};
async function rushExitV255(r,exit){if(r.exitPromise)return r.exitPromise;r.closing=true;if(state.battle?.config?.rushV252){state.battle.finished=true;state.battle.auto=false;state.battle.queue=[];setCommandDisabled(true);}rushFxCancelV255?.();rushHoloResolveV254?.();if($('#rushHoloV254'))$('#rushHoloV254').hidden=true;r.exitPromise=(async()=>{if(!r.outroDone){r.outroDone=true;await rushFxV255('abort',r);}return exit();})();return r.exitPromise;}
const rushReturnBaseV255=returnRushV252;
returnRushV252=function(){const r=eventRunV174;return r?.rushV252?rushExitV255(r,()=>rushReturnBaseV255()):rushReturnBaseV255();};
const rushHomeBaseV255=goHome;
goHome=function(...args){const r=eventRunV174;return r?.rushV252?rushExitV255(r,()=>rushHomeBaseV255(...args)):rushHomeBaseV255(...args);};
const rushClearBaseV255=clearRushV252;
clearRushV252=function(){const r=eventRunV174;if(r?.rushV252){r.closing=true;rushFxCancelV255?.();}return rushClearBaseV255();};
window.__mobBuildVersion='v255';

startRushAreaV252=async function(r){if(eventRunV174!==r||r.closing)return;const q=rushQuestV252(r.rushV252),a=q.areas[r.area];eventOverlayV163().hidden=true;
 await rushDialogueV252(a.pre,r);if(eventRunV174!==r||r.closing)return;const bg=storySceneBg(q.world,r.area);
 await startBattleLoaded({mode:'eventStory174',storyEventV174:true,rushV252:q.id,worldId:q.world,returnScreen:'training',party:r.party,questVitals:r.vitals,waves:rushWavesV252(q,r.area),bg:bg.bg,fallbackBg:bg.fallback,...(a.waves.some(w=>w.some(e=>e.enemy==='v179-phoenix'))?{storyV179:'phoenix'}:{})});
 if(eventRunV174!==r||r.closing)return;if(state.battle?.config?.rushV252!==q.id)throw Error('Rush battle not started');rushLabelV252();$('#battleBackBtn').style.display='';$('#battleBackBtn').disabled=false;
}
;

const rushMenuBaseV255=rushMenuV252;
rushMenuV252=function(){rushMenuBaseV255();for(const q of RUSH_DATA_V252.quests){const card=$('[data-rush-card="'+q.id+'"]');if(card&&!$('.rush-required-v255',card)){const p=document.createElement('p');p.className='rush-required-v255';p.textContent=player(q.requiredCharacter).name+' 必須＋自由3人 / 4人限定';$('h3',card).after(p);}}};
