/* Three-tier hologram simulations; original region/event definitions are untouched. */
let rushDifficultyV254=0,rushHoloResolveV254=null;
const rushTierV254=(q,t=rushDifficultyV254)=>!!state.meta.monsterRushV254?.[q.id]?.cleared?.[t]||(t===0&&!!state.meta.monsterRushV252?.[q.id]);
const rushTierOpenV254=(q,t=rushDifficultyV254)=>rushUnlockedV252(q)&&(t===0||rushTierV254(q,t-1));
function rushBestV254(q){return Math.max(0,...[0,1,2].filter(t=>rushTierV254(q,t)));}
function syncRushMedalsV254(){for(const q of RUSH_DATA_V252.quests){const source=rushMedalV253(q.reward),target=WEAPONS.find(m=>m.id===q.reward),tier=source.tiers[rushBestV254(q)];Object.assign(target,clone(tier));}}
syncRushMedalsV254();
const rushCheckpointBaseV254=restoreCampCheckpoint;
restoreCampCheckpoint=function(...args){const records=clone(state.meta.monsterRushV254||{}),legacy=clone(state.meta.monsterRushV252||{}),medals=Object.fromEntries(RUSH_DATA_V252.medals.map(m=>[m.id,medalOwned(m.id)]));const result=rushCheckpointBaseV254(...args);state.meta.monsterRushV254=records;state.meta.monsterRushV252=legacy;state.meta.medals??={};for(const [id,n] of Object.entries(medals))if(n)state.meta.medals[id]=Math.max(n,medalOwned(id));syncRushMedalsV254();saveMeta();return result;};
// Preserve passive state changes; omit character speech only inside rush combat.
const rushEnemySpeechV254=enemyStoryCutin,rushAllySpeechV254=allyStoryCutin;
enemyStoryCutin=async function(...args){if(!state.battle?.config?.rushV252)return rushEnemySpeechV254(...args);};
allyStoryCutin=async function(...args){if(!state.battle?.config?.rushV252)return rushAllySpeechV254(...args);};
const rushEnemyBaseV254=buildEnemyFromTemplate;
buildEnemyFromTemplate=function(t,...args){const e=rushEnemyBaseV254(t,...args);if(t?.rushPassive){const p=t.rushPassive;e.rushPassive=clone(p);e.elementResist={...e.elementResist,[p.element]:Math.min(.75,(e.elementResist?.[p.element]||0)+p.value)};}return e;};
rushOpenV252=q=>!!q&&rushTierOpenV254(q);
rushWavesV252=function(q,index){const diff=RUSH_DATA_V252.difficulties[eventRunV174?.tier??rushDifficultyV254];return q.areas[index].waves.map(w=>w.map(row=>{const t=clone(RUSH_DATA_V252.enemies[row.enemy]);t.mods={...t.mods,hp:(t.mods?.hp||1)*diff.hp,atk:(t.mods?.atk||1)*diff.attack,mag:(t.mods?.mag||1)*diff.attack};return {template:t,level:row.level+diff.levelOffset};}));};
startRushV252=async function(id){const q=rushQuestV252(id),tier=rushDifficultyV254;if(rushStartingV252||eventRunV174||!rushTierOpenV254(q,tier))return false;rushStartingV252=true;try{
 if(!await confirmStoryChallengeV179(q.title,`${RUSH_DATA_V252.difficulties[tier].name} / 推奨Lv.${q.recommendedLevel+RUSH_DATA_V252.difficulties[tier].levelOffset}`))return false;
 if(eventRunV174||!rushTierOpenV254(q,tier))return false;eventRunV174={rushV252:id,tier,difficulty:0,area:0,wave:0,vitals:{},rewarded:false};$('#trainingFeaturePopup').hidden=true;await startRushAreaV252(eventRunV174);return true;
 }catch(e){console.error('[rush254]',e);returnRushV252();toast('準備に失敗しました');return false;}finally{rushStartingV252=false;}};
rewardRushV252=function(r,b){const q=rushQuestV252(r?.rushV252);if(!q||eventRunV174!==r||state.battle!==b||!b.finished||!b.rushWonV252||r.rewarded||r.area!==q.areas.length-1||b.pendingWaveConfigs.length||r.wave!==q.areas[r.area].waves.length-1||livingEnemies().length)return false;r.rewarded=true;
 // One completion payment per in-memory run, before the result dialogue. Runs are never resumed after reload.
 const coins=q.clearCoins[r.tier];r.coinReward=coins;state.coins=Math.max(0,Number(state.coins)||0)+coins;state.meta.coins=state.coins;
 // Include the same fixed award in the existing rollback checkpoint once; restoring it never adds another award.
 const cp=state.adventure?.checkpoint;if(cp){cp.coins=Math.max(0,Number(cp.coins)||0)+coins;if(cp.meta)cp.meta.coins=cp.coins;}
 if(rushTierV254(q,r.tier)){r.rewardOutcome='メダル：'+RUSH_DATA_V252.narrator.messages.alreadyClaimed;saveMeta();if(cp)saveAdventure();return false;}
 state.meta.monsterRushV254??={};const record=state.meta.monsterRushV254[q.id]??={cleared:[!!state.meta.monsterRushV252?.[q.id],false,false]};record.cleared[r.tier]=true;
 state.meta.monsterRushV252??={};state.meta.monsterRushV252[q.id]=true;state.meta.medals??={};const had=medalOwned(q.reward)>0;state.meta.medals[q.reward]=Math.max(1,medalOwned(q.reward));syncRushMedalsV254();saveMeta();if(cp)saveAdventure();r.rewardOutcome=had?RUSH_DATA_V252.narrator.messages.upgraded:RUSH_DATA_V252.narrator.messages.received;return true;
};
function rushHoloOverlayV254(){let el=$('#rushHoloV254');if(!el){el=document.createElement('div');el.id='rushHoloV254';el.className='rush-holo-overlay-v254';el.hidden=true;document.body.append(el);}return el;}
rushDialogueV252=async function(lines,r){if(eventRunV174!==r)return;const el=rushHoloOverlayV254(),n=RUSH_DATA_V252.narrator;storyBusy=true;try{for(const line of lines){if(eventRunV174!==r)break;el.innerHTML=`<section role="dialog" aria-modal="true" aria-label="${rushTextV252(n.name)}"><div class="rush-holo-portrait-v254">${n.image?`<img src="${n.image}" alt="${rushTextV252(n.name)}">`:''}<i></i></div><div class="rush-holo-copy-v254"><small>HOLOGRAM / RUSH LAB</small><h2>${rushTextV252(n.name)}</h2><p>${line.text.split('\n').map(s=>`<span>${rushTextV252(s)}</span>`).join('')}</p><button class="primary-btn" data-holo-next>次へ</button><button data-holo-home>HOMEへ</button></div></section>`;el.hidden=false;bindImages(el);await new Promise(resolve=>{rushHoloResolveV254=resolve;$('[data-holo-next]',el).onclick=()=>{rushHoloResolveV254=null;resolve();};$('[data-holo-home]',el).onclick=()=>goHome();});}}finally{el.hidden=true;storyBusy=false;rushHoloResolveV254=null;}};
const rushClear254=clearRushV252;clearRushV252=function(){const done=rushClear254();if(done){const resolve=rushHoloResolveV254;rushHoloResolveV254=null;resolve?.();if($('#rushHoloV254'))$('#rushHoloV254').hidden=true;}return done;};
finishSavannaV174=async function(b,win){if(!b?.config?.rushV252)return rushFinishBaseV252(b,win);const r=eventRunV174;if(!r||b.finished||b.rushTransitionV252||win&&(livingEnemies().length||b.pendingWaveConfigs.length))return;b.finished=true;b.auto=false;b.rushWonV252=!!win;setCommandDisabled(true);persistUltimateCooldownsFromBattle();const q=rushQuestV252(r.rushV252),last=r.area===q.areas.length-1;
 if(win){for(const a of b.allies)r.vitals[a.id]={hp:a.hp,mp:a.mpNow,dead:a.dead,status:{...a.status}};if(last)rewardRushV252(r,b);}
 await rushDialogueV252(win?q.areas[r.area].post:RUSH_DATA_V252.narrator.defeat,r);if(eventRunV174!==r)return;
 const ov=eventOverlayV163(),m=weaponById(q.reward),diff=RUSH_DATA_V252.difficulties[r.tier];ov.innerHTML=`<div class="event-result-v163 rush-result-v252"><small>${rushTextV252(q.title)} / ${diff.name}</small><h2>${win?last?'QUEST CLEAR!!':'AREA CLEAR!':'DEFEAT'}</h2>${win&&last?`<p class="rush-coins-v254"><strong>完走報酬 +${Number(r.coinReward||0).toLocaleString()}G</strong></p>${rushMedallionV253(m,true)}<p>${rushTextV252(m.name)}<br>${rushTextV252(r.rewardOutcome)}</p><p>${rushTextV252(weaponStatsText(m,.1))}</p><p class="rush-traits-v253">${rushTextV252(m.traitLabel)}</p>`:`<p>${rushTextV252(win?RUSH_DATA_V252.narrator.messages.continueArea:RUSH_DATA_V252.narrator.messages.noReward)}</p>`}<button class="primary-btn" data-rush-next>${win&&!last?'次のAREAへ':'クエストへ戻る'}</button><button data-rush-home>HOMEへ</button></div>`;ov.hidden=false;bindImages(ov);
 $('[data-rush-next]',ov).onclick=async function(){this.disabled=true;if(win&&!last){r.area++;r.wave=0;try{await startRushAreaV252(r);}catch(e){console.error(e);returnRushV252();}}else returnRushV252();};$('[data-rush-home]',ov).onclick=()=>goHome();
};
rushMenuV252=function(){const root=$('#trainingFeaturePanel');root.hidden=false;const diff=RUSH_DATA_V252.difficulties[rushDifficultyV254],list=RUSH_DATA_V252.quests.filter(q=>rushFilterV253==='open'?rushTierOpenV254(q):rushFilterV253==='locked'?!rushTierOpenV254(q):rushFilterV253==='clear'?rushTierV254(q):true).slice().sort((a,b)=>a.recommendedLevel-b.recommendedLevel),pages=Math.max(1,Math.ceil(list.length/4));rushPageV253=clamp(rushPageV253,0,pages-1);
 root.innerHTML=`<section class="event-panel-v163 rush-panel-v252"><header><h2>モンスターラッシュ</h2><button data-rush-back>戻る</button></header><p>30ステージ / 各3難度 / 同時2〜3体<br>上位難度の初回勝利でメダルを強化<br>毎回の完走でG獲得 / 途中終了は0G<br>HP・MPを引き継ぐっちゃ</p><label class="rush-filter-v253">難易度<select data-rush-difficulty>${RUSH_DATA_V252.difficulties.map((t,i)=>`<option value="${i}" ${i===rushDifficultyV254?'selected':''}>${t.name}</option>`).join('')}</select></label><label class="rush-filter-v253">表示<select data-rush-filter>${[['all','すべて'],['open','挑戦可能'],['locked','未解放'],['clear','クリア済み']].map(([v,t])=>`<option value="${v}" ${v===rushFilterV253?'selected':''}>${t}</option>`).join('')}</select><span>${list.length}件</span></label><nav class="rush-pages-v253"><button data-rush-page="-1" ${rushPageV253===0?'disabled':''}>前へ</button><b>${rushPageV253+1} / ${pages}</b><button data-rush-page="1" ${rushPageV253===pages-1?'disabled':''}>次へ</button></nav><div class="rush-list-v252">${list.slice(rushPageV253*4,rushPageV253*4+4).map(q=>{const unlocked=rushUnlockedV252(q),src=rushMedalV253(q.reward),m={...src,...src.tiers[rushDifficultyV254]};return `<article class="rush-card-v252" data-rush-card="${q.id}"><img class="rush-icon-v252" src="${RUSH_DATA_V252.icon}" alt="RUSH"><div><h3>${rushTextV252(q.title)}</h3><p>${q.areas.length} AREA / 推奨Lv.${q.recommendedLevel+diff.levelOffset}<br>${unlocked?rushDifficultyV254?'前難度クリアで解放':'解放済み':rushTextV252(q.unlock.label)+'で解放'}</p>${unlocked?`<div class="rush-medal-info-v253">${rushMedallionV253(m)}<b>${rushTextV252(m.name)}</b></div><p>完走報酬 ${q.clearCoins[rushDifficultyV254].toLocaleString()}G<br>初回・再戦とも同額</p><p>この難度の到達性能<br>${rushTextV252(weaponStatsText(m,.1))}</p><p class="rush-traits-v253">${rushTextV252(m.traitLabel)}</p>`:'<p>解放後にメダル公開</p>'}<button class="primary-btn" data-rush-start="${q.id}" ${rushTierOpenV254(q)?'':'disabled'}>${rushTierV254(q)?'再挑戦 / G獲得':'挑戦する'}</button></div></article>`;}).join('')||'<p>該当なし</p>'}</div></section>`;
 $('[data-rush-back]',root).onclick=()=>{eventViewV163='story';selectedStoryV179=null;renderEventQuestsV163();};$('[data-rush-difficulty]',root).onchange=e=>{rushDifficultyV254=Number(e.target.value);rushPageV253=0;rushMenuV252();};$('[data-rush-filter]',root).onchange=e=>{rushFilterV253=e.target.value;rushPageV253=0;rushMenuV252();};$$('[data-rush-page]',root).forEach(b=>b.onclick=()=>{rushPageV253+=Number(b.dataset.rushPage);rushMenuV252();});$$('[data-rush-start]',root).forEach(b=>b.onclick=()=>startRushV252(b.dataset.rushStart));bindImages(root);
};
window.__mobBuildVersion='v254';
