/* SOUL is battle-local; a new battle initializes it, waves preserve it. */
const soulStatV218={HP:'maxHp',LIFE:'maxHp',MP:'maxMp',ATK:'atk',MAG:'mag',DEF:'def',MND:'res',SPD:'spd'};
const soulStatusV218={毒:'poison',やけど:'burn',マヒ:'paralyze',眠り:'sleep',ひるみ:'stun',混乱:'confuse'};
function figureSoulV218(a,id){a.figureSoulV218??={};return a.figureSoulV218[id]??=0;}
const cooldownBaseV218=advanceUltimateCooldowns;advanceUltimateCooldowns=function(a,...args){const r=cooldownBaseV218(a,...args);for(const id of a?.figureEquipment||[])if(figureById(id)?.soul)a.figureSoulV218={...(a.figureSoulV218||{}),[id]:Math.min(figureById(id).soul.cost,figureSoulV218(a,id)+1)};return r;};
function figureActiveV218(a,id){return !!a&&!a.dead&&a.hp>0&&a.figureEquipment?.includes(id)&&!!figureById(id)?.soul;}
const soulRenderBaseV218=renderBattle;renderBattle=function(...args){const r=soulRenderBaseV218(...args),a=activeAlly(),b=state.battle;$('#figureSoulBarV218')?.remove();if(!a||!b||b.finished)return r;const ids=(a.figureEquipment||[]).filter(Boolean);if(!ids.length)return r;
 const bar=document.createElement('div');bar.id='figureSoulBarV218';bar.setAttribute('aria-label',a.name+'のメインフィギュア');bar.innerHTML=ids.map(id=>{const f=figureById(id);if(!f)return'';const n=f.soul?figureSoulV218(a,id):0,ready=f.soul&&n>=f.soul.cost;return`<button data-soul="${id}" class="${ready?'ready':''}" ${!f.soul||b.busy?'disabled':''} aria-label="${f.name}${f.soul?` SOUL ${n}/${f.soul.cost}`:' スキルなし'}"><img src="${f.image}" alt=""><small>${f.soul?`${n}/${f.soul.cost}`:'超合金'}</small></button>`;}).join('');$('#activeActorBar').before(bar);$$('[data-soul]',bar).forEach(btn=>btn.onclick=()=>useFigureSoulV218(a,btn.dataset.soul));return r;};
async function soulCutinV218(f){const el=document.createElement('div');el.className='soul-cutin-v218';el.innerHTML=`<img src="${f.image}" alt="${f.name}"><strong>フィギュアスキル発動!!</strong><b>${f.soul.name}</b>`;document.body.append(el);try{await fixedDelay(1050);}finally{el.remove();}}
function soulEffectValueV218(unit,key){return(unit.soulEffectsV218||[]).filter(x=>x.key===key&&x.until>(state.battle?.turn||0)).reduce((sum,x)=>sum+x.value,0);}
function soulBuffV218(unit,key,value,turns=2){unit.soulEffectsV218??=[];unit.soulEffectsV218.push({key,value,until:(state.battle?.turn||1)+turns});}
const effectiveBaseV218=effective;effective=function(stat,obj){return effectiveBaseV218(stat,obj)*Math.max(.1,1+soulEffectValueV218(obj,stat));};
const enemyDefenseBaseV218=enemyDefense;enemyDefense=function(type,e=targetEnemy()){return enemyDefenseBaseV218(type,e)*Math.max(.1,1+soulEffectValueV218(e,type==='magic'?'res':'def'));};
const enemyDamageBaseV218=calcEnemyDamage;calcEnemyDamage=function(a,power,type='physical'){const e=actingEnemy();return enemyDamageBaseV218(a,power*Math.max(.1,1+soulEffectValueV218(e||{},type==='magic'?'mag':'atk')),type);};
const speedBaseV218=initiativeSpeed;initiativeSpeed=function(entry){const n=speedBaseV218(entry);return entry.type==='enemy'?n*Math.max(.1,1+soulEffectValueV218(enemyByUid(entry.enemyId)||{},'spd')):n;};
const evadeBaseV218=weaponEvasion;weaponEvasion=a=>clamp(evadeBaseV218(a)+soulEffectValueV218(a,'evade'),0,.8);
const resistBaseV218=weaponResistance;weaponResistance=function(a,el){return clamp(resistBaseV218(a,el)+soulEffectValueV218(a,'resist:'+el)+soulEffectValueV218(a,'resist:all'),0,.9);};
const soulDamageBaseV218=damageAlly;damageAlly=async function(a,power,type='physical',...args){const e=actingEnemy(),ignore=e?.story179Kind==='phoenix'&&(e.phoenixIgnoreV218||Math.random()<.5);const fe=a.figureEffects,guard=a.guard,cut=a.damageCut,book=a.bookHeroDamageCut;try{if(ignore){a.figureEffects={...fe,damageCut:0,physicalCut:0,magicCut:0};a.guard=0;a.damageCut=0;a.bookHeroDamageCut=0;}const extra=soulEffectValueV218(a,'damageCut')+soulEffectValueV218(a,type==='magic'?'magicCut':'physicalCut');if(e?.story179Kind==='phoenix'&&state.battle.turn>=3)power*=1.3;return await soulDamageBaseV218(a,power*(ignore?1:1-clamp(extra,0,.8)),type,...args);}finally{a.figureEffects=fe;a.guard=guard;a.damageCut=cut;a.bookHeroDamageCut=book;}};
const soulPlayerDamageBaseV218=applyEnemyDamageTo;applyEnemyDamageTo=function(a,e,power,type='physical',crit=0,...args){return soulPlayerDamageBaseV218(a,e,power*(1+soulEffectValueV218(a,type==='magic'?'magicDamage':'physicalDamage')+soulEffectValueV218(a,'damage:'+attackElementFromContext(a,type))),type,crit+soulEffectValueV218(a,'crit'),...args);};

/* Each clause keeps its target until an explicit new target appears. */
function soulClausesV218(text){const s=String(text).normalize('NFKC').replace(/さらに|攻撃後、?/g,'').replace(/HP[と・]MPを(\d+)(%?)回復/g,'HPを$1$2回復し、MPを$1$2回復').replace(/%・/g,'% & '),parts=s.split(/[。、]|し、|させ、|&/).map(x=>x.trim()).filter(Boolean);return parts.map((x,i)=>{if(/\d+%$/.test(x)&&!/会心率\d+%$/.test(x)){const next=parts.slice(i+1).find(x=>/アップ|ダウン/.test(x));if(next)x+=next.includes('ダウン')?'ダウン':'アップ';}return x;});}
function soulTargetsV218(clause,a,own,enemies,previous){if(/自分/.test(clause))return[a];if(/HPが最も低い味方/.test(clause))return[own.filter(x=>!x.dead&&x.hp>0).sort((x,y)=>x.hp/x.maxHp-y.hp/y.maxHp)[0]].filter(Boolean);if(/味方全体/.test(clause))return own.filter(x=>!x.dead&&x.hp>0);if(/センター/.test(clause))return[(/敵|相手/.test(clause)?enemies:own)[2]].filter(Boolean);if(/敵全体/.test(clause))return enemies.filter(x=>x.hp>0);if(/敵単体|正面の敵|敵1体/.test(clause))return[enemies.find(x=>x.hp>0)].filter(Boolean);return previous;}
async function applySoulTextV218(f,a,own,enemies,text,piece=false){
 let targets=piece?own:[a],defaultTurns=+(text.match(/(\d+)ターン/)?.[1]||2),dealt=0;
 for(const clause of soulClausesV218(text)){
  targets=soulTargetsV218(clause,a,own,enemies,targets);const turns=+(clause.match(/(\d+)ターン/)?.[1]||defaultTurns);
  if(!piece&&/ダメージを与|ダメージ$/.test(clause)&&!/ダメージ軽減/.test(clause)){
   const count=+(clause.match(/(?:×|連続|小ダメージを)(\d+)/)?.[1]||clause.match(/(\d+)(?:回|連続|連)/)?.[1]||1),element=clause.match(/([火水雷風地光闇無])属性/)?.[1]||clause.match(/([火水雷風地光闇無])(?:の)?(?:魔法|物理)/)?.[1]||'無',type=clause.includes('魔法')?'magic':'physical',power=(clause.includes('極大')?2.4:clause.includes('大')?1.8:clause.includes('中')?1.3:.8)/(clause.includes('分けて')?count:1),old=state.battle.weaponAttackContext;
   const elements=[...clause.matchAll(/([火水雷風地光闇無])属性/g)].map(m=>m[1]),hits=Math.max(count,elements.length),hitPower=count===1&&elements.length>1?power/elements.length:power;
   state.battle.weaponAttackContext={normal:false,element,figurePenetrationV218: +(text.match(/ダメージ軽減を(\d+)%無視/)?.[1]||0)/100};try{for(let i=0;i<hits;i++)for(const t of targets.filter(t=>enemies.includes(t)&&t.hp>0)){state.battle.weaponAttackContext.element=elements.length?elements[i%elements.length]:element;const stamp=document.createElement('img');stamp.className='soul-stamp-v218';stamp.src=f.image;positionEffect(stamp,`enemy:${t.uid}`);$('#battleFxLayer').append(stamp);try{await fixedDelay(160);dealt+=applyEnemyDamageTo(a,t,hitPower,type,+(text.match(/会心率(\d+)%/)?.[1]||0)/100).value||0;fx('magic',`enemy:${t.uid}`);}finally{setTimeout(()=>stamp.remove(),450);}}}finally{state.battle.weaponAttackContext=old;}
  }
  const up=/(アップ|上昇|増加)/.test(clause),down=/(ダウン|低下|減少)/.test(clause);
  if(up||down){const match=clause.match(/((?:(?:HP|MP|LIFE|ATK|DEF|MAG|MND|SPD)(?:と|・|、)?)+)(?:を|が|の)?(?:\d+ターンの間)?\s*(\d+(?:\.\d+)?)%/);if(match){const v=+match[2]/100*(down?-1:1);for(const code of match[1].match(/HP|MP|LIFE|ATK|DEF|MAG|MND|SPD/g)||[])for(const t of targets){const key=soulStatV218[code];if(piece){if(!['maxHp','atk','def','spd'].includes(key))continue;if(key==='maxHp'){if(down)t.hp=Math.max(0,t.hp-Math.round(t.maxHp*-v));else{const old=t.maxHp;t.maxHp=Math.max(1,Math.round(t.maxHp*(1+v)));t.hp=Math.max(0,Math.round(t.hp/old*t.maxHp));}}else t[key]=Math.max(1,Math.round(t[key]*(1+v)));}else soulBuffV218(t,key,v,turns);}}
   if(!piece){const extras={回避率:'evade',会心率:'crit',命中率:'accuracy',ダメージ軽減:'damageCut',物理ダメージ軽減:'physicalCut',魔法ダメージ軽減:'magicCut',魔法与ダメージ:'magicDamage',物理与ダメージ:'physicalDamage',全属性耐性:'resist:all',状態異常耐性:'status:all'};for(const [label,key]of Object.entries(extras)){const m=clause.match(new RegExp('(?:^|の|と|、|間)'+label+'を?(?:\\d+ターンの間)?(\\d+)%'));if(m)for(const t of targets)soulBuffV218(t,key,+m[1]/100*(down?-1:1),turns);}for(const m of clause.matchAll(/([火水雷風地光闇無])属性(耐性|与ダメージ|ダメージ軽減)を?(?:\d+ターンの間)?(\d+)%/g))for(const t of targets)soulBuffV218(t,(m[2]==='与ダメージ'?'damage:':'resist:')+m[1],+m[3]/100*(down?-1:1),turns);
    for(const [label,key]of Object.entries(soulStatusV218)){const m=clause.match(new RegExp(label+'耐性を?(?:\\d+ターンの間)?(\\d+)%'));if(m)for(const t of targets)soulBuffV218(t,'status:'+key,+m[1]/100,turns);}
    // A shared value applies to every named field (SPD and critical, DEF and cut).
    const mixed=clause.match(/((?:ATK|DEF|MAG|MND|SPD)(?:と(?:回避率|会心率|命中率|ダメージ軽減)))を(?:\d+ターンの間)?(\d+)%/);if(mixed){const stat=mixed[1].match(/ATK|DEF|MAG|MND|SPD/)[0];for(const t of targets)soulBuffV218(t,soulStatV218[stat],+mixed[2]/100*(down?-1:1),turns);}
   }
  }
  if(!piece){for(const m of clause.matchAll(/(HP|MP)(?:を|が)?(\d+)(%)?(?:回復|・)/g))for(const t of targets){const amount=+m[2]*(m[3]?(m[1]==='HP'?t.maxHp:t.maxMp)/100:1);if(m[1]==='HP')heal(t,amount);else t.mpNow=Math.min(t.maxMp,t.mpNow+amount);fx('buff',t.id);}
   if(/HPが最も低い味方を(\d+)%回復/.test(clause))for(const t of targets)heal(t,t.maxHp*+clause.match(/(\d+)%/)[1]/100);
   if(/解除/.test(clause))for(const t of targets){if(clause.includes('状態異常')){const keys=Object.keys(t.status).filter(k=>t.status[k]>0);for(const key of clause.includes('1つ')?keys.slice(0,1):keys)t.status[key]=0;}else for(const [name,key]of Object.entries(soulStatusV218))if(clause.includes(name))t.status[key]=0;}
   if(/状態に|ひるませ|毒にする|混乱にする|マヒにする|やけどにする|ひるみにする|付与/.test(clause)){const chance=+(clause.match(/(\d+)%/)?.[1]||100)/100;let statuses=Object.entries(soulStatusV218).filter(([name,key])=>clause.includes(name)||key==='stun'&&clause.includes('ひるま'));if(/または|どちらか/.test(clause)&&statuses.length)statuses=[pick(statuses)];for(const [,key]of statuses)for(const t of targets.filter(t=>enemies.includes(t)))applyEnemyStatusTo(t,key,chance,3);}
   if(/MP消費.*軽減/.test(clause))for(const t of targets)soulBuffV218(t,'mpCut',+(clause.match(/(\d+)%/)?.[1]||0)/100,turns);
   if(/HP30%以下/.test(clause)){const low=own.filter(t=>t.hp/t.maxHp<=.3);if(clause.includes('追加で15%回復'))for(const t of low)heal(t,t.maxHp*.15);if(clause.includes('SPD上昇量が35%'))for(const t of low)soulBuffV218(t,'spd',.10,turns);}
   if(/CT.*(?:短縮|減ら)/.test(clause)){const n=+(clause.match(/(\d+)ターン/)?.[1]||1);for(const t of targets)if(t.ultCooldowns)t.ultCooldowns=t.ultCooldowns.map(v=>Math.max(0,v-n));}
   if(/獲得コイン|獲得経験値/.test(clause)){const v=+(clause.match(/(\d+)%/)?.[1]||0)/100;for(const t of own){t.figureEffects={...t.figureEffects};if(clause.includes('獲得コイン'))t.figureEffects.goldBonus=(t.figureEffects.goldBonus||0)+v;if(clause.includes('獲得経験値'))t.figureEffects.expBonus=(t.figureEffects.expBonus||0)+v;}}
  }
 }
 return dealt;
}
async function useFigureSoulV218(a,id){const b=state.battle,f=figureById(id);if(!b||b.busy||b.finished||activeAlly()!==a||!figureActiveV218(a,id))return false;if(figureSoulV218(a,id)<f.soul.cost){await narrationDialog(`${f.soul.name}\n${f.soul.text}\nSOUL ${figureSoulV218(a,id)} / ${f.soul.cost}`);return false;}
 b.busy=true;setCommandDisabled(true);try{if(await narrationDialog(`${f.soul.name}\n${f.soul.text}\n発動しますか？（ターン消費なし）`,[['発動','yes','primary'],['戻る','no']])!=='yes')return false;if(state.battle!==b||b.finished||a.dead)return false;a.figureSoulV218[id]=0;await soulCutinV218(f);await applySoulTextV218(f,a,livingField(),livingEnemies(),f.soul.text);if(!livingEnemies().length)await handleEnemyWaveClear();return true;}finally{if(state.battle===b&&!b.finished){b.busy=false;renderBattle();}}}
function pieceSoulCountV218(f,hand=[]){let n=new Set(f?.tags||[]).size;const counts={};for(const id of hand)for(const tag of figureById(id)?.tags||[])counts[tag]=(counts[tag]||0)+1;for(const [id,count]of Object.entries(counts)){if(count<2)continue;const row=CATALOG_V218.tags.find(t=>t.id===id),text=count>=3?row?.pieceThree:row?.pieceTwo;if(id==='23'&&!f.tags.includes('23'))continue;n+=+(text?.match(/SOUL獲得量\+(\d+)/)?.[1]||0);}return Math.min(10,n);}
function pieceSoulTierV218(f,hand=[]){const n=pieceSoulCountV218(f,hand);return n>=10?10:n>=5?5:1;}
const pieceAdjacencyBaseV218=animatePieceAdjacencyV174;
animatePieceAdjacencyV174=async function(pRows,cRows,b){await pieceAdjacencyBaseV218(pRows,cRows,b);const eligible=pRows.filter(r=>r.f?.soul&&r.f.pieceSoul?.[pieceSoulTierV218(r.f)]);let chosen=eligible.slice(0,2);
 if(eligible.length){const overlay=document.createElement('div');overlay.className='piece-soul-picker-v218';overlay.innerHTML=`<section><h2>SOULスキルを選択</h2><p>このターンに発動するフィギュアを最大2体選択</p>${eligible.map(r=>`<button data-choice="${r.index}" aria-pressed="false"><img src="${r.f.image}" alt=""><b>${r.f.soul.name} / SOUL ${pieceSoulCountV218(r.f,b.pHand)}</b><small>${r.f.pieceSoul[pieceSoulTierV218(r.f,b.pHand)].text}</small></button>`).join('')}<button data-confirm>選択したスキルを発動</button></section>`;document.body.append(overlay);chosen=[];await new Promise(resolve=>{$$('[data-choice]',overlay).forEach(btn=>btn.onclick=()=>{const row=eligible.find(r=>r.index===+btn.dataset.choice);if(chosen.includes(row))chosen=chosen.filter(r=>r!==row);else if(chosen.length<2)chosen.push(row);btn.setAttribute('aria-pressed',String(chosen.includes(row)));});$('[data-confirm]',overlay).onclick=resolve;});overlay.remove();}
 for(const [rows,enemies,selected,hand]of [[pRows,cRows,chosen,b.pHand],[cRows,pRows,cRows.filter(r=>r.f?.soul&&r.f.pieceSoul?.[pieceSoulTierV218(r.f,b.cHand)]).slice(0,2),b.cHand]])for(const r of selected){await soulCutinV218(r.f);const boost=pieceSoulBoostV218(hand),text=r.f.pieceSoul[pieceSoulTierV218(r.f,hand)].text.replace(/(\d+(?:\.\d+)?)%/g,(_,n)=>(+n*(1+boost)).toFixed(2)+'%');await applySoulTextV218(r.f,r,rows,enemies,text,true);}
 for(const r of [...pRows,...cRows])updateFighterHpV110(ensureMobPieceOverlayV96(),r);
 b.pLifeMax=pRows.reduce((n,r)=>n+r.maxHp,0);b.cLifeMax=cRows.reduce((n,r)=>n+r.maxHp,0);b.pLife=sumAliveHpV110(pRows);b.cLife=sumAliveHpV110(cRows);
};
function cpuFigureAvailableV218(f){return FIGURE_GACHAS_V96.some(b=>b.unlock()&&gachaPoolV96(b).some(x=>x.id===f.id));}
const rubyExchangeBaseV218=rubyExchangeFigureV115;rubyExchangeFigureV115=function(f){if(figureOwned(f.id)&&figurePlusV218(f.id)>=9)return{ok:false,msg:'すでに最大強化です'};const cost=figureRubyCostV115(f);if(rubyOwnedV115()<cost)return{ok:false,msg:'ルビーが足りません'};setRubyV115(rubyOwnedV115()-cost);awardGachaFigureV115(f);saveMeta();return{ok:true};};
