// UPDATE_V179_BEGIN
/* v179: three authored event quests, event figures/medals, and focused story-dialogue corrections. */
ADJACENCY_TAGS_V174['04']={name:'ぷにモブシリーズ',equipment:'DEF+5 & ダメージ軽減率+2% & 全属性耐性+20%',piece:'ATK+30%・DEF+30% / ぷにモブタグ全員の全ステータス+30%',stats:{atk:.30,def:.30},auraTag:'01',aura:.30};
ADJACENCY_TAGS_V174['05']={name:'とびっきりのスイーツ',equipment:'MAG+5 & 魔法ダメージ軽減率+3%',piece:'ATK+30%・DEF+30% / 美味しい食べ物タグ全員の全ステータス+20%',stats:{atk:.30,def:.30},auraTag:'18',aura:.20};
ADJACENCY_TAGS_V174['06']={name:'マグネットモンスターズ',equipment:'SPD+5 & ATK+5',piece:'ATK+30%・SPD+40% / ネオン街タグ全員の全ステータス+15%',stats:{atk:.30,spd:.40},auraTag:'44',aura:.15};
ADJACENCY_TAGS_V174['07']={name:'マグマの決戦',equipment:'ATK+5 & HP+15',piece:'ATK+30%・HP+10% / マグマタグ全員の全ステータス+15%',stats:{atk:.30,maxHp:.10},auraTag:'47',aura:.15};

const EVENT_FIGURES_V179=[
 {id:'event023',image:'eventfig/23.png',name:'モブフェニックス',rarity:'UR',statsText:'DEF +10 & HP +100',traitText:'回復量 +20% & やけど耐性+50%',tags:['03','08','09','25','30','32','36','39','47','50','53','56'],adjacencyTags:['07']},
 {id:'event024',image:'eventfig/24.png',name:'モブカスタード',rarity:'SSR',statsText:'DEF +5 & MND +5',traitText:'魔法ダメージ軽減+5%',tags:['04','27','29','33','36','37','53','59'],adjacencyTags:['05']},
 {id:'event025',image:'eventfig/25.png',name:'モブリスカスタード',rarity:'UR',statsText:'DEF +8 & MND +10',traitText:'魔法ダメージ軽減+10%',tags:['04','08','09','27','29','33','36','37','53','59'],adjacencyTags:['05']},
 {id:'event026',image:'eventfig/26.png',name:'モブマグネットM',rarity:'SSR',statsText:'SPD +5 & MND +5',traitText:'マヒ耐性+35%',tags:['04','08','09','39','44','49','51'],adjacencyTags:['06']},
 {id:'event027',image:'eventfig/27.png',name:'モブマグネットO',rarity:'SSR',statsText:'MAG +5 & MND +5',traitText:'雷属性会心率+5%',tags:['02','08','09','39','44','49','51'],adjacencyTags:['06']},
 {id:'event028',image:'eventfig/28.png',name:'モブマグネットB',rarity:'SSR',statsText:'ATK +5 & SPD +5',traitText:'雷属性物理与ダメージ+8%',tags:['03','08','09','39','44','49','51'],adjacencyTags:['06']},
 {id:'event029',image:'eventfig/29.png',name:'モブマグネットMOB',rarity:'UR',statsText:'DEF +8 & SPD +8',traitText:'雷属性与ダメージ+10%',tags:['03','08','09','39','44','51','53','59'],adjacencyTags:['06']}
];
for(const row of EVENT_FIGURES_V179){const old=figureByImageV96(row.image);if(old)Object.assign(old,{...row,id:old.id});else FIGURES.push({...row,eventExclusiveV163:true});}

const phoenixMedalV179={id:'event-phoenix-medal',name:'モブフェニックス',image:'spenemy/41.png',type:'メダル',types:['メダル'],rarity:'UR',attribute:'火',stats:{atk:30,maxHp:150,maxMp:250},traits:[{kind:'eventPhoenixDrainV179',chance:.30,value:.10,label:'30%で与ダメージの10% HP回復'}],traitLabel:'30%の確率で与えたダメージの10% HPを回復する'};
const custardMedalV179={id:'event-custard-medal',name:'モブカスタード',image:'spenemy/42.png',type:'メダル',types:['メダル'],rarity:'UR',attribute:'光',stats:{mag:50,res:50},traits:[{kind:'eventMagicCritV179',value:.04,label:'魔法会心率+4%'}],traitLabel:'魔法会心率+4%'};
for(const w of [phoenixMedalV179,custardMedalV179])if(!weaponById(w.id))WEAPONS.push(w);

const calcDamageBaseV179=calcDamage;
calcDamage=function(a,type,power,crit=0,e=targetEnemy()){
 let extra=0;if(type==='magic')extra+=weaponTraitSum(a,'eventMagicCritV179');
 const adjustedCrit=((e?.story179Kind==='custard'||e?.story179Kind==='riscustard')?(crit+extra)*.20:(crit+extra));const r=calcDamageBaseV179(a,type,power,adjustedCrit,e);
 if(r?.value>0&&!r.miss&&Math.random()<combinedTraitChance(a,'eventPhoenixDrainV179')){const rate=weaponTraitSum(a,'eventPhoenixDrainV179');if(rate>0){const h=heal(a,r.value*rate);if(h)notice(`${a.name} HP +${h}`,'heal',450);}}
 return r;
};

const STORY179={
 phoenix:{title:'復活！モブフェニックス！',world:'magma',unlock:'tribe',unlockName:'部族村',image:'spenemy/41.png',oneTime:true,diffs:[{name:'SPECIAL',level:'60～65',coins:0,diamonds:100,figures:[23],medal:'event-phoenix-medal'}]},
 custard:{title:'小さな戦士とカスタードゲーム',world:'neon',unlock:'magma',unlockName:'マグマ',image:'spenemy/43.png',diffs:[{name:'ノーマル',level:35,coins:5000,diamonds:10,figures:[24]},{name:'ハード',level:55,coins:10000,diamonds:30,figures:[],medal:'event-custard-medal'},{name:'インフェルノ',level:90,coins:50000,diamonds:50,figures:[25]}]},
 magnet:{title:'マグネットカーニバル！',world:'neon',unlock:'rural2',unlockName:'田舎町Ⅱ',image:'spenemy/47.png',diffs:[{name:'ノーマル',level:60,coins:5000,diamonds:10,figures:[26]},{name:'ハード',level:75,coins:10000,diamonds:30,figures:[27,28]},{name:'インフェルノ',level:90,coins:50000,diamonds:50,figures:[29]}]}
};
function recordsV179(key){state.meta.storyEventsV179??={};return state.meta.storyEventsV179[key]??={};}
function openV179(key,d=0){const q=STORY179[key],r=recordsV179(key),test=testAllQuestsV171();if(!q||!q.diffs[d])return false;if(!worldCleared(q.unlock)&&!test)return false;if(q.oneTime)return !r.clear||test;if(d>0&&!r[d-1]&&!test)return false;return !r[d]||test;}
function seenV179(key){const r=recordsV179(key);return !!(r.clear||Object.values(r).some(Boolean)||state.meta.storyEventSeenV175?.[key]);}
function baseByNameV179(name){return trainingEnemyCatalog().find(x=>x.name===name)||null;}
function customTemplateV179(key,d=0){
 const lv=(arr)=>arr[Math.min(d,arr.length-1)], base=(name)=>({...baseByNameV179(name)}), common={story179Kind:key,noEscape:true};
 const map={
  phoenixMag:{...base('モブマグトカゲ'),name:'モブマグトカゲ',category:'elite',attribute:'火',levelMin:60,levelMax:60,damageReduction:.10,evasion:.15,actionCount:1,forceActionCount:true,v144ActionMin:1,v144ActionMax:2},
  phoenixRock:{...base('モブヒートロック'),name:'モブヒートロック',category:'elite',attribute:'火',levelMin:60,levelMax:60,damageReduction:.10,actionCount:1,forceActionCount:true,v144ActionMin:1,v144ActionMax:2},
  phoenixFlame:{...base('モブフレイム'),name:'モブフレイム',category:'elite',attribute:'火',levelMin:65,levelMax:65,damageReduction:.10,evasion:.10,actionCount:1,forceActionCount:true,v144ActionMin:1,v144ActionMax:2},
  phoenix:{id:'v179-phoenix',name:'モブフェニックス',image:'spenemy/41.png',category:'boss',attribute:'火',levelMin:68,levelMax:68,damageReduction:.12,evasion:.05,actionCount:2,forceActionCount:true,v144ActionMin:2,v144ActionMax:3},
  custard:{id:'v179-custard',name:'モブカスタード',image:'spenemy/42.png',category:'boss',attribute:'光',levelMin:lv([39,62,93]),levelMax:lv([39,62,93]),damageReduction:.10,actionCount:2,forceActionCount:true,v144ActionMin:2,v144ActionMax:3},
  riscustard:{id:'v179-riscustard',name:'モブリスカスタード',image:'spenemy/43.png',category:'boss',attribute:'光',levelMin:lv([45,65,95]),levelMax:lv([45,65,95]),damageReduction:.10,actionCount:2,forceActionCount:true,v144ActionMin:2,v144ActionMax:3},
  magM:{id:'v179-magM',name:'モブマグネットM',image:'spenemy/44.png',category:'elite',attribute:'雷',levelMin:lv([65,80,95]),levelMax:lv([65,80,95]),damageReduction:.11,evasion:.04,actionCount:2,forceActionCount:true,v144ActionMin:2,v144ActionMax:2},
  magO:{id:'v179-magO',name:'モブマグネットO',image:'spenemy/45.png',category:'elite',attribute:'雷',levelMin:lv([65,80,95]),levelMax:lv([65,80,95]),damageReduction:.11,evasion:.04,actionCount:2,forceActionCount:true,v144ActionMin:2,v144ActionMax:2},
  magB:{id:'v179-magB',name:'モブマグネットB',image:'spenemy/46.png',category:'elite',attribute:'雷',levelMin:lv([65,80,95]),levelMax:lv([65,80,95]),damageReduction:.11,evasion:.04,actionCount:2,forceActionCount:true,v144ActionMin:2,v144ActionMax:2},
  magMOB:{id:'v179-magMOB',name:'モブマグネットMOB',image:'spenemy/47.png',category:'boss',attribute:'雷',levelMin:lv([70,85,99]),levelMax:lv([70,85,99]),damageReduction:.15,evasion:.04,actionCount:2,forceActionCount:true,v144ActionMin:2,v144ActionMax:3}
 };
 return {...(map[key]||{}),...common,id:(map[key]?.id||`v179-${key}`),permanentDamageReduction:true};
}
const actorBaseV179=storyActorInfo;
storyActorInfo=function(key){if(String(key).startsWith('v179-')){const k=String(key).slice(5),t=customTemplateV179(k,eventRunV174?.difficulty||0);return {...t,enemyTemplate:t};}return actorBaseV179(key);};

function nagaV179(d,qty=2){const t={...baseByNameV179('モブナーガ'),category:'elite',story179Kind:'naga',levelMin:[35,55,90][d],levelMax:[35,55,90][d],damageReduction:.10,evasion:.10,actionCount:2,forceActionCount:true,v144ActionMin:2,v144ActionMax:2,noEscape:true};return Array.from({length:qty},()=>({template:t,level:t.levelMin}));}
function trainerV179(d){const t={...baseByNameV179('モブスラトレーナー'),story179Kind:'trainer',levelMin:[58,73,88][d],levelMax:[58,73,88][d],actionCount:1,forceActionCount:true,v144ActionMin:1,v144ActionMax:2,noEscape:true};return {template:t,level:t.levelMin};}
function waveV179(key,area,d){if(key==='phoenix'){const ks=['phoenixMag','phoenixRock','phoenixFlame','phoenix'];const t=customTemplateV179(ks[area],d);return area<3?Array.from({length:3},()=>({template:t,level:t.levelMin})):[{template:t,level:t.levelMin}];}
 if(key==='custard'){if(area===0)return nagaV179(d,2);if(area===2||area===3){const t=customTemplateV179(area===2?'custard':'riscustard',d);return[{template:t,level:t.levelMin}];}return nagaV179(d,eventRunV174?.quizWrongCountV179||1);}
 const center=customTemplateV179(['magM','magO','magB','magMOB'][area],d);return area<3?[trainerV179(d),{template:center,level:center.levelMin},trainerV179(d)]:[{template:center,level:center.levelMin}];}

const PRE_V179={
 phoenix:[
 [['say','pink','本当であります～！！'],['say','denden','オイラも見たでやんす～！！'],['say','desert','本当か？'],['say','nyoro','本当に、\nモブフェニックス様ニョロ！？'],['say','pink','僕はあれから\nお城の書物で見たであります！\n同じ姿でありました！'],['say','denden','オイラはもともと\n知っているでやんす！\n間違いないでやんす！'],['say','money','とにかく、探しましょう！\n魔王軍のことが聞けるかも！']],
 [['say','pink','もし復活しているなら\n絶対に仲間にするであります！'],['say','denden','100人力でやんす！'],['say','tetsu','拙者、見たことはないでござるが\n不死鳥伝説\nオトナシの国にも伝わっているでござる'],['say','jessie','もはや神話のモンスターだもの'],['say','nyoro','ニョロ～・・\n会いたいニョロ！'],['say','money','一気に片付けましょう！']],
 [['say','nekoku','モブフェニックスは\n国王様とも仲がいいぞ'],['say','jessie','海底とマグマは\n確か交流が多いのよね'],['say','nekoku','そうだぞ\nオラもここに来た'],['say','money','色々繋がってるのね～'],['say','desert','モブドラゴンは確かに強い\nだが、敗れた本当の理由が知りたい'],['say','pink','本人に直接聞いてみましょう！\nきっと復活しているであります！'],['say','jessie','もうすぐのはずだから\n急ぎましょう！']],
 [['guest','v179-phoenix'],['say','nyoro','モブフェニックス様！！'],['say','v179-phoenix','モブニョロか・・\n久しいな'],['say','nyoro','会いたかったニョロ！'],['say','v179-phoenix','心配をかけたな'],['say','money','ちょ、ちょっと！\nおかしくない？'],['say','pink','何がでありますか？'],['say','money','こいつ\n相当強いわよ！\nどうやって負けたの？'],['say','nyoro','だから、モブドラゴンに、、'],['say','desert','いや\nそんなレベルじゃない'],['say','tetsu','なんという威圧感・・！'],['say','nyoro','そうなのかニョロ？'],['say','v179-phoenix','素晴らしい心を持っているな\nお前たち、魔王を狙っているのか？'],['say','denden','そうでやんす！\n力を貸してほしいでやんす！'],['say','v179-phoenix','それは不可能だ\n私は一度敗れた\n復活はしたが、ここを離れられないのだ'],['say','desert','何があった？\n教えてくれないか？'],['say','nyoro','あれは、モブドラゴンじゃ\nないニョロか？'],['say','v179-phoenix','ああ、違う\nやつはモブフォーム\nモブドラゴンに化けておった'],['say','money','化ける！？\n魔王軍にそんなやつが・・'],['say','nyoro','怖いニョロ・・'],['say','v179-phoenix','やつは魔王軍ではない\n何かを見返りに\n援軍としてマグマへ来たのだ'],['say','pink','魔王軍じゃないにしても\n放ってはおけないであります！！'],['say','nekoku','早く探した方がいいぞ'],['say','v179-phoenix','今のお前たちでは無理だ'],['say','desert','だが、進むしかない'],['say','v179-phoenix','そうだな\nでは、私が鍛えてやる'],['say','nyoro','ニョロ～！\nお願いしますニョロ！'],['say','tetsu','願ってもないでござる！！'],['say','v179-phoenix','悪いが力は惜しまぬぞ']]
 ],
 custard:[
 [['say','pink','ネオン街、到着！'],['say','money','であります～'],['say','pink','先に言わないでください！！'],['say','denden','到着でやんす！'],['say','nyoro','キレイな街ニョロ～\n僕、キラキラ好きニョロ～！'],['guest','v179-custard'],['say','v179-custard','ねえねえ、\nそこのおチビちゃんたち'],['say','denden','敵襲でやんす！'],['say','money','あいつチビって言った！！'],['say','v179-custard','まあ落ち着いてよ\n私とゲームをしない？\n勝ったらいいものあげるよ'],['say','nyoro','いいものニョロ～？'],['say','pink','・・ん？\nあなた酒場の・・'],['say','v179-custard','それ人違い'],['say','denden','いいものは\n欲しいでやんす！'],['say','money','どう考えても怪しいでしょ！'],['say','v179-custard','それはお互い様でしょう\nやるの？やらないの？'],['say','denden','受けて立つでやんす！！'],['say','v179-custard','いいね～\nまずは、次のエリアまで来てね']],
 [],
 [['guest','v179-custard'],['say','v179-custard','おー\n来たね～'],['say','denden','次の勝負でやんす！'],['say','v179-custard','う～ん\nそうだな～'],['say','money','早くしなさいよ！'],['say','v179-custard','よし\n戦闘開始～'],['say','nyoro','ニョロ！？']],
 [['guest','v179-custard'],['say','denden','さあ！最後はなんでやんすか！'],['say','pink','勝負であります！'],['say','v179-custard','そうだね～\nやっぱり\nさっきのお返しかな？'],['guest','v179-riscustard'],['say','money','ちょっと！\n可愛いのは卑怯よ！'],['say','v179-riscustard','さあ～\nやっちゃうよ～']]
 ],
 magnet:[
 [['say','jessie','なんだか\n身体が変な感じね'],['say','denden','う、動きづらいでやんす'],['guest','v179-magM'],['say','desert','こいつの仕業か？'],['say','nekoku','マグネットモンスターだぞ'],['say','nyoro','頭痛いニョロ～・・'],['say','money','やっつけましょう！']],
 [['say','desert','他にも仲間がいるのだろう'],['say','jessie','この辺りから\n強い磁力を感じるわ'],['guest','v179-magO'],['say','nyoro','引っ張られるニョロ～！'],['say','nekoku','ふんばるんだぞ！']],
 [['guest','v179-magB'],['say','money','こいつで最後ね！'],['say','desert','さっさと片付けるぞ'],['say','nyoro','頑張るニョロ！']],
 [['guests',['v179-magM','v179-magO','v179-magB']],['say','denden','しぶといでやんす！'],['say','money','ここからが本番\nってわけね！'],['say','tetsu','いざ！'],['narrate','磁力が激しくぶつかり合い、3体が中央へ集まった！'],['guest','v179-magMOB'],['say','denden','合体した！！\n・・・でやんす？'],['say','money','明らかに失敗ね'],['say','tetsu','不憫でござる'],['say','pink','よーし！\nやっつけるであります！'],['say','jessie','ピンクちゃん・・']]
 ]
};
const POST_V179={
 phoenix:[[ ['say','nyoro','急ぐニョロ～！'] ],[['say','tetsu','さあ進むでござる！']],[['say','pink','レッツゴ～！\nであります！']],[['guest','v179-phoenix'],['say','v179-phoenix','見事だ\n旅を続け、力をつけよ'],['say','nyoro','はいニョロ！'],['say','denden','やってやるでやんす～！！']]],
 custard:[[ ['say','money','あんたの方が\nビリビリだったわね'],['say','denden','オイラ、ビリビリでやんす！'] ],[],[['guest','v179-custard'],['say','money','あんた中々やるわね'],['say','pink','モブメープルも\nこんなに強いでありますか？'],['say','v179-custard','う～ん\n負けちゃった'],['say','denden','もう終わりでやんすか？'],['say','v179-custard','次で最後かな'],['say','nyoro','もっと楽しいゲームがいいニョロ・・']],[['guest','v179-custard'],['say','pink','勝ったであります～！'],['say','denden','やったでやんす～！！'],['say','money','あんた、仲間にならない？'],['say','nyoro','それはいいニョロ～！'],['say','v179-custard','嬉しいね\nでもやめとく\nまた遊んでね'],['say','pink','次は、フィギュアでバトル！\nであります！'],['say','v179-custard','私、強いよ～'],['say','money','でしょうね\n対戦が楽しみだわ！']]],
 magnet:[[ ['say','money','ねえ、\nこれって、、'],['say','denden','さっきより\n動きづらいでやんす、、'],['say','tetsu','不穏でござるな'] ],[['say','pink','おーー\nなんでありますかー！'],['say','denden','引っ張られるでやんすー！'],['say','nyoro','傘がー！'],['say','tetsu','足に集中するでござる！！']],[['say','tetsu','落ち着いたでござるな'],['say','pink','でも\n変な音がするであります'],['say','jessie','確かめに行きましょう！']],[['say','tetsu','勝利でござる！'],['say','money','もう嫌よ・・'],['say','denden','オイラも\n合体してみたいでやんす'],['say','nyoro','まだまだ\n知らないモンスターが\nいっぱいいるニョロ！']]]
};

async function sceneV179(phase){const r=eventRunV174,q=STORY179[r.storyV179];if(!r||!q)return;showScreen('adventure');storyBusy=true;try{const extras=r.storyV179==='custard'?['pink','money','denden','nyoro']:['pink','denden','money','desert','nyoro','tetsu','jessie','nekoku'];await openStoryScene(q.world,r.area,'default',extras);$('#adventureStageTitle').textContent=q.title;$('#adventureProgress').textContent=`AREA ${r.area+1}${q.oneTime?'':` / ${q.diffs[r.difficulty].name}`}`;const steps=(phase==='pre'?PRE_V179:POST_V179)[r.storyV179]?.[r.area]||[];if(steps.length)await runStorySteps(steps);}finally{await closeStoryScene(false);storyBusy=false;}}
async function quizV179(){const r=eventRunV174;showScreen('adventure');storyBusy=true;let ans='';try{await openStoryScene('neon',1,'default',['pink','money','denden','nyoro']);await storyShowGuest('v179-custard');await storySay('v179-custard','来たね\nじゃあ第一ゲーム\n私のクイズに答えてね');await storySay('v179-custard','私はどら焼きが好きなの\n一日に何個食べるでしょう？');ans=await narrationDialog('一日に何個食べる？',[['A. 3コ','A','primary'],['B. 4コ','B'],['C. 5コ','C'],['D. 6コ','D']],'カスタードゲーム');await storySay('pink',`${ans||'A'}であります！`);if(ans==='A'){await storyNarrate('正解！');await storySay('v179-custard','正解！\nやるね～\n次のエリアで待ってるよ～');}else{await storyNarrate('不正解！');await storySay('v179-custard','そんなに食べられないよ～\n正解はAでした～\n間違えたから\nその分戦ってね');r.quizWrongCountV179={B:1,C:2,D:3}[ans]||1;}}finally{await closeStoryScene(false);storyBusy=false;}return ans==='A';}

function partyV179(key){if(key!=='custard')return state.party;const ids=new Set(['pink','money','denden','nyoro']);return state.party.filter(([id])=>ids.has(canonicalPlayerId(id)));}
async function confirmStoryChallengeV179(title,diff=''){const answer=await dialog(`${title}${diff?' '+diff:''}\n挑戦しますか？`,[['はい','yes','primary'],['いいえ','no']],'モブコーチ','play/003.png');return answer==='yes';}
async function startV179(key,d=0){if(eventRunV174||!openV179(key,d))return false;const party=partyV179(key);if(key==='custard'&&party.length<1)return toast('出撃可能キャラクターがいません');const q=STORY179[key],diff=q.oneTime?'':q.diffs[d]?.name||'';if(!await confirmStoryChallengeV179(q.title,diff))return false;eventRunV174={storyV179:key,difficulty:d,area:0,vitals:{},rewarded:false};skipScopeV174='';skippedV174=false;$('#trainingFeaturePopup').hidden=true;await startSavannaAreaV174();return true;}
const startSavannaConfirmBaseV179=startSavannaV174;
startSavannaV174=async function(d){if(eventRunV174||!savannaOpenV174(d))return false;if(!await confirmStoryChallengeV179('サバンナスピードキング',SAVANNA_DIFFICULTIES_V174[d]?.name||''))return false;return startSavannaConfirmBaseV179(d);};
const startHotConfirmBaseV179=startHotV177;
startHotV177=async function(d){if(eventRunV174||!hotOpenV177(d))return false;if(!await confirmStoryChallengeV179('熱血スライム',HOT_DIFFICULTIES_V177[d]?.name||''))return false;return startHotConfirmBaseV179(d);};
const startAreaBaseV179=startSavannaAreaV174;
startSavannaAreaV174=async function(){const r=eventRunV174;if(!r?.storyV179)return startAreaBaseV179();const q=STORY179[r.storyV179];eventOverlayV163().hidden=true;
 if(r.storyV179==='custard'&&r.area===1){const correct=await quizV179();if(correct){showResultV179(true,null,true);return;}}
 else await sceneV179('pre');
 const bg=storySceneBg(q.world,r.area),config={mode:'eventStory174',storyEventV174:true,storyV179:r.storyV179,worldId:q.world,returnScreen:'training',party:partyV179(r.storyV179),questVitals:r.vitals,enemyConfigs:waveV179(r.storyV179,r.area,r.difficulty),bg:bg.bg,fallbackBg:bg.fallback};await startBattleLoaded(config);const b=state.battle;if(!b)return;
 if(r.storyV179==='magnet'){for(const a of b.allies){a.spd=Math.max(1,Math.floor(a.spd*.5));a.figureEffects={...(a.figureEffects||{}),evade:0,aoeEvade:0};a.noEvadeV179=true;}renderBattle();notice('磁力の影響：回避率0 / SPD半減','danger',1200);}
 $('#battleModeLabel').textContent=`${q.title} / ${q.oneTime?'SPECIAL':q.diffs[r.difficulty].name} / AREA ${r.area+1}`;$('#battleBackBtn').style.display='';};

function rewardV179(){const r=eventRunV174,q=STORY179[r.storyV179],rec=recordsV179(r.storyV179);if(!r||r.rewarded)return null;if(q.oneTime&&rec.clear&&!testAllQuestsV171())return null;if(!q.oneTime&&rec[r.difficulty]&&!testAllQuestsV171())return null;const d=q.diffs[r.difficulty];r.rewarded=true;if(q.oneTime)rec.clear=true;else rec[r.difficulty]=true;state.coins+=d.coins;state.meta.coins=state.coins;state.meta.diamonds=(Number(state.meta.diamonds)||0)+d.diamonds;const awarded=d.figures.map(n=>awardGachaFigureV115(figureByImageV96(`eventfig/${n}.png`)));if(d.medal){addMedal(d.medal,1);const w=weaponById(d.medal);awarded.push({f:{name:`${w.name} メダル`,image:w.image},converted:false});}saveMeta();return {...d,awarded};}
function showResultV179(win,reward=null,noBattle=false){const r=eventRunV174,q=STORY179[r.storyV179],ov=eventOverlayV163(),isLast=r.area===3;ov.innerHTML=`<div class="event-result-v163"><small>${q.title}</small><h2>${win?(reward?'QUEST CLEAR!!':'AREA CLEAR!'):'DEFEAT'}</h2><p>${q.oneTime?'SPECIAL':q.diffs[r.difficulty].name} / AREA ${r.area+1}</p>${win?'<span class="event-clear-stamp-v163">CLEAR</span>':'<p>パーティーを整えて再挑戦しましょう。</p>'}${reward?`<h3>クリア報酬</h3><p>コイン +${reward.coins.toLocaleString()} / ◆ +${reward.diamonds}</p><div class="event-rewards-v174">${reward.awarded.map(x=>`<div>${figureImageTagV101(x.f)}<b>${x.f.name}</b><small>${x.converted?'ルビー +'+x.ruby:'GET!'}</small></div>`).join('')}</div>`:''}<button class="primary-btn" data-v179-next>${win&&!isLast?'次のAreaへ':'クエストへ戻る'}</button></div>`;ov.hidden=false;bindImages(ov);$('[data-v179-next]',ov).onclick=async function(){this.disabled=true;if(win&&!isLast){r.area++;await startSavannaAreaV174();}else returnSavannaV174();};if(noBattle)showScreen('battle');}
const finishBaseV179=finishSavannaV174;
finishSavannaV174=async function(b,win){const r=eventRunV174;if(!r?.storyV179)return finishBaseV179(b,win);if(b.finished)return;b.finished=true;b.auto=false;setCommandDisabled(true);let reward=null;if(win){for(const a of b.allies)r.vitals[a.id]={hp:a.hp,mp:a.mpNow,dead:a.dead,status:{...a.status}};applyProgressRewards(b,r.vitals);await sceneV179('post');if(r.area===3)reward=rewardV179();}showResultV179(win,reward);};

let selectedStoryV179=null;
const renderStoryBaseV179=renderEventQuestsV163;
renderEventQuestsV163=function(){renderStoryBaseV179();if(eventViewV163!=='story')return;const root=$('#trainingFeaturePanel'),panel=$('.event-panel-v163',root),header=$('header',panel);if(!panel)return;[...panel.children].filter(el=>el!==header).forEach(el=>el.remove());const body=document.createElement('div');
 const all=[['savanna','サバンナスピードキング','spenemy/38.png','田舎町',worldCleared('rural')],['hot','熱血スライム','spenemy/40.png','ネオン街',worldCleared('neon')],['phoenix',STORY179.phoenix.title,STORY179.phoenix.image,STORY179.phoenix.unlockName,worldCleared(STORY179.phoenix.unlock)],['custard',STORY179.custard.title,STORY179.custard.image,STORY179.custard.unlockName,worldCleared(STORY179.custard.unlock)],['magnet',STORY179.magnet.title,STORY179.magnet.image,STORY179.magnet.unlockName,worldCleared(STORY179.magnet.unlock)]];
 if(selectedStoryV179===null){body.className='event-story-list-v177';body.innerHTML=all.map(([id,name,img,unlockName,unlocked])=>{const seen=id==='savanna'?Object.values(savannaRecordsV174()).some(Boolean):id==='hot'?Object.values(hotRecordsV177()).some(Boolean):seenV179(id);return`<button class="event-story-card-v174" data-story179="${id}"><small>STORY / 全4 AREA</small><strong>${name}</strong><img src="${img}" class="${seen?'':'event-silhouette-v175'}" alt="イベントボス"><small>${unlocked||testAllQuestsV171()?'挑戦する':unlockName+'クリア後に解放'}</small></button>`;}).join('');}
 else if(selectedStoryV179==='savanna'){body.innerHTML=`<div class="event-story-card-v174"><small>STORY 01 / 全4 AREA</small><strong>サバンナスピードキング</strong><img src="spenemy/38.png" alt="イベントボス"></div><div class="event-difficulties-v163">${SAVANNA_DIFFICULTIES_V174.map((d,i)=>`<button class="event-difficulty-v163" data-sav179="${i}" ${savannaOpenV174(i)?'':'disabled'}><div><b>${d.name}</b><strong>適正 Lv.${d.level}</strong></div><div class="event-story-rewards-v174">コイン ${d.coins.toLocaleString()} / ◆ ${d.diamonds}<br>${d.figures.map(n=>`<img src="eventfig/${n}.png" class="${savannaRecordsV174()[i]?'':'event-silhouette-v175'}" alt="限定報酬">`).join('')}</div>${savannaRecordsV174()[i]?'<em class="event-clear-stamp-v163">CLEAR</em>':''}</button>`).join('')}</div>`;}
 else if(selectedStoryV179==='hot'){body.innerHTML=`<div class="event-story-card-v174"><small>STORY 02 / 全4 AREA</small><strong>熱血スライム</strong><img src="spenemy/40.png" alt="イベントボス"></div><div class="event-difficulties-v163">${HOT_DIFFICULTIES_V177.map((d,i)=>`<button class="event-difficulty-v163" data-hot179="${i}" ${hotOpenV177(i)?'':'disabled'}><div><b>${d.name}</b><strong>適正 Lv.${d.level}</strong></div><div class="event-story-rewards-v174">コイン ${d.coins.toLocaleString()} / ◆ ${d.diamonds}<br>${(d.medal?['spenemy/39.png']:d.figures.map(n=>'eventfig/'+n+'.png')).map(img=>`<img src="${img}" class="${hotRecordsV177()[i]?'':'event-silhouette-v175'}" alt="限定報酬">`).join('')}</div>${hotRecordsV177()[i]?'<em class="event-clear-stamp-v163">CLEAR</em>':''}</button>`).join('')}</div>`;}
 else{const q=STORY179[selectedStoryV179],rec=recordsV179(selectedStoryV179),desc=selectedStoryV179==='phoenix'?'水属性以外に強い耐性を持っている':selectedStoryV179==='magnet'?'このクエストはパーティー全員の回避率0、SPD半減':'出撃可能：モブピンク / モブマニー / モブデンデン / モブニョロ';body.innerHTML=`<div class="event-story-card-v174"><small>STORY / 全4 AREA</small><strong>${q.title}</strong><img src="${q.image}" class="${seenV179(selectedStoryV179)?'':'event-silhouette-v175'}" alt="イベントボス"><small>${desc}</small></div><div class="event-difficulties-v163">${q.diffs.map((d,i)=>{const cleared=q.oneTime?rec.clear:rec[i];return`<button class="event-difficulty-v163" data-v179-start="${selectedStoryV179}:${i}" ${openV179(selectedStoryV179,i)?'':'disabled'}><div><b>${d.name}</b><strong>適正 Lv.${d.level}</strong></div><div class="event-story-rewards-v174">${d.coins?`コイン ${d.coins.toLocaleString()} / `:''}◆ ${d.diamonds}<br>${d.figures.map(n=>`<img src="eventfig/${n}.png" class="${cleared?'':'event-silhouette-v175'}" alt="限定報酬">`).join('')}${d.medal?`<img src="${weaponById(d.medal)?.image||''}" class="${cleared?'':'event-silhouette-v175'}" alt="限定メダル">`:''}</div>${cleared?'<em class="event-clear-stamp-v163">CLEAR</em>':!worldCleared(q.unlock)&&!testAllQuestsV171()?`<p>${q.unlockName}クリアで解放</p>`:i&&!openV179(selectedStoryV179,i)?'<p>前の難易度クリアで解放</p>':''}</button>`;}).join('')}</div>`;}
 panel.appendChild(body);$$('[data-story179]',body).forEach(x=>x.onclick=()=>{selectedStoryV179=x.dataset.story179;renderEventQuestsV163();});$$('[data-sav179]',body).forEach(x=>x.onclick=()=>startSavannaV174(Number(x.dataset.sav179)));$$('[data-hot179]',body).forEach(x=>x.onclick=()=>startHotV177(Number(x.dataset.hot179)));$$('[data-v179-start]',body).forEach(x=>x.onclick=()=>{const[k,d]=x.dataset.v179Start.split(':');startV179(k,Number(d));});$('[data-event-back]',panel).onclick=()=>{if(selectedStoryV179)selectedStoryV179=null;else eventViewV163='menu';renderEventQuestsV163();};bindImages(panel);
};

const weaponEvasionBaseV179=weaponEvasion;
weaponEvasion=function(a){if(state.battle?.config?.storyV179==='magnet')return 0;return weaponEvasionBaseV179(a);};

const hitBaseV179=applyEnemyDamageTo;
applyEnemyDamageTo=function(a,e,...args){if(!e?.story179Kind)return hitBaseV179(a,e,...args);const k=e.story179Kind,oldDr=e.damageReduction;let result;
 const type=args[1]||'physical',el=normalizeElement(attackElementFromContext(a,type));if((k==='custard'||k==='riscustard')&&type==='magic'&&!e.magicWarnV179){e.magicWarnV179=true;enemyPassiveNoticeV142(e,k==='riscustard'?'学習しないね～\n魔法は効かないの':'あ、いいの？\n魔法防御得意なんだよね～');}if(k==='phoenix'&&el!=='水')e.damageReduction=1-(1-oldDr)*.60;if((k==='custard'||k==='riscustard')&&type==='magic')e.damageReduction=k==='riscustard'?1:1-(1-oldDr)*.20;if(['magM','magO','magB','magMOB'].includes(k)&&type==='magic')e.damageReduction=1-(1-e.damageReduction)*.80;if((k==='magB'||k==='magMOB')&&Math.random()<.30)e.damageReduction=1-(1-e.damageReduction)*.70;if((k==='custard'||k==='riscustard')&&e.custardShieldUntilV179===state.battle?.turn)e.damageReduction=1-(1-e.damageReduction)*.80;
 try{result=hitBaseV179(a,e,...args);}finally{e.damageReduction=oldDr;}
 if(result?.value>0&&!result.miss&&e.hp>0){if((k==='custard'||k==='riscustard')&&Math.random()<.20){addAllElementResistV142(e,.05);queueEnemyCounterV142(e,a,1.30);notice(`${e.name}のカスタードゲーム！ 全属性耐性+5%・反撃！`,'danger',750);}if((k==='magM'||k==='magMOB')&&Math.random()<.10)queueEnemyCounterV142(e,a,1.20);if(k==='phoenix'&&!e.phoenixHalfV179&&e.hp/e.maxHp<=.50){e.phoenixHalfV179=true;e.hp=e.maxHp;e.atkBuff=Math.max(e.atkBuff||0,.10);e.atkBuffTurns=99;notice('モブフェニックス「面白い もっと力を見せてみろ！」 / HP全回復・ATK+10%','heal',1100);renderBattle();}if((k==='magO'||k==='magMOB')&&!e.magOLowV179&&e.hp/e.maxHp<=.50){e.magOLowV179=true;e.atkBuff=Math.max(e.atkBuff||0,.35);e.atkBuffTurns=99;e.spdBuff=Math.max(e.spdBuff||0,.35);e.spdBuffTurns=99;notice(`${e.name} ATK・SPD +35%`,'buff',850);}}
 return result;};

const actionBaseV179=enemyAction;
enemyAction=async function(action=1,uid){const b=state.battle,e=enemyByUid(uid)||actingEnemy()||b?.enemy,k=e?.story179Kind;if(!k)return actionBaseV179(action,uid);if(!b||b.finished||e.hp<=0)return;if(['phoenixMag','phoenixRock','phoenixFlame'].includes(k)){const oldCrit=enemyCriticalV163;enemyCriticalV163=Math.random()<.20;try{return await actionBaseV179(action,uid);}finally{enemyCriticalV163=oldCrit;}}for(const s of ['sleep','stun','paralyze'])if(e.status[s]>0){e.status[s]--;return;}const old=b.actingEnemyId;b.actingEnemyId=e.uid;try{
 if(k==='phoenix'){if(action===1&&e.phoenixHealTurnV179!==b.turn){e.phoenixHealTurnV179=b.turn;const h=Math.min(500,e.maxHp-e.hp);e.hp+=h;if(h){floatNumber(h,'heal',`enemy:${e.uid}`);renderBattle();}if(b.turn===3&&!e.phoenixTurn3V179){e.phoenixTurn3V179=true;e.atkBuff=Math.max(e.atkBuff||0,.30);e.magBuff=Math.max(e.magBuff||0,.30);e.atkBuffTurns=e.magBuffTurns=99;await actionCutin('モブフェニックス「そんなものか？ 様子見は終わりにしよう」 / 火属性与ダメージ+30%','danger',1000);}const t=pick(livingMain());if(t){await actionCutin('ゴッド・フェニックス','danger',600);await beginEnemyLunge(e.uid);let dealt=0;try{dealt+=await damageAlly(t,1.35,'physical',false,'火');for(const a of livingField())dealt+=await damageAlly(a,.45,'physical',isSuper(a),'火');}finally{endEnemyLunge();}const hh=Math.round(dealt*.10);if(hh){e.hp=Math.min(e.maxHp,e.hp+hh);floatNumber(hh,'heal',`enemy:${e.uid}`);renderBattle();}}return;}}
 if(k==='custard'||k==='riscustard'){const oldCrit=enemyCriticalV163;enemyCriticalV163=Math.random()<.10;try{if(k==='riscustard'&&action===1&&(!e.syrupNextV179||b.turn>=e.syrupNextV179)){e.syrupNextV179=b.turn+rint(3,5);e.custardShieldUntilV179=b.turn;const h=Math.min(rint(800,1200),e.maxHp-e.hp);e.hp+=h;renderBattle();await actionCutin(`スクイレル・シロップ / HP +${h}・このターン軽減80%`,'heal',850);return;}if(action===1){const t=pick(livingMain());if(t){await actionCutin('カスタード・クロス','danger',600);await beginEnemyLunge(e.uid);try{await damageAlly(t,1.10,'physical',false,'光');t.defDebuff=Math.max(t.defDebuff||0,.20);t.defDebuffTurns=Math.max(t.defDebuffTurns||0,rint(2,3));notice(`${t.name} DEF -20%`,'status',600);}finally{endEnemyLunge();}}return;}if(action===2){await actionCutin(`${e.name}の全体攻撃！`,'danger',520);await beginEnemyLunge(e.uid);try{await aoeHit(.85,'physical','光');}finally{endEnemyLunge();}return;}}finally{enemyCriticalV163=oldCrit;}}
 if(['magM','magO','magB','magMOB'].includes(k)){if(action===2){await actionCutin(`${e.name}の全体攻撃！`,'danger',520);await beginEnemyLunge(e.uid);try{await aoeHit(.85,'physical','雷');}finally{endEnemyLunge();}return;}if(action===1){const picks=k==='magMOB'?['magM','magO','magB']:[k],skill=pick(picks);if(skill==='magO'){await actionCutin('マグネットソードO','danger',550);await beginEnemyLunge(e.uid);try{await aoeHit(.90,'physical','雷');for(const a of livingField())if(Math.random()<.15)await inflictAllyStatus(a,'sleep',2);}finally{endEnemyLunge();}return;}const t=pick(livingMain());if(t){const isB=skill==='magB',name=isB?'マグネットソードB':'マグネットソードM',status=isB?'confuse':'stun',chance=.60;await actionCutin(name,'danger',550);await beginEnemyLunge(e.uid);try{await damageAlly(t,1.05,'physical',false,'雷');if(Math.random()<chance)await inflictAllyStatus(t,status,status==='stun'?1:2);}finally{endEnemyLunge();}}return;}}
 return actionBaseV179(action,uid);
 }finally{b.actingEnemyId=old;}};

const roundBaseV179=startRound;
startRound=async function(...args){const b=state.battle;if(b?.config?.storyV179==='magnet'&&eventRunV174?.area===3){if(b.turn===2&&!b.v179Turn2){b.v179Turn2=true;await allyStoryCutin('money','ちょっと！\nコイツ強くない！？',900);await allyStoryCutin('denden','カチカチでやんす！',900);}if(b.turn===4&&!b.v179Turn4){b.v179Turn4=true;await allyStoryCutin('desert','気を付けろ！\n全員の能力を使っている！',900);await allyStoryCutin('jessie','合体は成功ね・・！',900);}}return roundBaseV179(...args);};

window.__mobV179Runtime=true;
// UPDATE_V179_END
