// Shelf totals use the same aggregation and rounding as combat.
function normalizeShelfV221(){const counts={},old=state.meta.figureShelfV218||[],next=old.filter((id,index)=>{const rarity=figureById(id)?.rarity;if(!rarity||old.indexOf(id)!==index)return false;return(counts[rarity]=(counts[rarity]||0)+1)<=shelfLimitsV218[rarity];});if(next.length!==old.length){state.meta.figureShelfV218=next;saveMeta();}}
normalizeShelfV221();
const chooseBaseV221=openFigureChooseV220;
openFigureChooseV220=function(mode,...args){chooseBaseV221(mode,...args);if(mode!=='shelf')return;const ov=$('#figureChooseV220'),box=document.createElement('section'),raw=emptyFigureEffects();for(const id of state.meta.figureShelfV218||[])mergeFigureEffects(raw,rawFigureEffectsV218(id));const base=figureGroupEffectsV220;try{figureGroupEffectsV220=()=>scaleFigureEffectsV218(raw);box.innerHTML='<h3>棚で発動中の効果（合計の30%）</h3>'+figureGroupStatusV220('yusha','shelf')+'<p>発動タグ：なし（棚では通常タグ・隣接タグ・SOULスキルは発動しません）</p>';}finally{figureGroupEffectsV220=base;}$('[data-figure-list]',ov).before(box);};
for(const p of HELPER_PLAYERS_V218)p.ults=[];
const allyBaseV221=buildAlly;buildAlly=function(p,...args){const a=allyBaseV221(p,...args);if(p.helperV218)a.ults=[];return a;};
const availableBaseV221=availableUlts;availableUlts=a=>a?.helperV218||String(a?.id).startsWith('helper218-')?[]:availableBaseV221(a);
const soulUiBaseV221=updateSoulBadgesV220;updateSoulBadgesV220=function(){soulUiBaseV221();const bar=$('#figureSoulBarV218');if(bar)for(const btn of $$('[data-soul]',bar))if(state.battle?.figureSoulUsedV221?.includes(btn.dataset.soul)){btn.disabled=true;btn.classList.remove('ready');$('small',btn).textContent='使用済み';}};

const finishBaseV221=finishBattle;
finishBattle=function(win){const b=state.battle;if(!win||!b?.config?.legendV218||b.finished)return finishBaseV221(win);finishBaseV221(win);const ov=eventOverlayV163(),result=document.createDocumentFragment();while(ov.firstChild)result.append(ov.firstChild);const boss=b.enemies.find(e=>e.legendV218)||b.enemies[0];ov.innerHTML=`<div class="legend-victory-v221"><div class="victory-ring-v221"></div><img src="${boss.image}" alt=""><div class="victory-sparks-v221">${Array.from({length:24},(_,i)=>`<i style="--i:${i}"></i>`).join('')}</div><h2>LEGEND CLEAR!!</h2></div>`;b.victoryPresentationV221=(async()=>{try{await fixedDelay(matchMedia('(prefers-reduced-motion: reduce)').matches?300:2800);}finally{if(state.battle===b){ov.replaceChildren(result);ov.firstElementChild?.classList.add('victory-result-v221');}}})();return b.victoryPresentationV221;};

pinkGachaV220=async function(pattern){const ov=gachaSurfaceV219(),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;ov.innerHTML=`<section class="pink-stage-v220 cinematic-v221 ${pattern.id}"><div class="gacha-sky-v221"></div><div class="gacha-stars-v221">${Array.from({length:28},(_,i)=>`<i style="--i:${i};left:${(i*37)%100}%;top:${(i*23)%95}%"></i>`).join('')}</div><div class="gacha-portal-v221"></div><div class="gacha-meteor-v221"></div><div class="pink-speech-v220">行ってくるであります‼</div><div class="pink-runner-v220"><img src="${player('pink').image}" alt="モブピンク"></div><div class="treasure-row-v220"></div><div class="pink-rays-v220"></div></section>`;const stage=$('.pink-stage-v220',ov);await fixedDelay(reduced?120:1200);stage.classList.add('flight');await fixedDelay(reduced?120:1600);stage.classList.add('returned');$('.pink-speech-v220',ov).textContent=pattern.line;$('.treasure-row-v220',ov).innerHTML=(pattern.id==='choice'?['wood','gold']:pattern.id==='rush'?['gold','rainbow','gold','rainbow','gold']:[pattern.id==='wood'?'wood':pattern.id==='rainbow'?'rainbow':'gold']).map(chestMarkupV220).join('');await fixedDelay(reduced?120:1700);stage.classList.add('opened');await fixedDelay(reduced?120:1300);};
window.__mobBuildVersion='v221';
