/* v178: readable repeated passives and the revised Demon Castle story. */
function reactionTextV178(el,text){
 const segments=typeof Intl.Segmenter==='function'?[...new Intl.Segmenter('ja',{granularity:'word'}).segment(String(text))].map(x=>x.segment):String(text).split(/(?=[・/])/),words=[];
 for(const s of segments){if(words.length&&(/^[ぁ-ゖー％%]+$/.test(s)||/^[、。！？!?)）]+$/.test(s)))words[words.length-1]+=s;else words.push(s);}
 el.replaceChildren();for(const word of words){const span=document.createElement('span');span.className='reaction-word-v178';span.textContent=word;if([...word].length>16)span.classList.add('long');el.appendChild(span);}
}
reactionV177=async function(actor,name,effect,{weapon=false,gidora=false,skill=false}={}){
 const b=state.battle,key=(actor.uid||actor.id||actor.name)+'|'+String(name).replace(/\(\d+\/\d+\)/g,''),counts=b?(b.passiveViewsV178??={}):{},repeat=!weapon&&!skill&&Number(counts[key]||0)>0;
 if(!weapon&&!skill)counts[key]=(counts[key]||0)+1;
 const layer=document.createElement('div');layer.className='reaction-v177'+(gidora?' gidora':'')+(repeat?' repeat-v178':'');layer.innerHTML='<div class="reaction-card-v177"><img alt=""><div><small></small><b></b><p></p></div></div>';
 $('img',layer).src=weapon?versionedPlay(actor.image):actor.image;$('small',layer).textContent=(weapon?'武器特性 / ':skill?'必殺技 / ':'敵パッシブ / ')+actor.name;reactionTextV178($('b',layer),name);reactionTextV178($('p',layer),effect);document.body.appendChild(layer);
 const visual=weapon?$(`[data-ally-id="${actor.id}"]`):enemyVisual(actor.uid);visual?.classList.add('passive-glow-v177');
 try{await waitRealV100(repeat?900:gidora?2300:weapon?1200:1850);}finally{visual?.classList.remove('passive-glow-v177');layer.remove();}
};
for(const area of HOT_STORY_V177)for(const step of [...area.pre,...area.post])if(typeof step[2]==='string')step[2]=step[2].replace('さすがもう','さすがにもう');
const moneyUltimateV178=player('money')?.ults.find(u=>u.kind==='moneyFriends');if(moneyUltimateV178)moneyUltimateV178.desc='ヤミモブマニーに変身。戦闘終了まで全ステータス・状態異常耐性・魔法会心率を20%アップ。';
function castleAceTemplateV178(){const specials=[{special:'レーザー・パルス・ストレート',kind:'single',power:1.65,skillElement:'光',skillType:'magic'},{special:'エネルギー・エース・スマッシュ',kind:'castleAceRush178',power:1.55,skillElement:'光',skillType:'physical'}];return {...trainingEnemyTemplate('boss-ace'),castleAceV178:true,levelMin:73,levelMax:73,actionCount:2,forceActionCount:true,v144ActionMin:2,v144ActionMax:3,specialOptions:specials,firstActionSpec:specials[0],v120ExtraSkills:[]};}
const castleActionBaseV178=enemyAction;
enemyAction=async function(index=1,uid){const b=state.battle,e=enemyByUid(uid)||actingEnemy();if(e?.castleAceV178&&b?.turn===1&&index===1&&!e.firstActionUsed&&!['sleep','stun','paralyze'].some(k=>e.status[k]>0)){await drainReactionsV177();e.firstActionUsed=true;await bossSpecial(e.firstActionSpec);if(!livingRoster().length)finishBattle(false);return;}return castleActionBaseV178(index,uid);};
const castleSpecialBaseV178=bossSpecial;
bossSpecial=async function(spec){const e=actingEnemy()||state.battle?.enemy;if(spec?.kind!=='castleAceRush178')return castleSpecialBaseV178(spec);await enemySkillImageCutinV134(e,spec);for(const target of livingField()){await beginEnemyLunge(e.uid);try{await damageAlly(target,spec.power,'physical',isSuper(target),'光');await fixedDelay(240);}finally{endEnemyLunge();}}};
const castleNormalBaseV178=bossNormal;
bossNormal=async function(){const e=actingEnemy()||state.battle?.enemy;if(e?.id!=='boss-gladi')return castleNormalBaseV178();const target=pick(livingMain());if(!target)return;await actionCutin(e.name+'の攻撃！','danger',520);await playEnemyProjectile(e,target);await damageAlly(target,1,'physical',false,e.attribute);if(!target.dead&&Math.random()<.4)await inflictAllyStatus(target,pick(['poison','poison','burn','burn','paralyze','sleep','sleep','stun','stun','stun']),2);await fixedDelay(320);};

async function projectileV178(from,to,type='thunder'){const scene=$('#storyScene');scene.classList.add('projectile-'+type+'-v178');try{await orbV157(from,to,type==='light');if(type!=='light'){await storyFlash();await glowV157(to,1);}}finally{scene.classList.remove('projectile-'+type+'-v178');}}
async function blackSceneV178(ms=0,lines=[],setup=null){const layer=document.createElement('div');layer.className='castle-black-v178';layer.innerHTML='<small>モブ魔王</small><p></p>';document.body.appendChild(layer);if(!lines.length)$('small',layer).hidden=true;try{if(setup)await setup();for(const line of lines){$('p',layer).textContent=line;if(!skippingV174())await storyAdvanceWait();}if(ms)await fixedDelay(ms);await animateV157(layer,[{opacity:1},{opacity:0}],1400);}finally{layer.remove();}}
async function castleJumpV178(id){await hotJumpV177(storyAnchor(id));}
async function gladiEntryV178(){const g=$('#storyGuest');g.style.opacity='0';try{await storyShowGuest('boss-gladi');g.style.opacity='1';await animateV157(g,[{translate:'0 350px',opacity:0},{translate:'0 0',opacity:1}],280);}finally{g.style.removeProperty('opacity');}}
async function castleMarkV178(id){const actor=storyAnchor(id);if(!actor)return;const mark=document.createElement('b');mark.className='surprise-v157';mark.textContent='！';actor.appendChild(mark);try{await fixedDelay(800);}finally{mark.remove();}}
async function darkFadeV178(id){const actor=storyAnchor(id);await animateV157(actor,[{filter:'brightness(1)',opacity:1},{filter:'brightness(0) drop-shadow(0 0 25px #9b4dff)',opacity:.8,offset:.55},{filter:'brightness(0)',opacity:0}],1400);if(actor)actor.hidden=true;}
async function castleHistoryV178(pages){const scene=$('#storyScene');scene.classList.add('castle-history-v178');try{for(const text of pages){scene.classList.toggle('castle-horror-v178',text.includes('僕の目の前にいる'));const caption=document.createElement('div');caption.className='castle-history-caption-v178';caption.innerHTML='<small>モブリリス</small><p></p>';$('p',caption).textContent=text;scene.appendChild(caption);try{if(!skippingV174())await storyAdvanceWait();}finally{caption.remove();}}}finally{scene.classList.add('castle-history-exit-v178');await fixedDelay(900);scene.classList.remove('castle-history-v178','castle-horror-v178','castle-history-exit-v178');}}
async function quietPinkV178(){const scene=$('#storyScene');scene.classList.add('castle-history-v178');try{await storySay('pink','モブマニーが\n最後のレコード・・？');}finally{scene.classList.remove('castle-history-v178');}}
aceAttackV157=async function(){await projectileV178('boss-ace','boss-maou-castle');const ace=storyAnchor('boss-ace'),maou=storyAnchor('boss-maou-castle');if(ace&&maou){const dx=maou.getBoundingClientRect().left-ace.getBoundingClientRect().left;for(const dy of [-90,60,-45,90,0]){await animateV157(ace,[{translate:'0 0'},{translate:`${dx}px ${dy}px`,offset:.45},{translate:'0 0'}],240);await glowV157(maou,1);}}await blackSceneV178(3000);};

const castleStepsBaseV178=runStorySteps;
runStorySteps=async function(steps=[]){for(const step of steps){if(step[0]==='castleHistory178')await castleHistoryV178(step[1]);else if(step[0]==='castleJump178')await castleJumpV178(step[1]);else if(step[0]==='castleDarkFade178')await darkFadeV178(step[1]);else if(step[0]==='castleGladi178')await gladiEntryV178();else await castleStepsBaseV178([step]);}};
STORY_EVENTS['pre:demonCastle:1'].steps[0]=['castleGladi178'];
const lilithPostV178=STORY_EVENTS['post:demonCastle:2'].steps;
const historyStartV178=lilithPostV178.findIndex(s=>s[2]?.startsWith('モブネオンキングが')),historyEndV178=lilithPostV178.findIndex(s=>s[2]?.startsWith('そう君だよ'));
const historyPagesV178=lilithPostV178.slice(historyStartV178,historyEndV178).flatMap(s=>s[2].split('\n'));
lilithPostV178.splice(historyStartV178,historyEndV178-historyStartV178,['castleHistory178',historyPagesV178]);
lilithPostV178.splice(lilithPostV178.findIndex(s=>s[1]==='jessie'),0,['castleJump178','jessie']);
const lilithHideV178=lilithPostV178.findIndex(s=>s[0]==='hideGuest');lilithPostV178.splice(lilithHideV178,1,['castleDarkFade178','boss-lilith-castle'],['hideGuest']);
const closeCastleBaseV178=closeStoryScene;
closeStoryScene=async function(...args){$('#storyScene')?.classList.remove('castle-history-v178','castle-horror-v178');$$('.castle-black-v178,.castle-history-caption-v178').forEach(x=>x.remove());return closeCastleBaseV178(...args);};
window.__mobV178Runtime=true;

async function sayLinesV178(id,lines){for(const line of lines)await storySay(id,line);}
runDemonCastleArrivalStory=async function(){
  await openStoryScene('demonCastle',0);
  await storySay('pink','ここが魔王城でありますね・・！');
  await storyShowGuest('boss-ace',{slow:true});
  await storySay('boss-ace','まさかここまで来るとはな');await storySay('money','！？');await storySay('jessie','モブエース！！');
  await storySay('boss-ace','久しぶりだな\nこのような形での\n再開は望んでいなかった');await storySay('desert','魔王の側近と\n随分と仲が良さそうだな');await storySay('jessie','かつての仲間よ\n共にネオン街を守っていた\n保安官仲間');await storySay('desert','通りで強いわけだ\nさらに、王の息子なのだろう？');await storySay('pink','なぜ魔王軍に！');await storySay('denden','退屈だからでやんすか！？');await storySay('boss-ace','退屈か\nそうであれば\nどれほど幸せだろな');await storySay('money','はっきりとは覚えてないけど\n悪いやつではなかったはずよ！');await storySay('boss-ace','そうか\n少しは覚えているのか');await storySay('jessie','モブエース！\n１つ答えなさい！\nなぜネオン街を捨てた！');await storySay('boss-ace','捨ててなどいない\nお前と同じだモブジェシー！');await storySay('desert','目的の相違での戦い\n俺にも経験がある\n避けては通れないぞ！');await storySay('nekoku','オラ、みんなを守るぞ');await storySay('riro','悲しい戦いネ\nいや\n戦いは悲しいネ\nでも');await storySay('denden','それでも戦うでやんす！！');
  $('#storyScene').hidden=true;await startDemonAceStoryBattle();
  await openStoryScene('demonCastle',0);await storyShowGuest('boss-ace',{slow:true});await storySay('boss-ace','俺はまだ・・\n消えるわけにはいかない・・');await storySay('denden','オイラたちの勝ちでやんす！');await storySay('nyoro','もう終わりニョロ！');await storyNarrate('？？？「情けない」');
  await storyShowGuests(['boss-ace','boss-maou-castle'],{slow:true,silhouetteKeys:['boss-maou-castle']});
  await storySay('boss-maou-castle','我の側近が無様な姿を晒すとは');await storySay('boss-ace','申し訳、、ありません・・');await storySay('pink','魔王であります！！');await storySay('desert','こんなに早く出会うとはな');await storySay('boss-maou-castle','まあよい\n一度引き上げるぞ');await storySay('jessie','逃がさないわよ！');await projectileV178('jessie','boss-ace');await storyImpact('バチィッ!!');await storySay('boss-ace','グッ・・・！');await storySay('boss-maou-castle','随分と嫌われたようだな\n行くぞ');
  await demonTeleportPairV106();await storySay('denden','待つでやんす！！');await storySay('money','臆病者！');await storySay('desert','城内にいるはずだ\n先へ進むぞ！');
};
demonFinalPreV89Final=async function(){
  await blackSceneV178(0,['いつまで寝ているのだ','立て'],async()=>{await openStoryScene('demonCastle',3);duelPartyV158(true);await storyShowGuests(['boss-maou-castle','boss-ace'],{slow:true});});
  await storySay('boss-maou-castle','モブリリスがやられた\n我が軍は私とお前だけだ');await storySay('boss-ace','なんと、、');
  await storySay('boss-maou-castle','だが、終わりでは無い\n勇者を滅ぼし\n新たな軍勢を作る');await storySay('boss-ace','では、現状援軍などは無いと？');await storySay('boss-maou-castle','不要であろう\n私とお前がいる');await storySay('boss-ace','そうか');
  await storySay('boss-ace','この日をどれほど夢見たことか\n力を得て\nお前の側近となり\n討伐する\nこの日を！！');await storySay('boss-maou-castle','ほう、面白いな');await storySay('boss-ace','俺はネオン街の戦士\nモブエース\nお前を倒すチャンスを\nずっと伺っていた');await storySay('boss-ace','勇者たちと戦ったのも\nお前を倒せる力があるか\n見極めるためだ');
  await storySay('boss-maou-castle','この状況がチャンスだと？\nそんな体で何が出来る');await storySay('boss-ace','モブジェシーが放ったのは\n回復魔法だ');await storySay('boss-ace','そして');storyAnchor('boss-ace')?.classList.add('ace-charge-v178');await glowV157('boss-ace',2);await storySay('boss-ace','長年お前を見てきた\n闘い方、癖、仲間の強さ\n1対1なら\n今の俺なら勝てる!!');await storySay('boss-maou-castle','言いたいことはそれだけか？\nならば\n早く攻め入るが良い\n先に攻撃させてやる');await storySay('boss-ace','その油断が、お前の命取りだ！');
  await aceAttackV157();storyAnchor('boss-ace')?.classList.remove('ace-charge-v178');await storySay('boss-maou-castle','もう終わりか？');await storySay('boss-ace','はあ、はあ、\n化け物め・・');await storySay('boss-maou-castle','化け物か\n悪くない響きだ');await storySay('boss-ace','くそ、、\nこんなはずでは');
  await storySay('boss-maou-castle','お前は最初から間違えている\nモブマニーはいずれ\n世界を滅ぼす\nお前などが\n何をやったところで\n結果は変わらない');await storySay('boss-ace','意味ならあるさ\n必ず・・！！');await storySay('boss-maou-castle','お前の働きには感謝しているぞ\n安らかに眠れ');await projectileV178('boss-maou-castle','boss-ace','pyramid');await storySay('boss-ace','ッ・・！！');const aceV178=storyAnchor('boss-ace');if(aceV178)aceV178.style.opacity='.4';await fixedDelay(1000);await storySay('boss-ace','あとは任せたぞ・・');
  duelPartyV158(false);$('#storyPartyLine').style.removeProperty('visibility');await storySay('money','モブエース！？');await darkFadeV178('boss-ace');await storyHideGuests();await storyShowGuest('boss-maou-castle',{slow:true});await storySay('boss-maou-castle','一足遅かったな');await storySay('jessie','モブエース・・');await storySay('desert','仲間割れか？');await storySay('tetsu','腐っているでござる・・！');await storySay('nyoro','仲間を手にかけるなんて');await storySay('denden','血も涙もないでやんす！');
  await storySay('boss-maou-castle','仲間だと？\nハハハッ！こいつがか？\n笑わせるな');await storySay('jessie','それ以上モブエースを侮辱してみなさい\n後悔させてやるわ');await storySay('money','モブジェシー？');await storySay('boss-maou-castle','先代モブネオンキング\nモブエース\nあとは、お前達だけだな');await storySay('money','どういうこと？');await storySay('desert','何か秘密がありそうだな');await storySay('pink','僕たちを惑わそうとしているであります!!');
  await storySay('boss-maou-castle','ネオン街での戦いは\n2つの心を持つ魔女によって終結された\n王の息子と娘が魔女を封印し\n封印が解かれる日まで\n長年見守り続けてきた');await storySay('nekoku','思い出した\n「ネオン街の悪夢」\n国王様から聞いたことがある');await storySay('money','私は\nあんたに封印されたはず・・！');await storySay('boss-maou-castle','私に見覚えがあるか？');await storySay('money','それは・・');await storySay('boss-maou-castle','モブジェシー、お前はどうだ？');await storySay('jessie','私は、、');
  await storySay('boss-maou-castle','全て教えてやろう\nモブジェシー、モブエース\nお前たちはネオン街の王\nモブネオンキングの実の子だ\nそして\nモブマニーは\nネオン街に突如現れ');await storySayRed('boss-maou-castle','王に娘として育てられた魔女');await storySay('pink','2人は姉妹ということでありますか!?');await storySay('boss-maou-castle','モブジェシー、モブエースは\n命をかけてモブマニーを封印し\n記憶を改ざんしようとした\n封印はうまくいったが\n様々な記憶にノイズを入れることなったのだ');await storySay('desert','噛み合わなかったのはそのためか');
  await storySay('jessie','それがなんだというの？\nそれが本当なら\nモブマニーは大切な妹で心強い仲間\n何も変わらない！');await storySay('boss-maou-castle','お前たちはそうであろうな\nだが\nモブマニー、お前はどうだ？\nネオン街を半壊し王を消した魔女\nどんな気分だ？');await storySay('money','・・・・');await storySay('desert','答えなくていい\nお前は俺たちの仲間だ\nどうなっても変わらない');await storySay('boss-maou-castle','どうなっても、か');await storySay('nyoro','分からないニョロ・・\nこんな話をして\n魔王になんのメリットがあるニョロ？');await storySay('denden','そうでやんす\nこの程度じゃ僕たちは揺るがないでやんす！');await storySay('boss-maou-castle','下等な生き物は察しがいいな');await storySay('riro','鍵・・ネ');await storySay('pink','鍵？');await storySay('boss-maou-castle','ほうさすがだなサクラ一族');await storySay('riro','モブマニーは異世界への扉を開く最後の鍵');await storySay('jessie','どういうこと？');await storySay('pink','・・・・！');await quietPinkV178();
  await storySay('boss-maou-castle','その通り\nお前たちに易々とレコードを渡したのは\n全てのレコードを1か所に集結させるため\nモブマニーを手にし\n我ら魔王軍は異世界へと侵略する');await storySay('jessie','それがお前の野望・・！');await storySay('pink','そんなこと絶対にさせない！');await storySay('boss-maou-castle','おしゃべりはここまでだ\nこの魔法を発動するまで\n良い時間稼ぎになった\n「魔力解放の陣」');await glowV157('boss-maou-castle',2);await sealV157('money');await storySay('money','うわああああああ！！！！');await storyFlash();await storyHideGuest();await storyShowGuests(['boss-maou-castle','boss-yami-money'],{slow:true});hideMoneyV157();await storySay('jessie','モブマニー・・？');await storySay('boss-yami-money','私はモブマニー\n闇の魔女\nモブマニー');await storySay('jessie','そんな・・！');await storySay('boss-maou-castle','さあ、どんな風に踊ってくれるのだ？\nいずれまた会おう\n勇者と仲間達よ');
  await darkFadeV178('boss-maou-castle');await storyHideGuests();await storyShowGuest('boss-yami-money');await storySay('desert','魔力が巨大すぎる！一度退くぞ！');await storySay('denden','急ぐでやんす！');await storySay('pink','ここで逃げたら\nモブマニーは元に戻らないかもしれない！\n戦うべきであります！');await storySay('boss-yami-money','私は全てを滅ぼす存在\n勇者よ、覚悟!!');await storySay('jessie','戦わないで！');await moveV157('jessie',.5,.5);await storySay('riro','モブジェシー危なイ！');await storySay('tetsu','下がるでござる！');await orbV157('boss-yami-money','jessie');actorV157('jessie').style.opacity='.4';await storyImpact('ズドン!!');await storySay('jessie','うっ・・');await storySay('nyoro','まともに当たったニョロ！\n早く手当てをしないと！');await storySay('desert','いや、これは・・');await storySay('denden','そんな、、');await storySay('pink','僕に任せるであります');await moveV157('pink',.65,.5);await storySay('denden','何をする気でやんす！？');
  await storySay('pink','僕たち王国の兵士には\n自身の生命エネルギーを\n他者に与える力があります');await storySay('nyoro','ニョロ！？');await storySay('desert','馬鹿な真似はよせ！');await storySay('pink','80年であります');await storySay('nekoku','・・・・');await storySay('pink','モブマニーが自らを封印し\n前ネオン街の王が闇に消えてから\n80年であります');await storySay('desert','80年・・');await sayLinesV178('pink',['その間','モブジェシーは・・','モブジェシーとモブエースは','ずっと','ずっと','戦い続けたのであります','守り続けたのであります']);await storySayBigV94('pink','大切な妹を！');await sayLinesV178('pink',['僕たち兵士はいくらでも代わりがいる！','僕たちは所詮モブキャラだから！']);await castleJumpV178('pink');await storySayBigV94('pink','でも!!');await sayLinesV178('pink',['みなさんは違います・・','必ず、魔王を倒してください！！']);storyAnchor('pink')?.classList.add('pink-charge-v178');await sayLinesV178('pink',['勇者様','お供できて']);storyAnchor('pink')?.classList.add('full');await storySayBigV94('pink','光栄でした！');await storyNarrate('モブピンクが生命エネルギーを渡そうとした、その瞬間――');
  await orbV157('boss-yami-money','jessie',true);await surpriseV157();await glowV157('jessie',1);actorV157('jessie').style.opacity='1';await storySay('desert','モブピンク、待て！');await castleMarkV178('pink');await storySay('jessie','ん・・');await storySay('tetsu','モブジェシー！！');storyAnchor('pink')?.classList.remove('pink-charge-v178','full');await storySay('pink','気が付いたでありますか！？');await storySay('boss-yami-money','（みんな聞こえる！？）');await storySay('denden','モブマニーでやんす！');await storySay('nyoro','聞こえるニョロ！');await storySay('boss-yami-money','（私は大丈夫だから、）\n（遠慮なくぶっ飛ばして！）');await storySay('desert','そういうことなら任せろ');await storySay('pink','必ず助けるであります！');await resetMotionV157();await storySay('jessie','信じるよ！');await storySay('denden','オイラ強いでやんすよ！\nモブマニー！！');
};
demonFinalPostV89Final=async function(){
  await openStoryScene('demonCastle',3);await storyShowGuest('boss-yami-money',{slow:true});await glowV157('boss-yami-money',1);await storyHideGuest();restoreMoneyV157();await storyShowGuest('money',{slow:true});await storySay('jessie','モブマニー！');await storySay('pink','無事でありますか！？');await storySay('denden','返事するでやんす！');await sayLinesV178('money',['・・・・','・・・・','・・・・']);await storySayBigV94('money','うわ！');await storySay('desert','気が付いたか！');await storySay('nyoro','良かったニョロ～！！');await storySay('nekoku','オラ、嬉しい！');await storySay('tetsu','そなたは最高のサムライでござる！');await storySay('riro','本当に良かっタ・・');await storySay('jessie','闇に勝ったのね');await storySay('money','あの子がしたことも\n私の一部だから');await storySay('money','もう逃げない\nだから、友達になった！');await chorusV158('え！？',true);await storySay('money','あの子はあの子で大変そうでさ\nここまで来たら友達になろうって！');await storySay('desert','あの力が使えるのか？');await storySay('money','うん！私もっと強くなったよ！');await storySay('nyoro','心強いニョロ～！');await storySay('tetsu','また手合わせ願いたいでござるなー');await storySay('nekoku','！\n何か落ちてるぞ？');await storySay('desert','これは、、レコード！');
  await storyNarrate('7枚目のレコード\n「読みかけの本」を手に入れた！');state.meta.moneyFriendsUnlocked=true;state.meta.record7Obtained=true;saveMeta();
  await storySay('money','なんか\n私の友達が持ってたみたいね');await storySay('pink','7枚揃ったであります！\n王様に報告しましょう！');await storySay('money','待って！\nみんな\n・・・・\nありがとう！');await storyNarrate('モブマニーは新必殺技を覚えた！\n新必殺技「マニーフレンズ」\nヤミモブマニーに変身し、全てのステータス20%アップ\nさらに状態異常耐性を20%アップ、魔法会心率を20%アップする\n戦闘終了後、解除される');
};
