/* September 24: revised raid cadence and regional gachas. */
figureOverflowRubyV115=f=>({R:1,SR:2,SSR:5,UR:10,MOB:20}[f?.rarity]||1);
mapleShopUnlocked=()=>worldCleared('grassland');
const COMMON_GACHA_V219=[...figImgV96(1,25),...figImgV96(81,83)];
const GACHA_ROWS_V219=[
 ['001','草原','grassland',eneImgV96(1,6),bossImgV96(1,1),[45,46,50]],
 ['002','砂漠','desert',eneImgV96(10,14),bossImgV96(3,3),[61,62,49]],
 ['003','田舎町','rural',eneImgV96(18,21),bossImgV96(5,6),[34,44,48]],
 ['004','マグマ','magma',eneImgV96(52,56),bossImgV96(10,10),[40,51]],
 ['005','ネオン街','neon',eneImgV96(29,33),bossImgV96(7,8),[26,27,42]],
 ['008','海底','sea',eneImgV96(37,43),bossImgV96(43,43),[43,52,53,54,55,75,76,77,78]],
 ['006','部族村','tribe',eneImgV96(45,50),bossImgV96(13,16),[63,64,65,66,67]],
 ['007','草原Ⅱ','grassland2',eneImgV96(1,9),bossImgV96(2,2),[45,46,47,50]],
 ['015','田舎町Ⅱ','rural2',eneImgV96(18,28),bossImgV96(17,17),[35,36,37,38,41]],
 ['009','ネオン街Ⅱ','neon2',eneImgV96(29,36),bossImgV96(18,18),[28,29,30,31,58]],
 ['010','マグマⅡ','magma2',eneImgV96(51,61),bossImgV96(10,10),[39,56,57]],
 ['011','砂漠Ⅱ','desert2',[...eneImgV96(52,56),...eneImgV96(10,17)],[...bossImgV96(10,10),...bossImgV96(4,4),...bossImgV96(27,30)],[40,51,59,60,68,69]],
 ['012','魔王城','demonCastle',eneImgV96(65,72),[...bossImgV96(19,22),...bossImgV96(31,31)],[84,85,86,87]],
 ['013','読みかけの本','book',eneImgV96(10,17),[35,36,39,41].map(n=>`figboss/${n}.png`),[79,80,89,90,91,92]]
];
FIGURE_GACHAS_V96.splice(0,FIGURE_GACHAS_V96.length,...GACHA_ROWS_V219.map(([id,name,world,enemies,bosses,figs])=>({id,name:name+'ガチャ',world,extra:[...enemies,...bosses,...figs.map(n=>`fig/${String(n).padStart(2,'0')}.png`)],unlock:()=>world==='book'?!!state.meta.bookCompleted:worldCleared(world)})));
gachaPoolV96=b=>[...new Set([...COMMON_GACHA_V219,...(b?.extra||[])])].map(figureByImageV96).filter(usableFigureV103);
// Pickups are illustrative until specified; they do not change draw probabilities.
gachaPickupsV96=()=>[];
let gachaFocusV219='';
function gachaSurfaceV219(){const ov=ensureGachaOverlayV96();ov.className='gacha-overlay-v219';ov.hidden=false;return ov;}
function gachaImageV219(f){return `<img src="${f.image}" alt="${f.name}">`;}
function closeGachaV219(id){ensureGachaOverlayV96().hidden=true;restoreGachaCarouselV100(id||gachaFocusV219);}
function gachaDetailV219(f,ov){const pop=document.createElement('div');pop.className='gacha-detail-v219';pop.innerHTML=`<section><button data-detail-close type="button">性能を閉じる ×</button>${figureDetailMarkupV96(f)}</section>`;ov.append(pop);bindImages(pop);$('[data-detail-close]',pop).onclick=e=>{e.stopPropagation();pop.remove();};}
renderFigureGachaShopV98=function(focus=''){const card=$('.maple-shop-card',$('#tavernFigurePopup'));if(!card)return;gachaFocusV219=focus||gachaFocusV219;const rows=FIGURE_GACHAS_V96.filter(b=>b.unlock());card.innerHTML=`<div class="settings-head"><div><small>FIGURE GACHA</small><h2>モブメープル</h2></div><button id="tavernFigureCloseBtn" class="sheet-close" type="button">×</button></div><div class="maple-shop-host"><img src="play/009.png" alt="モブメープル"><p>好きなガチャを横にスワイプして選んでね！</p></div><div class="gacha-wallet-v219">◆ ダイヤ ${Number(state.meta.diamonds)||0}　♦ ルビー ${rubyOwnedV115()}</div><div class="gacha-carousel-v219">${rows.map(b=>`<button data-banner="${b.id}" type="button"><img src="gacha/${b.id}.png" alt="${b.name}"><b>${b.name}</b><small>1回 5ダイヤ / 10連 50ダイヤ</small></button>`).join('')||'<p>エリアをクリアするとガチャが解放されます。</p>'}</div><p class="gacha-rate-note-v96">R 50% / SR 30% / SSR 15% / UR 4.5% / MOB 0.5%<br>10連の最後はSR以上確定</p><button data-piece type="button">モブピースバトル</button>`;bindImages(card);$('#tavernFigureCloseBtn').onclick=()=>{$('#tavernFigurePopup').hidden=true;};$('[data-piece]',card).onclick=openMobPieceMenuV96;$$('[data-banner]',card).forEach(b=>b.onclick=()=>openGachaDetailV96(b.dataset.banner));requestAnimationFrame(()=>{const grid=$('.gacha-carousel-v219',card),target=$(`[data-banner="${gachaFocusV219}"]`,grid);if(target)grid.scrollLeft=target.offsetLeft-grid.offsetLeft-(grid.clientWidth-target.clientWidth)/2;});};
renderFigureGachaShopV96=renderFigureGachaShopV98;
openGachaDetailV96=function(id){if(gachaBusyV110)return;const b=FIGURE_GACHAS_V96.find(b=>b.id===id);if(!b?.unlock())return;gachaFocusV219=id;const ov=gachaSurfaceV219();ov.innerHTML=`<section class="gacha-panel-v219"><img class="gacha-banner-v219" src="gacha/${b.id}.png" alt="${b.name}"><h2>${b.name}</h2><p>◆ ダイヤ ${Number(state.meta.diamonds)||0}</p><div class="gacha-actions-v219"><button data-lineup>ラインナップを見る</button><button data-one>1回 5ダイヤ</button><button data-ten>10連 50ダイヤ</button><button data-cancel>キャンセル</button></div></section>`;$('[data-lineup]',ov).onclick=()=>showGachaLineupV96(b);$('[data-one]',ov).onclick=()=>drawGachaV96(b,1);$('[data-ten]',ov).onclick=()=>drawGachaV96(b,10);$('[data-cancel]',ov).onclick=()=>closeGachaV219(id);};
showGachaLineupV96=function(b){if(!b.unlock())return;const ov=gachaSurfaceV219(),pool=gachaPoolV96(b),featured=b.extra.map(figureByImageV96).filter(Boolean).sort((a,b)=>['MOB','UR','SSR','SR','R'].indexOf(a.rarity)-['MOB','UR','SSR','SR','R'].indexOf(b.rarity)).slice(0,5);const tile=f=>`<button data-figure="${f.id}" class="rarity-${figureRarityClass(f.rarity)}">${gachaImageV219(f)}<small>${f.rarity}</small><b>${f.name}</b></button>`;ov.innerHTML=`<section class="gacha-panel-v219"><button data-back aria-label="ガチャへ戻る">← 戻る</button><h2>全${pool.length}種！</h2><p>このガチャのピックアップはこちら！</p><small>注目フィギュアの紹介です（排出率アップなし）</small><div class="gacha-grid-v219">${featured.map(tile).join('')}</div><h3>全ラインナップ</h3><div class="gacha-grid-v219">${pool.map(tile).join('')}</div></section>`;bindImages(ov);$('[data-back]',ov).onclick=()=>openGachaDetailV96(b.id);$$('[data-figure]',ov).forEach(btn=>btn.onclick=()=>gachaDetailV219(figureById(btn.dataset.figure),ov));};
async function graffitiGachaV219(){const ov=gachaSurfaceV219();ov.innerHTML=`<div class="gacha-graffiti-v219" aria-label="ガチャ演出">${Array.from({length:16},(_,i)=>`<b style="--x:${(i%4-1.5)*170}px;--y:${(Math.floor(i/4)-1.5)*180}px;--r:${i%2?18:-18}deg;--ink:${['#ff69ad','#65f6df','#ffe65b','#a897ff'][i%4]};--delay:${i*.035}s">MOB</b>`).join('')}<div class="gacha-flash-v219"></div></div>`;await fixedDelay(matchMedia('(prefers-reduced-motion: reduce)').matches?150:2300);}
showGachaResultV115=function(b,entries){return new Promise(resolve=>{const ov=gachaSurfaceV219(),rank={R:0,SR:1,SSR:2,UR:3,MOB:4},best=Math.max(...entries.map(e=>rank[e.f.rarity]||0));ov.innerHTML=`<section class="gacha-panel-v219 gacha-result-v219"><div class="gacha-confetti-v219" aria-hidden="true">${Array.from({length:8+best*12},(_,i)=>`<i style="left:${i*37%100}%;--delay:${i%9*.09}s;background:${['#ff73ba','#72f6e5','#ffdc68','#a9a1ff'][i%4]}"></i>`).join('')}</div><small>FIGURE GET!</small><h2>${entries.length===1?entries[0].f.name+'を獲得した！':'10連結果'}</h2><div class="gacha-grid-v219 ${entries.length===1?'single':''}">${entries.map((e,i)=>`<button data-result="${i}" class="rarity-${figureRarityClass(e.f.rarity)} ${e.converted?'converted-v219':''}">${gachaImageV219(e.f)}<small>${e.f.rarity}</small><b>${e.f.name}</b><em>${e.converted?'♦ ルビー +'+e.ruby:e.plus?'強化 +'+e.plus:'NEW!'}</em></button>`).join('')}</div><p>フィギュアをタップすると性能を確認できます</p><button data-results-close>結果を閉じる</button></section>`;bindImages(ov);$$('[data-result]',ov).forEach(btn=>btn.onclick=()=>gachaDetailV219(entries[+btn.dataset.result].f,ov));$('[data-results-close]',ov).onclick=()=>{ov.hidden=true;resolve();};});};
drawGachaV96=async function(b,count){if(gachaBusyV110||![1,10].includes(count)||!b?.unlock())return;gachaBusyV110=true;const cost=count===10?50:5;try{ensureGachaOverlayV96().hidden=true;const answer=await dialog('このガチャを引くの？',[['はい','yes','primary'],['いいえ','no']],'モブメープル','play/009.png');if(answer!=='yes')return;if((Number(state.meta.diamonds)||0)<cost){await facilityTalk('ダイヤが足りないよ！','モブメープル','play/009.png');return;}
 const figs=Array.from({length:count},(_,i)=>gachaRollV96(b,count===10&&i===9));if(figs.some(f=>!f))throw new Error('ガチャの排出データがありません');state.meta.diamonds-=cost;const entries=figs.map(awardGachaFigureV115);saveMeta();await Promise.all([graffitiGachaV219(),preloadFigureRowsV110(figs,3200)]);await showGachaResultV115(b,entries);
 }finally{gachaBusyV110=false;closeGachaV219(b.id);}};

const freshLegendBaseV219=buildEnemyFromTemplate;buildEnemyFromTemplate=function(t,...args){const e=freshLegendBaseV219(t,...args);if(t?.legendV218)e.hp=e.maxHp;return e;};
function cadenceLegendV219(b){return !!b?.config?.legendV218&&b.config.legendV218!=='magnum';}
const raidQueueBaseV219=processQueue;processQueue=async function(...args){const b=state.battle;if(cadenceLegendV219(b)&&b.queuePos===0&&b.legendQueueTurnV219!==b.turn){b.queue=b.queue.filter(x=>x.type!=='enemy');b.legendQueueTurnV219=b.turn;}return raidQueueBaseV219(...args);};
function recordLegendAllyActionV219(b){if(!cadenceLegendV219(b)||b.finished)return;b.legendAllyActionsV219=(b.legendAllyActionsV219||0)+1;if(b.legendAllyActionsV219<4)return;b.legendAllyActionsV219=0;const e=livingEnemies().find(e=>e.legendV218);if(!e)return;const n=e.legendShieldV218||e.legendRageV218?5:3;b.queue.splice(b.queuePos+1,0,...Array.from({length:n},(_,i)=>({type:'enemy',enemyId:e.uid,action:i+1})));}
saveLegendV218=function(b,win=false){const e=b?.enemies.find(e=>e.legendV218);if(!e)return;const rec=legendRecordV218(e.legendV218);delete rec.remaining;rec.maxHp=e.maxHp;if(win)rec.cleared=true;saveMeta();};
window.__mobBuildVersion='v219';
