const assert=require('node:assert/strict'),{open}=require('./story-v172-harness.cjs');
const injection=`window.banditTest230={
 setup:()=>{state.party=['yusha','pink','desert','denden','money','nyoro','nekoku','jessie'].map(id=>[id,75]);state.training.party=state.party.map(x=>[...x]);state.meta.openingCompleted=true;state.meta.trainingPlayed=true;state.test.enabled=false;state.meta.storyEventsV179={};confirmStoryChallengeV179=async()=>true;fixedDelay=async()=>{};animateV157=async()=>{};delay=async()=>{};startRound=()=>{};},
 locks:()=>{const base=worldCleared;worldCleared=id=>id==='rural';const first=[0,1,2].map(d=>openV179('bandits',d));recordsV179('bandits')[0]=true;const after=[0,1,2].map(d=>openV179('bandits',d));worldCleared=()=>true;const unlocked=[0,1,2].map(d=>openV179('bandits',d));state.meta.storyEventsV179={};worldCleared=base;return{first,after,unlocked};},
 menu:()=>{worldCleared=()=>true;eventViewV163='story';selectedStoryV179=null;renderEventQuestsV163();$('#trainingFeaturePopup').hidden=false;showScreen('training');},
 fastScenes:()=>{window.scenes230=[];banditSceneV230=async phase=>scenes230.push([eventRunV174.difficulty,eventRunV174.area,phase]);},
 start:async d=>{await startV179('bandits',d);return{party:state.battle.allies.map(a=>a.id),area:eventRunV174.area};},
 snap:()=>({d:eventRunV174?.difficulty,area:eventRunV174?.area,finished:state.battle?.finished,waves:state.battle?.pendingWaveConfigs?.length,enemies:state.battle?.enemies.map(e=>({key:e.banditV230,hp:e.maxHp,level:e.level,category:e.category,cut:e.damageReduction,min:e.v144ActionMin,max:e.v144ActionMax})),record:recordsV179('bandits')}),
 win:async()=>{const b=state.battle;for(const e of b.enemies){e.hp=0;recordEnemyDefeat(e);}await handleEnemyWaveClear();},
 rewards:()=>({coins:state.coins,diamonds:state.meta.diamonds,figures:[56,57,58,59,60].map(n=>figureOwned(figureByImageV96('eventfig/'+n+'.png').id)),medal:medalOwned('event-horapue-medal')}),
 repeat:()=>rewardV179(),
 medal:()=>weaponStatBonus({main:null,sub:null,medals:['event-horapue-medal']}),
 templates:()=>[0,1,2].map(d=>STORY179.bandits.diffs[d].areas).map((n,d)=>Array.from({length:n},(_,area)=>banditWavesV230(d,area).map(w=>w.length))),
};`;
(async()=>{const x=await open(injection);try{const{page,errors}=x;assert.deepEqual(errors,[]);await page.evaluate(()=>banditTest230.setup());assert.deepEqual(await page.evaluate(()=>banditTest230.locks()),{first:[true,false,false],after:[false,false,false],unlocked:[false,true,false]});assert.deepEqual(await page.evaluate(()=>banditTest230.templates()),[[[3,3],[2],[5,5],[2]],[[5,5],[5,5,2],[1]],[[3],[5,5,5],[3],[5]]]);assert.equal((await page.evaluate(()=>banditTest230.medal())).spd,8);
await page.evaluate(()=>banditTest230.menu());await page.locator('[data-story230="bandits"]').click();assert(await page.getByText('砂漠の盗賊ファミリー！',{exact:true}).isVisible());assert.equal(await page.locator('[data-v179-start]').count(),3);await page.screenshot({path:'tests/v230-bandit-menu.png'});await page.evaluate(()=>banditTest230.fastScenes());
for(let d=0;d<3;d++){const before=await page.evaluate(()=>banditTest230.rewards()),start=await page.evaluate(d=>banditTest230.start(d),d);if(d<2)assert.deepEqual(start.party,d===0?['yusha','pink','desert','denden']:['yusha','money','nyoro','nekoku']);let areas=0,waves=0;
while(true){const s=await page.evaluate(()=>banditTest230.snap());await page.evaluate(()=>banditTest230.win());waves++;if(s.waves)continue;areas++;await page.locator('[data-v179-next]').waitFor({state:'visible'});const last=areas===[4,3,4][d];if(last){assert((await page.locator('.event-result-v163').innerText()).includes('QUEST CLEAR'));assert.equal(await page.evaluate(()=>banditTest230.repeat()),null);await page.locator('[data-v179-next]').click();break;}await page.locator('[data-v179-next]').click();await page.waitForFunction(()=>!banditTest230.snap().finished);}
assert.equal(waves,[6,6,6][d]);const after=await page.evaluate(()=>banditTest230.rewards());assert.equal(after.diamonds-(before.diamonds||0),[50,100,150][d]);assert(after.coins-before.coins>=[5000,10000,50000][d]);}
const rewards=await page.evaluate(()=>banditTest230.rewards());assert.deepEqual(rewards.figures,[1,1,1,1,1]);assert.equal(rewards.medal,1);assert.equal((await page.evaluate(()=>scenes230)).length,22);await page.reload();assert.deepEqual((await page.evaluate(()=>banditTest230.rewards())).figures,[1,1,1,1,1]);assert.equal((await page.evaluate(()=>banditTest230.rewards())).medal,1);assert.deepEqual(errors,[]);console.log('v230 PASS: three unlock gates, parties, 11 areas/18 waves, hard ends at area3, all five figures and medal, no duplicate rewards');
}finally{await x.browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
