const assert=require('node:assert/strict'),path=require('node:path'),{open}=require('./story-v172-harness.cjs');
const injection=`
const realDelay218=fixedDelay;fixedDelay=ms=>realDelay218(Math.min(25,ms));
window.live218={
 setup:()=>{state.party=['yusha','pink','desert','denden','money','jessie','tetsu','nyoro','nekoku','kaijin'].map(id=>[id,80]);state.meta.openingCompleted=true;state.meta.trainingPlayed=true;worldCleared=()=>true;state.autoBattle=false;passiveChance=()=>false;initiativeSpeed=e=>e.type==='enemy'?1:10000;},
 start:()=>startLegendV218(LEGENDS_V218[0],['dolphin','coach']),
 snap:()=>({allies:state.battle?.allies.length,main:state.battle?.mainIds.length,busy:state.battle?.busy,queue:state.battle?.queue.map(x=>[x.type,x.id||x.enemyId]),active:activeAlly()?.id,hp:state.battle?.enemies[0]?.hp,turn:state.battle?.turn}),
 figure:()=>{const a=activeAlly(),f=figureById('01');state.meta.figures[f.id]=1;state.meta.figurePlusV218??={};a.figureEquipment=[f.id];a.hp=Math.max(1,a.hp-100);a.figureSoulV218={[f.id]:f.soul.cost};renderBattle();return{hp:a.hp,queuePos:state.battle.queuePos,id:a.id};},
 figureSnap:()=>{const a=activeAlly();return{hp:a.hp,queuePos:state.battle.queuePos,soul:a.figureSoulV218?.['01']};},
 rewards:()=>({value:state.meta.legendsV218?.caramel}),
 kill:()=>{const e=state.battle.enemies[0];e.hp=1;e.evasion=0;calcDamage=()=>({value:10000,crit:false,miss:false});}
};`;
(async()=>{const x=await open(injection);let failed;try{const {page,errors}=x;const consoleErrors=[];page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('Failed to load resource'))consoleErrors.push(m.text());});await page.evaluate(()=>live218.setup());await page.evaluate(()=>live218.start());await page.waitForFunction(()=>{const s=live218.snap();return s.active&&!s.busy;});const s=await page.evaluate(()=>live218.snap());assert.equal(s.allies,12);assert.equal(s.main,12);assert.equal(s.queue.filter(x=>x[0]==='ally').length,12);await page.screenshot({path:path.join(__dirname,'v218-raid.png')});const before=await page.evaluate(()=>live218.figure());await page.locator('[data-soul="01"]').click();await page.getByRole('button',{name:'発動',exact:true}).click();await page.waitForFunction(()=>!live218.snap().busy);const after=await page.evaluate(()=>live218.figureSnap());assert.equal(after.queuePos,before.queuePos);assert.equal(after.soul,0);assert(after.hp>before.hp);await page.evaluate(()=>live218.kill());await page.locator('#attackBtn').click();await page.getByText('LEGEND CLEAR!!',{exact:true}).waitFor();assert((await page.evaluate(()=>live218.rewards())).value.rewarded);assert.deepEqual(errors,[]);assert.deepEqual(consoleErrors,[]);console.log('v218 LIVE PASS: 12 allies in actual initiative queue, click SOUL/confirm heals without consuming a turn, attack -> legend victory -> first reward');}catch(e){failed=e;console.error(e);}finally{await x.browser.close();}if(failed)throw failed;})().then(()=>process.exit(0),()=>process.exit(1));
