const fs=require('node:fs'),assert=require('node:assert/strict'),{open}=require('./story-v172-harness.cjs');
const injection=`window.eq256={init(){state.party=[['yusha',80],['pink',80]];state.meta.weapons={'01':3,'06':3};state.meta.medals=Object.fromEntries(WEAPONS.map(w=>[w.id,4]));state.meta.equipment={yusha:{main:'01',sub:'06',medals:['05',null,null]},pink:{main:'01',sub:'06',medals:[]}};saveParty();saveMeta();},eq:id=>clone(equipmentFor(id)),set:(pid,kind,id,index=0)=>setPlayerEquipment(pid,kind,index,id),stats:eq=>weaponStatBonus(eq),traits:eq=>weaponTraitEntries(eq).map(e=>({id:e.weapon.id,trait:e.trait,socket:e.socket})),weapons:()=>WEAPONS,stock:()=>clone(state.meta.medals),save:()=>saveMeta(),snapshot:()=>JSON.stringify(WEAPONS),scale:(id,key)=>({stats:socketStatsV256(weaponById(id),key),traits:socketTraitsV256(weaponById(id),key),text:socketTraitTextV256(weaponById(id),key)}),owned(id,n){state.meta.medals[id]=n;},raw(eq){state.meta.equipment.yusha=eq;saveMeta();},render(){equipmentPlayerId='yusha';equipmentTab='equip';renderEquipment();showScreen('equipment');},calc(){return baseStats(player('yusha'),80);}};`;
(async()=>{const x=await open(injection),checks=[];try{const p=x.page;await p.evaluate(()=>eq256.init());const stock=await p.evaluate(()=>eq256.stock()),catalog=await p.evaluate(()=>eq256.weapons()),snapshot=await p.evaluate(()=>eq256.snapshot());const initial=await p.evaluate(()=>eq256.eq('yusha'));assert.equal(initial.mainMedal,null);assert.equal(initial.subMedal,null);assert.deepEqual(initial.medals,['05',null,null]);
for(const w of catalog){for(const key of ['mainMedal','subMedal']){const scaled=await p.evaluate(([id,k])=>eq256.scale(id,k),[w.id,key]);for(const [stat,v] of Object.entries(w.stats||{}))assert.equal(scaled.stats[stat],Math.floor(v*.1*(key==='mainMedal'?2:.5)+1e-9));for(let i=0;i<(w.traits||[w.trait]).filter(Boolean).length;i++){const t=(w.traits||[w.trait]).filter(Boolean)[i],actual=scaled.traits[i];for(const k of ['value','chance','power'])if(t[k]!==undefined)assert.equal(actual[k],key==='mainMedal'?t[k]:Math.floor(t[k]*50+1e-9)/100);if(t.threshold!==undefined)assert.equal(actual.threshold,t.threshold);}checks.push([w.id,key]);}}
assert.equal(await p.evaluate(()=>eq256.set('yusha','mainMedal','event-phoenix-medal')),false);for(const w of catalog.filter(w=>w.type==='メダル'))assert.equal(await p.evaluate(id=>eq256.set('yusha','mainMedal',id),w.id),false);
assert.equal(await p.evaluate(()=>eq256.set('yusha','mainMedal','05')),true);assert.equal(await p.evaluate(()=>eq256.set('yusha','subMedal','06')),true);const eq=await p.evaluate(()=>eq256.eq('yusha')),base=await p.evaluate(eq=>eq256.stats({...eq,mainMedal:null,subMedal:null}),eq),actual=await p.evaluate(eq=>eq256.stats(eq),eq);for(const k of Object.keys(base))assert.equal(actual[k],base[k]+Math.floor((catalog.find(w=>w.id==='05').stats[k]||0)*.2+1e-9)+Math.floor((catalog.find(w=>w.id==='06').stats[k]||0)*.05+1e-9));assert.equal((await p.evaluate(eq=>eq256.traits(eq),eq)).find(x=>x.socket==='subMedal').trait.value,.02);
await p.evaluate(()=>eq256.save());await p.reload({waitUntil:'load'});assert.deepEqual(await p.evaluate(()=>eq256.eq('yusha')),eq);assert.deepEqual(await p.evaluate(eq=>eq256.stats(eq),eq),actual);await p.reload({waitUntil:'load'});assert.deepEqual(await p.evaluate(()=>eq256.stock()),stock);assert.equal(await p.evaluate(()=>eq256.snapshot()),snapshot);
await p.evaluate(()=>eq256.set('yusha','sub',null));assert.equal((await p.evaluate(()=>eq256.eq('yusha'))).subMedal,'06');assert.ok(!(await p.evaluate(()=>eq256.traits(eq256.eq('yusha')))).some(x=>x.socket==='subMedal'));await p.evaluate(()=>eq256.set('yusha','sub','06'));assert.equal(await p.evaluate(()=>eq256.set('yusha','subMedal',null)),true);assert.equal(await p.evaluate(()=>eq256.set('yusha','mainMedal',null)),true);
await p.evaluate(()=>{eq256.owned('06',1);});assert.equal(await p.evaluate(()=>eq256.set('yusha','mainMedal','06')),true);assert.equal(await p.evaluate(()=>eq256.set('pink','subMedal','06')),false);assert.equal(await p.evaluate(()=>eq256.set('yusha','medal','06',1)),false);assert.equal(await p.evaluate(()=>eq256.set('yusha','mainMedal','06')),true);
await p.evaluate(()=>eq256.raw({main:'01',sub:'06',mainMedal:'event-phoenix-medal',medals:['05',null,null]}));assert.equal((await p.evaluate(()=>eq256.eq('yusha'))).mainMedal,null);assert.deepEqual((await p.evaluate(()=>eq256.eq('yusha'))).medals,['05',null,null]);assert.deepEqual(x.errors,[]);fs.writeFileSync('artifacts/equipment-v256/results.json',JSON.stringify({checks,monsterRejected:39,oldSlotsKept:true,reloadStable:true,inventoryStable:true,hostRemovalInactive:true},null,2));console.log('PASS '+checks.length+' scaling sets, monster rejection, stock constraints, reload, inactive host, old slots');
}finally{await x.browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
