const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{open,root}=require('./story-v172-harness.cjs');
const baseInjection=fs.readFileSync('tests/equipment-v256.cjs','utf8').match(/const injection=`([\s\S]*?)`;/)[1];
const injection=baseInjection+`eq256.camp=()=>{showScreen('adventure');$('#campOverlay').hidden=false;$('#campMainMenu').hidden=true;$('#campSubPanel').hidden=false;campEquipPlayerId='yusha';renderCampEquipment();syncCampModalV133();};`;
(async()=>{const x=await open(injection);try{const p=x.page;await p.evaluate(()=>eq256.init());const stock=await p.evaluate(()=>eq256.stock());for(const width of [320,375,390]){await p.setViewportSize({width,height:844});await p.evaluate(()=>eq256.render());assert.equal(await p.locator('#equipmentContent [data-equip-slot="medal"]').count(),3);assert.equal(await p.locator('#equipmentContent [data-equip-slot="mainMedal"]').count(),1);assert.equal(await p.locator('#equipmentContent [data-equip-slot="subMedal"]').count(),1);
await p.locator('#equipmentContent [data-equip-slot="mainMedal"]').click();assert.equal(await p.locator('[data-socket-medal="event-phoenix-medal"]').isDisabled(),true);await p.screenshot({path:path.join(root,'artifacts/equipment-v256/main-picker-'+width+'.png')});await p.locator('[data-socket-medal="06"]').click();assert.equal((await p.evaluate(()=>eq256.eq('yusha'))).mainMedal,'06');
await p.locator('#equipmentContent [data-equip-slot="subMedal"]').click();await p.locator('[data-socket-medal="rush-savanna-v252"]').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(root,'artifacts/equipment-v256/sub-picker-'+width+'.png')});await p.locator('[data-socket-medal="rush-savanna-v252"]').evaluate(e=>{e.click();e.click();});assert.equal((await p.evaluate(()=>eq256.eq('yusha'))).subMedal,'rush-savanna-v252');await p.locator('#equipmentContent [data-equip-slot="subMedal"]').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(root,'artifacts/equipment-v256/equipped-'+width+'.png')});
await p.locator('#equipmentContent [data-equip-slot="mainMedal"]').click();await p.locator('[data-socket-close]').click();assert.equal(await p.locator('#socketPickerV256').evaluate(e=>e.hidden),true);await p.locator('#equipmentContent [data-equip-slot="mainMedal"]').click();assert.equal(await p.locator('[data-socket-medal="06"]').isDisabled(),false);await p.locator('[data-socket-close]').click();assert.equal(await p.locator('body').evaluate(e=>e.scrollWidth>innerWidth+1),false);}
await p.evaluate(()=>eq256.camp());await p.locator('#campSubPanel [data-equip-slot=mainMedal]').click();await p.locator('[data-socket-medal=\"07\"]').click();assert.equal((await p.evaluate(()=>eq256.eq('yusha'))).mainMedal,'07');await p.screenshot({path:path.join(root,'artifacts/equipment-v256/camp.png')});assert.deepEqual(await p.evaluate(()=>eq256.stock()),stock);assert.deepEqual(x.errors,[]);fs.writeFileSync('artifacts/equipment-v256/ui-results.json',JSON.stringify({widths:[320,375,390],oldSlots:3,addedSlots:2,cancelReopen:true,doubleTapNoDuplicate:true},null,2));console.log('PASS 320/375/390, five medal slots, rejection, equip, cancel/reopen/double tap');
}finally{await x.browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
