const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {open,root}=require('./story-v172-harness.cjs');
const output=path.join(os.tmpdir(),'mob-quest-v174');fs.mkdirSync(output,{recursive:true});
const injection=`window.test174={
 close(){storyBusy=false;return closeStoryScene(false);},
 seed(){state.adventure=defaultAdventure();state.adventure.reportedWorlds=['grassland','desert','rural'];state.party=['yusha','pink','desert','denden','money','nyoro','nekoku'].map(id=>[id,90]);state.meta.trainingPlayed=true;state.meta.openingCompleted=true;state.meta.exp={yusha:100};state.meta.storyEventsV174={savanna:{}};state.test.enabled=true;state.training.mode='event';state.coins=100;state.meta.coins=100;state.meta.diamonds=0;showScreen('training');eventViewV163='story';renderTraining();$('#trainingFeaturePopup').hidden=false;},
 assets(){return [...SAVANNA_FIGURES_V174.map(f=>f.image),...['normal','variant','water','wind','nagi','metal'].map(k=>savannaTemplateV174(k).image)];},
 audit(){return {figs:SAVANNA_FIGURES_V174.map(f=>figureByImageV96(f.image)),waves:[0,1,2].map(d=>[0,1,2,3].map(a=>buildEnemyWave(savannaWaveV174(a,d),4,'','').map(e=>({name:e.name,hp:e.hp,maxHp:e.maxHp,level:e.level,cut:e.damageReduction,evade:e.evasion,actions:e.actionCount,min:e.v144ActionMin,max:e.v144ActionMax,preempt:e.preemptive}))))};},
 adjacency(){const ids=SAVANNA_FIGURES_V174.map(f=>figureByImageV96(f.image).id);state.meta.figureEquipment.yusha=[ids[0],null,ids[1],ids[2]];const gap=adjacentPairsV174(figureEquipmentFor('yusha'));state.meta.figureEquipment.yusha=ids;const pairs=adjacentPairsV174(ids),fx=figureEffectsFor('yusha'),base=figureEffectsBaseV174('yusha');const hand=[...ids,figureByImageV96('eventfig/02.png').id],rows=pieceFightersV133(hand,[],'player'),original=pieceFightersBaseV174(hand,[],'player');return {gap,pairs:pairs.map(p=>[p.id,p.left,p.right]),bonus:{spd:fx.stats.spd-base.stats.spd,evade:fx.evade-base.evade,stun:fx.statusResist.stun-base.statusResist.stun},hand,piece:rows.map((r,i)=>({id:r.id,hp:r.hp,atk:r.atk,def:r.def,spd:r.spd,base:original[i]}))};},
 detail(){openPlayerDetail('yusha');return {remaining:expToNextRequiredV159(90)-100,text:$('#playerDetailBody').innerText};},
 async scene(kind='race'){eventRunV174={difficulty:0,area:2};skippedV174=false;showScreen('adventure');await openStoryScene('grassland',2,'default',['pink','denden','desert']);await savannaEntranceV174(kind);},
 async combat(){const base={damageAlly,aoeHit,bossNormal,enemySkillImageCutinV134,checkSpecialRevives},hits=[];damageAlly=async(a,p,t,s,e)=>{hits.push([a.id,p,t,e]);return 5;};aoeHit=async(p,t,e)=>hits.push(['all',p,t,e]);bossNormal=async()=>hits.push(['normal']);enemySkillImageCutinV134=async()=>{};checkSpecialRevives=async()=>{};try{const allies=state.party.slice(0,4).map(([id])=>buildAlly(player(id),80));const e=buildEnemyWave([{template:savannaTemplateV174('nagi',0),level:23}],4,'','')[0];state.battle={allies,mainIds:allies.map(a=>a.id),superIds:[],reserveIds:[],enemies:[e],enemy:e,turn:1,config:{},defeatedEnemies:[]};const before=initiativeSpeed({type:'enemy',enemyId:e.uid});await enemyAction(1,e.uid);const nagi={hits:[...hits],ratio:initiativeSpeed({type:'enemy',enemyId:e.uid})/before};await enemyAction(2,e.uid);const extra=hits.at(-1);hits.length=0;const metal=buildEnemyWave([{template:savannaTemplateV174('metal',1),level:50}],4,'','')[0];state.battle.enemies=[metal];state.battle.enemy=metal;const resistance=playerBaseElementResistanceV104(allies[0],'風');await enemyAction(1,metal.uid);const down=resistance-playerBaseElementResistanceV104(allies[0],'風');state.battle.turn=8;const restored=playerBaseElementResistanceV104(allies[0],'風');return {nagi,extra,down,restored,resistance};}finally{({damageAlly,aoeHit,bossNormal,enemySkillImageCutinV134,checkSpecialRevives}=base);}},
 async timing(){state.speed=5;state.battle={enemies:[],allies:[],config:{},turn:1};state.noticeQueue=[];const start=performance.now();await passiveCutin(player('pink'),'パッシブの表示時間');const ally=performance.now()-start;let seen=0;notice('敵パッシブ / ダメージ軽減が発動！','buff',760);await new Promise(resolve=>{const timer=setInterval(()=>{if($('#centerMessage').classList.contains('play'))seen++;if(!state.noticeBusy){clearInterval(timer);resolve();}},100);});return {ally,enemyFrames:seen};},
 locked(){state.test.enabled=false;const worlds=state.adventure.reportedWorlds;state.adventure.reportedWorlds=[];const before=savannaOpenV174(0);state.adventure.reportedWorlds=worlds;return before;},
 saved(){return {record:savannaRecordsV174(),figures:SAVANNA_FIGURES_V174.map(f=>figureOwned(figureByImageV96(f.image).id))};},
 async skip(){storyBusy=true;showScreen('adventure');await openStoryScene('grassland',0);await runStorySteps([['say','pink','テスト会話'],['joinSilent','riro'],['say','desert','次の会話']]);return {joined:state.party.some(x=>x[0]==='riro'),skipped:skippedV174};},
 async nextScope(){await closeStoryScene(false);await openStoryScene('grassland',1);return {skipped:skippedV174,visible:!skipBtnV174.hidden};},
 async battleSkip(){state.test.enabled=false;eventRunV174={difficulty:1,area:2};skippedV174=false;showScreen('battle');await allyStoryCutin('pink','合体イベントの会話');await allyStoryCutin('denden','次の会話');const skipped=skippedV174;eventRunV174=null;return skipped;},
 stub(){this.old={savannaSceneV174,startRound,allyStoryCutin,actionCutin,animateV157,fixedDelay,storyFlashBattle};savannaSceneV174=async()=>{};startRound=async()=>{};allyStoryCutin=async()=>{};actionCutin=async()=>{};animateV157=async()=>{};fixedDelay=async()=>{};storyFlashBattle=async()=>{};},
 async start(d){if(!this.old)this.stub();return startSavannaV174(d);},
 async win(){const b=state.battle;for(const e of b.enemies){e.hp=0;recordEnemyDefeat(e);}if(b.pendingWaveConfigs.length){await spawnNextEnemyWave();const fused=b.enemies[0];for(const e of b.enemies){e.hp=0;recordEnemyDefeat(e);}await finishBattle(true);return {fused:fused.name};}await finishBattle(true);return {};},
 async next(){eventRunV174.area++;return startSavannaAreaV174();},
 finish(){const repeat=rewardSavannaV174(),r={record:{...savannaRecordsV174()},repeat,owned:SAVANNA_FIGURES_V174.map(f=>figureOwned(figureByImageV96(f.image).id)),diamonds:state.meta.diamonds,coins:state.coins,xp:state.meta.exp.yusha};returnSavannaV174();return r;},
 guard(d){return savannaOpenV174(d);},
 restore(){if(this.old){({savannaSceneV174,startRound,allyStoryCutin,actionCutin,animateV157,fixedDelay,storyFlashBattle}=this.old);this.old=null;}},
 read(){return {area:eventRunV174?.area,enemies:state.battle?.enemies.map(e=>e.name),skip:!skipBtnV174.hidden};}
};`;
(async()=>{const {browser,page,errors}=await open(injection);try{
 await page.waitForFunction(()=>window.__mobV174Runtime);await page.evaluate(()=>test174.seed());await page.screenshot({path:path.join(output,'quests.png')});
 const assets=await page.evaluate(()=>test174.assets());for(const a of assets)assert(a&&fs.existsSync(path.join(root,a)),'Missing asset '+a);
 const audit=await page.evaluate(()=>test174.audit());assert.equal(audit.figs.length,4);for(const d of audit.waves){assert.equal(d[0].length,3);assert.equal(d[1].length,2);assert(d[2].every(e=>e.preempt));assert.equal(d[3][1].maxHp,300);assert.equal(d[3][1].cut,.9);}assert.equal(audit.waves[2][2][0].level,86);
 const adjacency=await page.evaluate(()=>test174.adjacency());assert.equal(adjacency.gap.length,1);assert.equal(adjacency.pairs.length,3);assert.equal(adjacency.bonus.spd,15);assert(Math.abs(adjacency.bonus.evade-.03)<1e-8);assert(Math.abs(adjacency.bonus.stun-.3)<1e-8);
 // Two edges at B stack +120% ATK and three grassland auras add +30%.
 assert.equal(adjacency.piece[1].atk,Math.round(adjacency.piece[1].base.atk*2.5));assert.equal(adjacency.piece[4].def,Math.round(adjacency.piece[4].base.def*1.4));
 const detail=await page.evaluate(()=>test174.detail());assert(detail.text.includes(detail.remaining.toLocaleString('ja-JP')));await page.screenshot({path:path.join(output,'status.png')});await page.evaluate(()=>document.querySelector('#playerDetailOverlay').hidden=true);
 const skip=page.evaluate(()=>test174.skip());await page.locator('#storySkipV174').click();const skipped=await skip;assert(skipped.joined&&skipped.skipped);const next=await page.evaluate(()=>test174.nextScope());assert(next.visible&&!next.skipped);await page.evaluate(()=>test174.close());
 console.log('PASS assets, authored enemy stats, adjacency edge stacking, next EXP, Area skip preserves joining');
 for(const d of [0,1,2]){assert(await page.evaluate(d=>test174.start(d),d));for(let area=0;area<4;area++){const r=await page.evaluate(()=>test174.win());if(area===2)assert.equal(r.fused,'モブナギサバンナ');if(area<3)await page.evaluate(()=>test174.next());}const r=await page.evaluate(()=>test174.finish());assert.equal(r.repeat,null);assert(r.record[d]);assert.equal(await page.evaluate(d=>test174.guard(d),d),false);assert(r.xp>100);if(d===2){assert.deepEqual(r.owned,[1,1,1,1]);assert.equal(r.diamonds,90);assert(r.coins>=65100);}}
 console.log('PASS all 12 Areas, fusion, rewards exactly once, no replay after clear');
 await page.evaluate(()=>test174.restore());const combat=await page.evaluate(()=>test174.combat());assert.equal(combat.nagi.hits.length,4);assert.equal(combat.nagi.hits[0][0],'all');assert.equal(combat.nagi.ratio,1.1);assert.equal(combat.extra[0],'normal');assert(Math.abs(combat.down-.2)<1e-8);assert.equal(combat.restored,combat.resistance);
 const timing=await page.evaluate(()=>test174.timing());assert(timing.ally>=1650);assert(timing.enemyFrames>=20);console.log('PASS actual skill routing, timed wind debuff, SPD increase, readable passives at 5x');
 await page.evaluate(()=>test174.scene('race'));await page.screenshot({path:path.join(output,'savanna.png')});await page.evaluate(()=>test174.close());const battleSkip=page.evaluate(()=>test174.battleSkip());await page.locator('#storySkipV174').click();assert(await battleSkip);assert.equal(await page.evaluate(()=>test174.locked()),false);assert.deepEqual(errors,[]);
 await page.reload();await page.waitForFunction(()=>window.__mobV174Runtime);const saved=await page.evaluate(()=>test174.saved());assert.deepEqual(saved.record,{'0':true,'1':true,'2':true});assert.deepEqual(saved.figures,[1,1,1,1]);
 console.log('PASS browser scenes without runtime errors');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
