const assert=require('node:assert/strict'),{open}=require('./story-v172-harness.cjs'),catalog=require('../js/figure-catalog-v218.json');
const injection=`window.fig227={catalog:()=>CATALOG_V218.figures.map(row=>{const f=figureByImageV96(row.image);return{image:f.image,tags:f.tags,adjacencyTags:f.adjacencyTags};}),parse:id=>parseFigureEffectText(ADJACENCY_TAGS_V174[id].equipment),run:()=>{
state.meta.figureEquipment={};state.meta.subFiguresV218={};state.meta.figureShelfV218=[];state.meta.figures={};state.meta.figureMigrationV218=true;
const fs=FIGURES.filter(f=>f.adjacencyTags?.includes('48')).slice(0,3);fs.forEach(f=>state.meta.figures[f.id]=1);state.meta.figureEquipment.pink=fs.map(f=>f.id);const equipped=figureEffectsFor('pink'),pairs=adjacentPairsV174(fs.map(f=>f.id)).filter(p=>p.id==='48');
const tagText=ADJACENCY_TAGS_V174['48'].equipment;ADJACENCY_TAGS_V174['48'].equipment='';const baseline=figureEffectsFor('pink').normalFollowV227||0;ADJACENCY_TAGS_V174['48'].equipment=tagText;const a=buildAlly(player('pink'),30),e=buildEnemyFromTemplate(trainingEnemyCatalog()[0],30);a.figureEffects=emptyFigureEffects();a.figureEffects.enemyEvadeDownV227=.2;e.evasion=.3;state.battle={allies:[a],enemies:[e],enemy:e,mainIds:[a.id],targetEnemyId:e.uid,weaponAttackContext:{},queue:[],queuePos:0,turn:1};
const hit=playerAttackHitChance(a,e);a.figureEffects.normalFollowV227=.05;const follow=weaponFollowupSpec(a,'normalFollowup'),magic=weaponFollowupSpec(a,'magicFollowup');a.soulPointsV220=0;a.figureEffects.soulGainV227=1;gainSoulV220(a,1);const soul=a.soulPointsV220;
const saved=figureEffectsFor;figureEffectsFor=()=>({ ...emptyFigureEffects(),magPercentV227:.05});const boosted=weaponStatsForEquipment(player('pink'),30,null).mag;figureEffectsFor=()=>emptyFigureEffects();const base=weaponStatsForEquipment(player('pink'),30,null).mag;figureEffectsFor=saved;
const merged=mergeFigureEffects(parseFigureEffectText(ADJACENCY_TAGS_V174['48'].equipment),parseFigureEffectText(ADJACENCY_TAGS_V174['48'].equipment));
return{pairs:pairs.length,equipped:equipped.normalFollowV227-baseline,tag:ADJACENCY_TAGS_V174['48'],hit,evasion:e.evasion,follow,magic,soul,boosted,base,merged:merged.normalFollowV227};}};`;
(async()=>{const x=await open(injection);try{const{page,errors}=x;assert.deepEqual(await page.evaluate(()=>fig227.catalog()),catalog.figures.map(f=>({image:f.image,tags:f.tags,adjacencyTags:f.image.startsWith('spbossfig/')?[]:f.adjacencyTags})));
const parses=await page.evaluate(()=>Object.fromEntries(['06','14','23','26','28','42','44','45','47','48'].map(id=>[id,fig227.parse(id)])));
assert.equal(parses['06'].enemyEvadeDownV227,.1);assert.equal(parses['06'].evade,0);assert.equal(parses['42'].enemyEvadeDownV227,.2);assert.equal(parses['23'].elementCrit['水'],.05);assert.equal(parses['23'].crit,0);assert.equal(parses['26'].passiveChanceV218,.05);assert.equal(parses['28'].statusResist.confuse,.2);assert.equal(parses['44'].magPercentV227,.05);assert.equal(parses['44'].stats.mag,0);assert.equal(parses['45'].crit,.03);assert.equal(parses['45'].ultimateCritV227,.03);assert.equal(parses['47'].soulGainV227,1);assert.equal(parses['48'].normalFollowV227,.05);
const r=await page.evaluate(()=>fig227.run());assert.equal(r.pairs,2);assert(Math.abs(r.equipped-.1)<1e-9);assert.equal(r.tag.name,'疾風の狩人');assert.deepEqual(r.tag.stats,{atk:.5,spd:.5});assert(r.tag.auraTag);assert.equal(r.tag.aura,.15);assert(Math.abs(r.hit-.9)<1e-9);assert.equal(r.evasion,.3);assert(Math.abs(r.follow.chance-.05)<1e-9);assert.equal(r.magic.chance,0);assert.equal(r.soul,2);assert.equal(r.boosted,Math.round(r.base*1.05));assert.equal(r.merged,.1);assert.deepEqual(errors,[]);console.log('v227 PASS: 318 catalogue identities/tags, 48th adjacency stacking, conditional effects, hit/followup/SOUL/MAG combat integration');
}finally{await x.browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
