const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{open,root}=require('./story-v172-harness.cjs');
const injection=`
window.macaronTest={
 setup(){state.party=['yusha','pink','jessie','denden','nyoro','money','nekoku'].map(id=>[id,95]);state.training.party=state.party.map(r=>[...r]);state.meta.openingCompleted=true;state.meta.trainingPlayed=true;state.meta.seenMemosV236=Object.fromEntries(MEMOS_V236.map(m=>[m.id,true]));state.test.enabled=false;state.meta.storyEventsV179={};confirmStoryChallengeV179=async()=>true;startRound=()=>{};fixedDelay=delay=async()=>{};actionCutin=async()=>{};},
 locks(){const base=worldCleared;worldCleared=()=>false;const before=[0,1,2].map(d=>openV179('macaron',d));worldCleared=id=>id==='magma';const first=[0,1,2].map(d=>openV179('macaron',d));recordsV179('macaron')[0]=true;const hard=[0,1,2].map(d=>openV179('macaron',d));recordsV179('macaron')[1]=true;const last=[0,1,2].map(d=>openV179('macaron',d));state.meta.storyEventsV179={};worldCleared=base;return{before,first,hard,last};},
 menu(){worldCleared=()=>true;eventViewV163='story';selectedStoryV179=null;renderEventQuestsV163();$('#trainingFeaturePopup').hidden=false;showScreen('training');},
 fast(){window.sceneLog=[];macaronSceneV247=async phase=>{sceneLog.push([eventRunV174.difficulty,eventRunV174.area,phase]);return phase==='pre'&&eventRunV174.area===1&&window.quizCorrect;};},
 async start(d,correct){window.quizCorrect=correct;await startV179('macaron',d);return state.battle.allies.map(a=>a.id);},
 snap(){return{area:eventRunV174?.area,finished:state.battle?.finished,record:recordsV179('macaron'),enemies:state.battle?.enemies.map(e=>({kind:e.macaronV247,level:e.level,actions:e.actionCount,min:e.v144ActionMin,max:e.v144ActionMax,cut:e.damageReduction,size:enemySizeClass(e),image:e.image}))};},
 async win(){for(const e of state.battle.enemies){e.hp=0;recordEnemyDefeat(e);}await handleEnemyWaveClear();},
 rewards(){return{coins:state.coins,diamonds:state.meta.diamonds||0,figures:[63,64].map(n=>figureOwned(figureByImageV96('eventfig/'+n+'.png').id)),medal:medalOwned('event-macaron-medal')};},
 repeat:()=>rewardV179(),
 medal:()=>weaponStatBonus({main:null,sub:null,medals:['event-macaron-medal']}),

};`;
(async()=>{const x=await open(injection);try{const {page,errors}=x;await page.evaluate(()=>macaronTest.setup());assert.deepEqual(errors,[]);assert.deepEqual(await page.evaluate(()=>macaronTest.locks()),{before:[false,false,false],first:[true,false,false],hard:[false,true,false],last:[false,false,true]});const medal=await page.evaluate(()=>macaronTest.medal());assert.equal(medal.atk,10);
await page.evaluate(()=>macaronTest.menu());await page.locator('[data-story247="macaron"]').click();assert.equal(await page.locator('[data-v179-start^="macaron:"]').count(),1);fs.mkdirSync(path.join(root,'artifacts/macaron-v247'),{recursive:true});await page.screenshot({path:path.join(root,'artifacts/macaron-v247/menu.png')});await page.evaluate(()=>macaronTest.fast());
for(let d=0;d<3;d++){const correct=d!==1,before=await page.evaluate(()=>macaronTest.rewards()),party=await page.evaluate(([d,c])=>macaronTest.start(d,c),[d,correct]);assert.deepEqual(party,['denden','money','nyoro','nekoku']);let battles=0;
for(let area=0;area<4;area++){if(area===1&&correct){assert.equal((await page.evaluate(()=>macaronTest.snap())).area,1);}else{const snap=await page.evaluate(()=>macaronTest.snap());assert.equal(snap.area,area);assert.equal(snap.enemies.length,area<2?3:1);for(const e of snap.enemies){assert.equal(e.actions,area<2?2:3);assert.equal(e.size,'normal');assert.equal(e.level,(area<2?[60,75,95]:area===2?[63,79,97]:[67,82,99])[d]);}await page.evaluate(()=>macaronTest.win());battles++;}await page.locator('[data-v179-next]').waitFor({state:'visible'});if(area===3){assert.equal(await page.evaluate(()=>macaronTest.repeat()),null);assert.match(await page.locator('.event-result-v163').innerText(),/QUEST CLEAR/);}await page.locator('[data-v179-next]').click();if(area<3&&!(area===0&&correct))await page.waitForFunction(()=>!macaronTest.snap().finished);}
assert.equal(battles,correct?3:4);const after=await page.evaluate(()=>macaronTest.rewards());assert.equal(after.diamonds-before.diamonds,[10,50,100][d]);assert.ok(after.coins-before.coins>=[5000,10000,50000][d]);}
const reward=await page.evaluate(()=>macaronTest.rewards());assert.deepEqual(reward.figures,[1,1]);assert.equal(reward.medal,1);
assert.deepEqual(errors,[]);console.log('PASS event: unlocks, three difficulties, both quiz branches, party, levels, rewards, medal');}finally{await x.browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});