const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{open,root}=require('./story-v172-harness.cjs');
const injection=`
window.mintTest={
 setup(){state.party=['yusha','pink','jessie','denden','nyoro','money'].map(id=>[id,95]);state.training.party=state.party.map(r=>[...r]);state.meta.openingCompleted=true;state.meta.trainingPlayed=true;state.meta.seenMemosV236=Object.fromEntries(MEMOS_V236.map(m=>[m.id,true]));state.test.enabled=false;state.meta.storyEventsV179={};confirmStoryChallengeV179=async()=>true;startRound=()=>{};fixedDelay=delay=async()=>{};actionCutin=async()=>{};},
 locks(){const base=worldCleared;worldCleared=()=>false;const before=[0,1,2].map(d=>openV179('mint',d));worldCleared=id=>id==='tribe';const first=[0,1,2].map(d=>openV179('mint',d));recordsV179('mint')[0]=true;const hard=[0,1,2].map(d=>openV179('mint',d));recordsV179('mint')[1]=true;const last=[0,1,2].map(d=>openV179('mint',d));state.meta.storyEventsV179={};worldCleared=base;return{before,first,hard,last};},
 menu(){worldCleared=()=>true;eventViewV163='story';selectedStoryV179=null;renderEventQuestsV163();$('#trainingFeaturePopup').hidden=false;showScreen('training');},
 fast(){window.sceneLog=[];mintSceneV237=async phase=>{sceneLog.push([eventRunV174.difficulty,eventRunV174.area,phase]);return phase==='pre'&&eventRunV174.area===1&&window.quizCorrect;};},
 async start(d,correct){window.quizCorrect=correct;await startV179('mint',d);return state.battle.allies.map(a=>a.id);},
 snap(){return{area:eventRunV174?.area,finished:state.battle?.finished,record:recordsV179('mint'),enemies:state.battle?.enemies.map(e=>({kind:e.mintV237,level:e.level,actions:e.actionCount,min:e.v144ActionMin,max:e.v144ActionMax,cut:e.damageReduction,size:enemySizeClass(e),image:e.image}))};},
 async win(){for(const e of state.battle.enemies){e.hp=0;recordEnemyDefeat(e);}await handleEnemyWaveClear();},
 rewards(){return{coins:state.coins,diamonds:state.meta.diamonds||0,figures:[61,62].map(n=>figureOwned(figureByImageV96('eventfig/'+n+'.png').id)),medal:medalOwned('event-mint-medal')};},
 repeat:()=>rewardV179(),
 medal:()=>weaponStatBonus({main:null,sub:null,medals:['event-mint-medal']}),
 async combat(){
  eventRunV174=null;await beginBattle({mode:'training',party:state.party,enemyConfigs:mintWaveV237(3,2)});const b=state.battle,e=b.enemies[0],a=b.allies[0],oldRandom=Math.random,out={hits:[],talk:[],cuts:[]};for(const u of b.allies){u.hp=u.maxHp=100000;u.dead=false;}
  const oldHit=damageAlly,oldTalk=enemyStoryCutin,oldReaction=reactionV177,oldLunge=beginEnemyLunge,oldEnd=endEnemyLunge;
  damageAlly=async(t,p,type,s,el)=>{out.hits.push({id:t.id,p,type,el,aoe:enemyAoeV163});return 10;};enemyStoryCutin=async(e,t)=>out.talk.push(t);reactionV177=async()=>{};beginEnemyLunge=async()=>{};endEnemyLunge=()=>{};actionCutin=async text=>out.cuts.push(text);Math.random=()=>.1;
  for(let i=1;i<=3;i++)await enemyAction(i,e.uid);out.debuff=b.allies.map(t=>[t.atkDebuff||0,t.atkDebuffTurns||0]);out.actions=e.actionCount;out.talkCount=out.talk.length;
  e.status.paralyze=1;const before=out.hits.length;await enemyAction(1,e.uid);out.paralyzed=out.hits.length===before&&e.status.paralyze===1;e.status.paralyze=0;
  damageAlly=oldHit;enemyStoryCutin=oldTalk;reactionV177=oldReaction;beginEnemyLunge=oldLunge;endEnemyLunge=oldEnd;Math.random=oldRandom;return out;
 },
 async magic(){
  await beginBattle({mode:'training',party:state.party,enemyConfigs:mintWaveV237(3,0)});const b=state.battle,a=b.allies[0],e=b.enemies[0];e.hp=e.maxHp=1000000;a.mpNow=a.maxMp=1000;const skill={...MOB_DATA.magicCatalog.find(s=>s.element==='水'&&s.tier==='medium'),cost:11};
  const out={};skillSprite=async()=>{};actionCutin=async()=>{};reactionV177=async()=>{};preloadAssets=async()=>{};passiveChance=()=>false;const old=applyEnemyDamageTo,oldRandom=Math.random;let hits=0;applyEnemyDamageTo=function(...args){hits++;return{value:10,miss:false};};Math.random=()=>.99;
  const figures=[61,62].map(n=>figureByImageV96('eventfig/'+n+'.png'));a.figureEffects={...emptyFigureEffects(),mintMagicFollowV237:0};a.equipment={main:null,sub:null,medals:[]};a.figureEquipment=[];
  await applySoulTextV218(figures[0],a,b.allies,b.enemies,figures[0].soul.text);await performMagic(a,skill);out.self={hits,mp:a.mpNow,other:b.allies[1].mintGuaranteedTurnV237};hits=0;b.turn++;a.mpNow=1000;await performMagic(a,skill);out.expired={hits,mp:a.mpNow};
  await applySoulTextV218(figures[1],a,b.allies,b.enemies,figures[1].soul.text);out.party=b.allies.every(t=>t.mintGuaranteedTurnV237===b.turn);b.turn++;a.mpNow=1000;hits=0;a.equipment.medals=['event-mint-medal'];Math.random=()=>.02;await performMagic(a,skill);out.medal={hits,mp:a.mpNow};
  a.equipment.medals=[];a.figureEffects.mintMagicFollowV237=.04;a.mpNow=1000;hits=0;Math.random=()=>.039;await performMagic(a,skill);out.figure={hits,mp:a.mpNow};
  a.mpNow=0;hits=0;const failed=await performMagic(a,skill);out.noMp={hits,failed};
  const own=[{hp:100,maxHp:100,def:100},{hp:50,maxHp:100,def:100}];await applySoulTextV218(figures[1],own[0],own,[],figures[1].pieceSoul[10].text,true);out.piece=own;out.traits=figures.map(f=>parseFigureEffectText(f.traitText).mintMagicFollowV237);out.costs=figures.map(f=>f.soul.cost);out.names=figures.map(f=>f.pieceSoul[10].name);
  applyEnemyDamageTo=old;Math.random=oldRandom;return out;
 }
};`;
(async()=>{const x=await open(injection);try{const {page,errors}=x;await page.evaluate(()=>mintTest.setup());assert.deepEqual(errors,[]);assert.deepEqual(await page.evaluate(()=>mintTest.locks()),{before:[false,false,false],first:[true,false,false],hard:[false,true,false],last:[false,false,true]});const medal=await page.evaluate(()=>mintTest.medal());assert.equal(medal.mag,5);assert.equal(medal.def,3);
await page.evaluate(()=>mintTest.menu());await page.locator('[data-story237="mint"]').click();assert.equal(await page.locator('[data-v179-start^="mint:"]').count(),1);fs.mkdirSync(path.join(root,'artifacts/mint-v237'),{recursive:true});await page.screenshot({path:path.join(root,'artifacts/mint-v237/menu.png')});await page.evaluate(()=>mintTest.fast());
for(let d=0;d<3;d++){const correct=d!==1,before=await page.evaluate(()=>mintTest.rewards()),party=await page.evaluate(([d,c])=>mintTest.start(d,c),[d,correct]);assert.deepEqual(party,['pink','jessie','denden','nyoro']);let battles=0;
for(let area=0;area<4;area++){if(area===1&&correct){assert.equal((await page.evaluate(()=>mintTest.snap())).area,1);}else{const snap=await page.evaluate(()=>mintTest.snap());assert.equal(snap.area,area);assert.equal(snap.enemies.length,area===0?3:area===1?4:1);for(const e of snap.enemies){assert.equal(e.actions,area<2?2:3);assert.equal(e.size,'normal');assert.equal(e.level,(area<2?[45,55,90]:area===2?[50,70,95]:[52,72,95])[d]);}await page.evaluate(()=>mintTest.win());battles++;}await page.locator('[data-v179-next]').waitFor({state:'visible'});if(area===3){assert.equal(await page.evaluate(()=>mintTest.repeat()),null);assert.match(await page.locator('.event-result-v163').innerText(),/QUEST CLEAR/);}await page.locator('[data-v179-next]').click();if(area<3&&!(area===0&&correct))await page.waitForFunction(()=>!mintTest.snap().finished);}
assert.equal(battles,correct?3:4);const after=await page.evaluate(()=>mintTest.rewards());assert.equal(after.diamonds-before.diamonds,[100,200,300][d]);assert.ok(after.coins-before.coins>=[5000,10000,50000][d]);}
const reward=await page.evaluate(()=>mintTest.rewards());assert.deepEqual(reward.figures,[1,1]);assert.equal(reward.medal,1);
const combat=await page.evaluate(()=>mintTest.combat());assert.equal(combat.actions,3);assert.equal(combat.talkCount,1);assert.ok(combat.hits.every(h=>h.type==='magic'&&h.el==='水'));assert.ok(combat.hits.filter(h=>h.aoe).length>=4);assert.ok(combat.debuff.some(x=>x[0]===.2&&x[1]>=2&&x[1]<=3));assert.ok(combat.paralyzed);
const magic=await page.evaluate(()=>mintTest.magic());for(const k of ['self','medal','figure']){assert.equal(magic[k].hits,2,JSON.stringify(magic));assert.equal(magic[k].mp,989);}assert.deepEqual(magic.expired,{hits:1,mp:989});assert.ok(magic.party);assert.deepEqual(magic.noMp,{hits:0,failed:false});assert.deepEqual(magic.traits,[.02,.04]);assert.deepEqual(magic.costs,[7,8]);assert.deepEqual(magic.names,['ミントベール','ミントベールMAX']);assert.equal(magic.piece[0].maxHp,115);assert.equal(magic.piece[0].def,105);
await page.reload();assert.deepEqual((await page.evaluate(()=>mintTest.rewards())).figures,[1,1]);assert.deepEqual(errors,[]);console.log('PASS: unlocks, 3 difficulties, both quiz branches, party restrictions, rewards/persistence, enemy actions, ailments, free nonrecursive magic repeats, turn expiry and piece skills');
}finally{await x.browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
