const assert=require('node:assert/strict'),fs=require('node:fs'),{open}=require('./story-v172-harness.cjs');
const injection=`const actualRound239=startRound;window.n239={lines:[],actions:[],setup(){state.party=['yusha','pink','jessie','money'].map(id=>[id,100]);state.meta.openingCompleted=true;state.meta.trainingPlayed=true;state.meta.seenMemosV236=Object.fromEntries(MEMOS_V236.map(m=>[m.id,true]));state.test.enabled=false;fixedDelay=delay=async()=>{};nmAnimV239=async()=>{};nmSoundV239=()=>{};storyAdvanceWait=async()=>{const b=$('.nm-bubble-v239',nmStageV239);if(b&&!b.hidden){const r=b.getBoundingClientRect();n239.lines.push({name:$('b',b).textContent,text:$('p',b).textContent,x:r.x,y:r.y,w:r.width,h:r.height});if(n239.captureText&&$('p',b).textContent.includes(n239.captureText))await capture239('last-line');}};},
assets(){return Object.keys(NM_NAMES_V239).filter(k=>!['unknown','narration'].includes(k)).map(k=>[k,nmInfoV239(k).image]);},
async scene(phase,area){eventRunV174={storyV179:'nightmare',area,difficulty:0};await nmSceneV239(phase);return{busy:storyBusy,stages:document.querySelectorAll('.nm-stage-v239').length};},
cast(){return [...document.querySelectorAll('.nm-actor-v239')].filter(e=>!e.hidden).map(e=>{const r=e.getBoundingClientRect(),img=e.querySelector('img');return{id:e.dataset.nmActor,x:r.x,y:r.y,w:r.width,h:r.height,loaded:img.complete&&img.naturalWidth>0,opacity:getComputedStyle(e).opacity};});},
async battle(area){eventRunV174=null;startRound=()=>{};actionCutin=async()=>{};await beginBattle({mode:'training',nightmareV239:true,party:state.party,enemyConfigs:nmWaveV239(area)});return state.battle.enemies.map(e=>({name:e.name,id:e.id,kind:e.nightmareV239,level:e.level,actions:e.actionCount,min:e.v144ActionMin,max:e.v144ActionMax,cut:e.damageReduction,hp:e.maxHp,def:e.def}));},
async help(){const b=state.battle,e=b.enemies[0],def=e.def;let messages=0;enemyStoryCutin=allyStoryCutin=async()=>{messages++;};actionCutin=async()=>{};processQueue=async()=>{};applyRoundDots=async()=>{};checkBattleHpDialogue=async()=>{};b.turn=3;await actualRound239();const first=e.def;await actualRound239();return{def,first,second:e.def,cut:e.damageReduction,messages,count:b.queue.filter(q=>q.enemyId===e.uid).length};},
locks(){state.meta.gameCleared=false;const locked=openV179('nightmare');state.meta.gameCleared=true;const open=openV179('nightmare');return{locked,open};},
menu(){state.meta.gameCleared=true;eventViewV163='story';selectedStoryV179=null;renderEventQuestsV163();$('#trainingFeaturePopup').hidden=false;showScreen('training');},
fast(){nmSceneV239=async()=>{};confirmStoryChallengeV179=async()=>true;startRound=()=>{};actionCutin=async()=>{};eventRunV174=null;},
async start(){await startV179('nightmare');},async win(){const b=state.battle;for(const e of b.enemies){e.hp=0;recordEnemyDefeat(e);}await handleEnemyWaveClear();},status(){return{finished:state.battle?.finished,enemy:state.battle?.enemies?.[0]?.nightmareV239,area:eventRunV174?.area,party:state.battle?.allies.map(a=>a.id),clear:recordsV179('nightmare').clear,coins:state.coins,diamonds:state.meta.diamonds};}
};const nmActionTest=nmActionV239;nmActionV239=async function(op){await nmActionTest(op);n239.actions.push(op);if(n239.captureOps?.includes(op)){const cast=n239.cast();await capture239(op,cast);}};`;
(async()=>{const x=await open(injection);try{const{page,errors}=x;fs.mkdirSync('artifacts/nightmare-v239',{recursive:true});const casts=[];await page.exposeFunction('capture239',async(name,cast)=>{if(cast)casts.push({name,cast});await page.screenshot({path:'artifacts/nightmare-v239/'+page.viewportSize().height+'-'+name+'.png'});});await page.evaluate(()=>n239.setup());const assets=await page.evaluate(()=>n239.assets());for(const [id,src]of assets)assert(fs.existsSync(src),id+': '+src);console.log('assets',assets);assert.deepEqual(await page.evaluate(()=>n239.locks()),{locked:false,open:true});
for(const viewport of [{width:390,height:844},{width:360,height:640}]){await page.setViewportSize(viewport);await page.evaluate(()=>{n239.captureOps=['threeArmies','sealedEnding','farewell'];n239.captureText='いずれ共に戦おう';});for(const phase of ['pre','post'])for(let area=0;area<4;area++){const result=await page.evaluate(([p,a])=>n239.scene(p,a),[phase,area]);assert.deepEqual(result,{busy:false,stages:0});}const lines=await page.evaluate(()=>n239.lines.splice(0));assert(lines.length>100);assert(lines.every(l=>l.x>=-1&&l.x+l.w<=viewport.width+1&&l.y>=0&&l.y+l.h<=viewport.height),JSON.stringify(lines.filter(l=>l.x<0||l.x+l.w>viewport.width)));assert(lines.every(l=>!l.text.includes('巨大文字')&&!l.text.includes('表示してください')));}
for(const group of casts)for(const c of group.cast){assert(c.loaded&&c.opacity==='1');assert(c.x>=-1&&c.y>=0&&c.w>0&&c.h>0,JSON.stringify(c));}
for(let area=1;area<4;area++){const rows=await page.evaluate(a=>n239.battle(a),area);console.log('battle',area,rows);assert.deepEqual(rows.map(e=>e.level),area===1?[90,93,90]:area===2?[93]:[96]);assert.deepEqual(rows.map(e=>e.actions),area===1?[2,3,2]:area===2?[3]:[4]);if(area===2){assert.equal(rows[0].cut,.15);assert.equal(rows[0].max,4);}}
const help=await page.evaluate(()=>n239.help());assert.equal(help.first,Math.round(help.def*.4));assert.equal(help.first,help.second);assert.equal(help.cut,0);assert.equal(help.messages,2);assert.equal(help.count,4);
await page.evaluate(()=>n239.menu());await page.locator('[data-nightmare-v239]').click();assert(await page.locator('[data-nm-start]').isEnabled());await page.screenshot({path:'artifacts/nightmare-v239/menu.png'});await page.evaluate(()=>n239.fast());await page.evaluate(()=>n239.start());for(let a=0;a<4;a++){if(a){await page.waitForFunction(a=>!n239.status().finished&&n239.status().enemy===['','cockpit','gladi','yami'][a],a);const status=await page.evaluate(()=>n239.status());assert.equal(status.area,a);assert.deepEqual(status.party,['yusha','pink','jessie','money']);await page.evaluate(()=>n239.win());}await page.locator('[data-nm-next]').waitFor();await page.locator('[data-nm-next]').click();if(a<3)await page.waitForFunction(a=>n239.status().area===a+1,a);}assert((await page.evaluate(()=>n239.status())).clear);await page.reload();assert((await page.evaluate(()=>n239.status())).clear);assert.deepEqual(errors,[]);console.log('PASS all scenes/actors, two phone layouts, unlock/menu, three battles and four-action queue, turn-three weakness, complete event and persisted clear');}finally{await x.browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
