const assert=require('node:assert/strict'),{open}=require('./story-v172-harness.cjs');
const injection=`window.portraits228={setup:()=>{state.party=['yusha','pink','desert','denden','money','jessie'].map(id=>[id,30]);state.training.party=state.party.map(x=>[...x]);state.meta.openingCompleted=true;state.meta.trainingPlayed=true;state.party.forEach(([id])=>equipmentFor(id));},equip:tab=>{equipmentTab=tab;equipmentPlayerId='pink';renderEquipment();showScreen('equipment');},tavern:()=>{showScreen('tavern');showTavernParty();},split:()=>{chooseLilithSplit();},book:()=>{bookPartyFormationV92();},snapshot:()=>({party:state.party,equip:equipmentPlayerId,swap:state.tavernSwapIndex,equipment:state.meta.equipment}),close:()=>closePlayerDetail()};`;
(async()=>{const x=await open(injection);try{const{page,errors}=x;await page.evaluate(()=>portraits228.setup());
async function inspect(selector){const before=await page.evaluate(()=>portraits228.snapshot());await page.locator(selector).first().click();await page.locator('#playerDetailOverlay').waitFor({state:'visible'});assert((await page.locator('#playerDetailBody').innerText()).includes('パッシブ'));assert((await page.locator('#playerDetailBody').innerText()).includes('HP'));assert.deepEqual(await page.evaluate(()=>portraits228.snapshot()),before);const top=await page.locator('#playerDetailCloseBtn').evaluate(e=>{const r=e.getBoundingClientRect();return document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)===e;});assert(top);await page.locator('#playerDetailCloseBtn').click();await page.locator('#playerDetailOverlay').waitFor({state:'hidden'});}
for(const tab of ['equip','armor','figures','subfigures']){await page.evaluate(t=>portraits228.equip(t),tab);await inspect('#equipmentContent .equipment-party-strip img');await page.locator('#equipmentContent .equipment-party-strip button').first().locator('b').first().click();assert.equal((await page.evaluate(()=>portraits228.snapshot())).equip,'yusha');}
await page.evaluate(()=>portraits228.equip('equip'));await inspect('.equipment-selected>img');
await page.evaluate(()=>portraits228.tavern());await inspect('[data-tavern-swap="0"] img');await page.locator('[data-tavern-swap="0"]>b').click();await inspect('[data-tavern-swap="1"] img');await page.locator('[data-tavern-swap="1"]>b').click();assert.equal((await page.evaluate(()=>portraits228.snapshot())).party[0][0],'pink');
await page.evaluate(()=>portraits228.split());const member=page.locator('[data-v181-split-member]').first(),cls=await member.getAttribute('class');await inspect('[data-v181-split-member] img');assert.equal(await member.getAttribute('class'),cls);await member.locator('b').first().click();assert.notEqual(await member.getAttribute('class'),cls);await page.locator('[data-v181-split-member] img').first().focus();await page.keyboard.press('Enter');await page.locator('#playerDetailOverlay').waitFor({state:'visible'});await page.screenshot({path:'tests/v228-character-detail.png'});await page.locator('#playerDetailCloseBtn').click();
await page.evaluate(()=>{document.querySelector('#lilithSplitOverlay').hidden=true;portraits228.book();});await inspect('.book-formation-grid-v92 img');await page.locator('.book-formation-grid-v92>button').nth(0).locator('b').first().click();await page.locator('.book-formation-grid-v92>button').nth(1).locator('b').first().click();assert.equal((await page.evaluate(()=>portraits228.snapshot())).party[0][0],'yusha');assert.deepEqual(errors,[]);console.log('v228 PASS: weapon/armor/main/sub figures, tavern and book swaps, split movement, keyboard, detail foreground and unchanged selection while inspecting');
}finally{await x.browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
