const assert=require('node:assert/strict'),{open}=require('./story-v172-harness.cjs');
const injection=`
const delay222=fixedDelay,animate222=animateV157;fixedDelay=ms=>delay222(Math.min(ms,8));animateV157=(el,frames,ms)=>animate222(el,frames,Math.min(ms,8));HTMLMediaElement.prototype.play=()=>Promise.reject(new Error('autoplay test'));
window.record222={lines:[],jumps:[],posters:[],messages:[],done:false};
const line222=endingLineV222;endingLineV222=async function(stage,id,text,style,auto){record222.lines.push([id,text,style||'']);const timer=!auto?setInterval(()=>stage.click(),40):null;try{return await line222(stage,id,text,style,auto);}finally{clearInterval(timer);}};
const jump222=endingJumpV222;endingJumpV222=async function(stage,id,times){record222.jumps.push([id,times]);return jump222(stage,id,times);};
loadEndingFrameV217=async n=>{record222.posters.push(n);const img=new Image();img.src='poster/01.png';return img;};
const cap222=endingCaptionV157;endingCaptionV157=async function(text){record222.messages.push(text);await cap222(text);const p=document.querySelector('.ending-caption-v222 p');if(p&&p.getBoundingClientRect().width>innerWidth-35)throw Error('Caption overflow: '+text);};
window.test222={run:()=>{finalEndingV89Final().then(()=>record222.done=true).catch(e=>{record222.error=e.stack;record222.done=true;});},preview:()=>{const stage=document.createElement('section');stage.className='ending-stage-v222 black';stage.innerHTML='<div class="ending-cast-v222"></div><div class="ending-bubble-v222"></div>';document.body.append(stage);endingCastV222(stage,['pink','yusha',...MOB_DATA.players.map(p=>p.id).filter(id=>!['pink','yusha'].includes(id))],true);line222(stage,'pink','それまでお達者で！','farewell',true);},gacha:async()=>{const p=GACHA_PATTERNS_V220.find(x=>x.id==='gold');await pinkGachaV220(p);},report:()=>{state.adventure.awaitingReport={worldId:'demonCastle2'};renderAdventure();return document.querySelector('#areaDescription').textContent;},spec:()=>({dialogue:ENDING_DIALOGUE_V222,pink:ENDING_PINK_V222,messages:ENDING_MESSAGES_V222}),state:()=>({clear:state.meta.gameCleared,pending:state.meta.pendingFinalEndingV217,screen:document.querySelector('.screen.active')?.id})};
`;
(async()=>{const x=await open(injection);try{const {page,errors}=x;await page.evaluate(()=>test222.run());await page.waitForFunction(()=>record222.done,{},{timeout:45000});const record=await page.evaluate(()=>record222),spec=await page.evaluate(()=>test222.spec());assert.equal(record.error,undefined);assert.deepEqual(record.lines.slice(0,20).map(x=>x.slice(0,2)),spec.dialogue.map(x=>x.slice(0,2)));assert.deepEqual(record.lines.slice(20,28).map(x=>x[1]),spec.pink);assert.equal(record.lines[28][1],'それまでお達者で！');assert(record.jumps.some(x=>x[0]==='king'&&x[1]===3));assert(record.jumps.some(x=>x[0]===null&&x[1]===3));assert.deepEqual(record.messages,[...spec.messages,'CB Memory']);assert(record.posters.includes(31));assert.equal(await page.locator('.ending-stage-v222,.ending-v157,.ending-caption-v157').count(),0);assert.deepEqual(await page.evaluate(()=>test222.state()),{clear:true,pending:undefined,screen:'titleScreen'});assert.equal(await page.evaluate(()=>test222.report()),'');await page.evaluate(()=>test222.preview());await page.screenshot({path:'tests/v222-ending-party.png',animations:'disabled'});await page.evaluate(()=>document.querySelector('.ending-stage-v222').remove());await page.evaluate(()=>test222.gacha());assert.equal(await page.locator('.chest-lid-v222').count(),1);await page.screenshot({path:'tests/v222-gacha.png',animations:'disabled'});assert.deepEqual(errors,[]);console.log('v222 PASS: exact separated dialogue/newlines, king/Pink/group jumps, all final messages fit mobile, 31 posters, cleanup/title/unlocks, report copy hidden, 3D chest');}finally{await x.browser.close();}})().then(()=>process.exit(0),e=>{console.error(e);process.exit(1)});
