const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');const {open}=require('./story-v172-harness.cjs');const out=path.join(os.tmpdir(),'mob-v177');fs.mkdirSync(out,{recursive:true});
const injection=`window.p177={
 seed(){state.adventure=defaultAdventure();state.party=['yusha','pink','desert','denden','money'].map(id=>[id,40]);state.meta.trainingPlayed=true;state.meta.openingCompleted=true;state.test.enabled=true;},
 effects(){const ids=HOT_FIGURES_V177.map(f=>f.id);state.meta.figureEquipment.yusha=ids;const fx=figureEffectsFor('yusha'),base=figureEffectsBaseV174('yusha'),extra=FIGURES.find(f=>f.tags.includes('56')&&!ids.includes(f.id));const hand=[...ids,extra.id],rows=pieceFightersV133(hand,[],'player'),original=pieceFightersBaseV174(hand,[],'player');addMedal('hot-fight');const eq=equipmentFor('yusha');eq.main=eq.sub=null;eq.medals=['hot-fight',null,null];return {fx,individual:HOT_FIGURES_V177.map(f=>parseFigureEffectText(f.traitText)),delta:{atk:fx.stats.atk-base.stats.atk,cut:fx.damageCut-base.damageCut,burn:fx.statusResist.burn-base.statusResist.burn},stats:weaponStatBonus(eq),trait:weaponTraitList({equipment:eq},'lowHpDamageCut'),rows:rows.map((r,i)=>({atk:r.atk,def:r.def,spd:r.spd,hp:r.hp,base:original[i]}))};},
 result(){void showGachaResultV115({id:'01'},[{f:figureByImageV96('eventfig/22.png'),converted:false}]);},
 async visual(){showScreen('battle');state.battle={enemies:[],allies:[],config:{},turn:1};const old=waitRealV100;waitRealV100=()=>new Promise(r=>this.release=r);try{await reactionV177(trainingEnemyTemplate('boss-gidora'),'ドラゴンソウル','ダメージ軽減+10%・全属性耐性+10%',{gidora:true});}finally{waitRealV100=old;}},
 async scene(a,phase){eventRunV174={hotV177:true,difficulty:0,area:a};skipScopeV174='';skippedV174=false;await savannaSceneV174(phase);return !storyBusy;},
 async entrance(){eventRunV174={hotV177:true,difficulty:0,area:3};skippedV174=false;skipScopeV174='';showScreen('adventure');await openStoryScene('grassland',3,'default',['pink','denden','money','desert']);$('#adventureStageTitle').textContent='熱血スライム';await hotEntranceV177('passion');return $('#storyGuest').innerText;}
};`;
(async()=>{const {browser,page,errors}=await open(injection);try{await page.waitForFunction(()=>window.__mobV177Runtime);await page.evaluate(()=>p177.seed());const e=await page.evaluate(()=>p177.effects());assert.equal(e.fx.stats.def,11);assert.equal(e.individual[1].physicalCut,.08);assert(Object.values(e.individual[0].resist).every(v=>v===.03));assert.deepEqual(e.delta,{atk:5,cut:.01,burn:.4});assert.equal(e.stats.atk,5);assert.equal(e.stats.def,5);assert.equal(e.trait[0].threshold,.5);for(let i=0;i<3;i++){const r=e.rows[i];assert.equal(r.atk,Math.round(r.base.atk*(i<2?1.55:1.15)));assert.equal(r.def,Math.round(r.base.def*(i<2?1.45:1.15)));assert.equal(r.spd,Math.round(r.base.spd*1.15));}
 await page.evaluate(()=>p177.result());await page.locator('[data-gacha-result-figure-v102]').click();const detail=page.locator('.gacha-figure-detail-v177');assert.equal(await detail.locator('p').first().evaluate(e=>getComputedStyle(e).color),'rgb(37, 27, 16)');await page.screenshot({path:path.join(out,'gacha-detail.png')});await page.reload();await page.waitForFunction(()=>window.__mobV177Runtime);await page.evaluate(()=>p177.seed());
 const visual=page.evaluate(()=>p177.visual());await page.locator('.reaction-v177.gidora').waitFor();await page.screenshot({path:path.join(out,'passive.png')});await page.evaluate(()=>p177.release());await visual;
 for(let a=0;a<4;a++)for(const phase of ['pre','post']){const scene=page.evaluate(([a,p])=>p177.scene(a,p),[a,phase]);await page.locator('#storySkipV174').click();assert(await scene);}
 await page.reload();await page.waitForFunction(()=>window.__mobV177Runtime);await page.evaluate(()=>p177.seed());await page.evaluate(()=>p177.entrance());await page.screenshot({path:path.join(out,'passion.png')});assert.deepEqual(errors,[]);console.log('PASS authored figures, equipment/adjacency/medal, fire aura, actual tapped gacha detail, 8 story scenes and Area skip, boss entrance');
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1;});
