const fs=require('node:fs'),assert=require('node:assert/strict'),{open}=require('./story-v172-harness.cjs');
const d=require('../js/rush-v254.json'),prior=JSON.parse(fs.readFileSync('artifacts/rush-v255/backup/js_rush-v254.json'));
assert.deepEqual(d.medals,prior.medals);assert.deepEqual(d.enemies,prior.enemies);assert.deepEqual(d.narrator,prior.narrator);for(const q of d.quests){const old=prior.quests.find(x=>x.id===q.id);assert.deepEqual(q.clearCoins,old.clearCoins);assert.deepEqual(q.areas,old.areas);}
const legacy=fs.readFileSync('tests/rush-v253.cjs','utf8').split('const injection=`')[1].split('`;')[0];
const injection=legacy+`window.test255={init(){rushTest.setup();rushTest.unlock();state.party=['yusha','pink','desert','denden','money','nyoro','jessie'].map(id=>[id,110]);state.meta.monsterRushV254={};state.coins=1000;fixedDelay=async()=>{};preloadAssets=preloadAssetsSafe=async()=>{};startBattleLoaded=async c=>beginBattle(c);rushFxV255=async()=>{};saveParty();saveMeta();},team(id){const q=rushQuestV252(id);return [q.requiredCharacter,...state.party.map(p=>p[0]).filter(id=>id!==q.requiredCharacter)].slice(0,4).map(id=>state.party.find(p=>p[0]===id));},start(id){return startRushV252(id,this.team(id));},invalid(type){let team=test255.team(RUSH_DATA_V252.quests[0].id);if(type==='three')team.pop();if(type==='five')team.push(state.party.find(p=>!team.some(t=>t[0]===p[0])));if(type==='missing')team=state.party.filter(p=>p[0]!=='pink').slice(0,4);if(type==='duplicate')team[1]=team[0];return startRushV252(RUSH_DATA_V252.quests[0].id,team);},best:()=>rushBestV254(RUSH_DATA_V252.quests[0]),tier(t){rushDifficultyV254=t;},gates:()=>[0,1,2].map(t=>RUSH_DATA_V252.quests.every(q=>rushTierOpenV254(q,t))),party:()=>JSON.stringify(state.party),battle:()=>({allies:state.battle.allies.length,super:state.battle.superIds.length,reserve:state.battle.reserveIds.length,levels:state.battle.enemies.map(e=>e.level)}),medal:id=>clone(weaponById(id)),old(){state.meta.monsterRushV252=Object.fromEntries(RUSH_DATA_V252.quests.slice(0,14).map(q=>[q.id,true]));state.meta.monsterRushV254={};return rushTierCountV255(0);},oldUpper(){state.meta.monsterRushV252={};state.meta.monsterRushV254={[RUSH_DATA_V252.quests[0].id]:{cleared:[true,true,true]}};syncRushMedalsV254();saveMeta();return {best:rushBestV254(RUSH_DATA_V252.quests[0]),gates:this.gates()};}};`;
(async()=>{const x=await open(injection),rows=[];try{const p=x.page;await p.evaluate(()=>test255.init());const party=await p.evaluate(()=>test255.party());assert.deepEqual(await p.evaluate(()=>test255.gates()),[true,false,false]);
for(const type of ['three','five','missing','duplicate']){assert.equal(await p.evaluate(type=>{return test255.invalid(type);},type),false);}
let coins=1000;for(let t=0;t<3;t++){await p.evaluate(t=>test255.tier(t),t);for(const q of d.quests){await p.evaluate(id=>test255.start(id),q.id);const b=await p.evaluate(()=>test255.battle());assert.equal(b.allies,4);assert.equal(b.super,0);assert.equal(b.reserve,0);assert.ok(b.levels.every(l=>l>=[1,50,80][t]));await p.evaluate(()=>rushTest.lose());await p.locator('[data-rush-next]').click();await p.waitForFunction(()=>!rushTest.snap().run);assert.equal((await p.evaluate(()=>rushTest.snap())).coins,coins);
await p.evaluate(id=>test255.start(id),q.id);await p.evaluate(()=>rushTest.back());await p.waitForFunction(()=>!rushTest.snap().run);assert.equal((await p.evaluate(()=>rushTest.snap())).coins,coins);
for(let replay=0;replay<2;replay++){await p.evaluate(id=>test255.start(id),q.id);for(let a=0;a<q.areas.length;a++){for(const wave of q.areas[a].waves)await p.evaluate(()=>rushTest.win());await p.locator('[data-rush-next]').waitFor({state:'visible'});if(a===q.areas.length-1){coins+=q.clearCoins[t];assert.equal((await p.evaluate(()=>rushTest.snap())).coins,coins);assert.equal(await p.evaluate(()=>rushTest.reward()),false);assert.equal((await p.evaluate(()=>rushTest.snap())).medals[q.reward],1);}await p.locator('[data-rush-next]').click();if(a<q.areas.length-1)await p.waitForFunction(()=>rushTest.snap().finished===false);else await p.waitForFunction(()=>!rushTest.snap().run);}}
assert.deepEqual((await p.evaluate(id=>test255.medal(id),q.reward)).stats,d.medals.find(m=>m.id===q.reward).tiers[t].stats);assert.equal(await p.evaluate(()=>test255.party()),party);rows.push({quest:q.id,tier:t,coins:q.clearCoins[t],fourOnly:true});if(t<2&&q!==d.quests.at(-1))assert.equal((await p.evaluate(()=>test255.gates()))[t+1],false);console.log(t,q.id);}
if(t<2)assert.equal((await p.evaluate(()=>test255.gates()))[t+1],true);}
await p.reload({waitUntil:'load'});assert.equal((await p.evaluate(()=>rushTest.snap())).coins,coins);assert.equal(await p.evaluate(()=>rushTest.reward()),false);assert.equal(await p.evaluate(()=>test255.old()),14);assert.equal((await p.evaluate(()=>test255.gates()))[1],false);const old=await p.evaluate(()=>test255.oldUpper());assert.equal(old.best,2);assert.equal(old.gates[1],false);assert.equal(old.gates[2],false);await p.reload({waitUntil:'load'});assert.equal(await p.evaluate(()=>test255.best()),2);assert.deepEqual(x.errors,[]);fs.writeFileSync('artifacts/rush-v255/lifecycle-results.json',JSON.stringify({rows,invalidParties:4,partyUnchanged:true,legacyPreserved:true},null,2));console.log('PASS 90 tiers, global gates, four-only, defeats/aborts/replays/coins/medals, old saves');
}finally{await x.browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
