const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict'),{open,root}=require('./story-v172-harness.cjs'),d=require('../js/rush-v254.json');
require('../js/rush-validation-v254.js')(d,{assetExists:p=>fs.existsSync(path.join(root,p))});
const raw=fs.readFileSync(path.join(__dirname,'rush-v253.cjs'),'utf8').match(/const injection=`([\s\S]*?)`;/)[1];
const injection=vm.runInNewContext('`'+raw+'`')+`
window.test254={init(){rushTest.setup();rushTest.unlock();state.meta.monsterRushV254={};fixedDelay=delay=async()=>{};preloadAssets=preloadAssetsSafe=async()=>{};startBattleLoaded=async config=>beginBattle(config);},tier(t){rushDifficultyV254=t;},gate:id=>{worldCleared=()=>true;return rushTierOpenV254(rushQuestV252(id));},clear:id=>rushTierV254(rushQuestV252(id)),ranks:()=>state.meta.monsterRushV254,medal:id=>({stats:weaponById(id).stats,traits:weaponById(id).traits}),
 audit(){return RUSH_DATA_V252.quests.flatMap(q=>RUSH_DATA_V252.difficulties.flatMap((diff,t)=>{eventRunV174={tier:t};const rows=q.areas.flatMap((a,i)=>rushWavesV252(q,i).flatMap(w=>{if(w.length<2||w.length>3)throw Error('Wave cap');return w.map(r=>{const e=buildEnemyFromTemplate(r.template,r.level),base=rushEnemyBaseV254(r.template,r.level),p=r.template.rushPassive;if(!e.rushPassive||Math.abs(e.elementResist[p.element]-Math.min(.75,(base.elementResist?.[p.element]||0)+p.value))>.00001)throw Error('Passive not applied');if(e.actionCount<1||e.actionCount>e.v144ActionMax||(!enemySpecialSpec(e)&&e.story179Kind!=='phoenix'))throw Error('AI missing');return {quest:q.id,tier:t,id:e.id,level:e.level,actions:e.actionCount,min:e.v144ActionMin,max:e.v144ActionMax,passive:e.rushPassive};});}));eventRunV174=null;return rows;}));},
 equipment(id){const eq={main:null,sub:null,medals:[id,null,null]},a={equipment:eq};return {bonus:weaponStatBonus(eq),traits:weaponTraitEntries(a).length,removed:weaponStatBonus({main:null,sub:null,medals:[]}),removedTraits:weaponTraitEntries({main:null,sub:null,medals:[]}).length};},
 oldSave(){state.meta.monsterRushV254={};state.meta.monsterRushV252=Object.fromEntries(RUSH_DATA_V252.quests.slice(0,14).map(q=>[q.id,true]));state.meta.medals=Object.fromEntries(RUSH_DATA_V252.medals.slice(0,14).map(m=>[m.id,1]));saveMeta();},save:()=>saveMeta()};`;
(async()=>{const x=await open(injection),out={stages:[]};try{const p=x.page;await p.evaluate(()=>test254.init());out.enemies=await p.evaluate(()=>test254.audit());
 for(const q of d.quests){console.log(q.id);for(let tier=0;tier<3;tier++){await p.evaluate(t=>test254.tier(t),tier);assert.equal(await p.evaluate(id=>test254.gate(id),q.id),true);await p.evaluate(id=>rushTest.start(id),q.id);await p.evaluate(()=>rushTest.lose());await p.locator('[data-rush-next]').click();await p.evaluate(id=>rushTest.start(id),q.id);await p.evaluate(()=>rushTest.back());assert.equal((await p.evaluate(()=>rushTest.snap())).run,null);await p.evaluate(id=>rushTest.start(id),q.id);
  for(let a=0;a<q.areas.length;a++){for(const wave of q.areas[a].waves){const snap=await p.evaluate(()=>rushTest.snap());assert.ok(snap.enemies.length>=2&&snap.enemies.length<=3);await p.evaluate(()=>rushTest.win());}await p.locator('[data-rush-next]').waitFor({state:'visible'});if(a===q.areas.length-1){assert.equal((await p.evaluate(()=>rushTest.snap())).medals[q.reward],1);assert.equal(await p.evaluate(()=>rushTest.reward()),false);}await p.locator('[data-rush-next]').click();if(a<q.areas.length-1)await p.waitForFunction(()=>rushTest.snap().finished===false);}
  const medal=await p.evaluate(id=>test254.medal(id),q.reward);assert.deepEqual(medal.stats,q?d.medals.find(m=>m.id===q.reward).tiers[tier].stats:{});out.stages.push({id:q.id,tier,medal});
 }
 // Replaying a cleared tier must not duplicate or downgrade the medal.
 await p.evaluate(()=>test254.tier(0));await p.evaluate(id=>rushTest.start(id),q.id);for(let a=0;a<q.areas.length;a++){for(const w of q.areas[a].waves)await p.evaluate(()=>rushTest.win());await p.locator('[data-rush-next]').click();if(a<q.areas.length-1)await p.waitForFunction(()=>rushTest.snap().finished===false);}assert.equal((await p.evaluate(()=>rushTest.snap())).medals[q.reward],1);assert.deepEqual((await p.evaluate(id=>test254.medal(id),q.reward)).stats,d.medals.find(m=>m.id===q.reward).tiers[2].stats);
 const eq=await p.evaluate(id=>test254.equipment(id),q.reward);assert.equal(eq.removedTraits,0);assert.ok(Object.values(eq.removed).every(v=>v===0));
 }
 await p.evaluate(()=>test254.save());await p.reload({waitUntil:'load'});for(const m of d.medals)assert.deepEqual((await p.evaluate(id=>test254.medal(id),m.id)).stats,m.tiers[2].stats);await p.evaluate(()=>test254.oldSave());await p.reload({waitUntil:'load'});for(const q of d.quests.slice(0,14)){await p.evaluate(()=>test254.tier(0));assert.equal(await p.evaluate(id=>test254.clear(id),q.id),true);await p.evaluate(()=>test254.tier(1));assert.equal(await p.evaluate(id=>test254.gate(id),q.id),true);}
 assert.deepEqual(x.errors,[]);fs.writeFileSync(path.join(root,'artifacts/rush-v254/lifecycle-results.json'),JSON.stringify(out,null,2));console.log('PASS 90 difficulty clears, 30 replays, 2-3 enemies, passives, AI, defeat/abort/retry, upgrades, unequip, reload and v253 save migration');
 }finally{await x.browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
