const assert=require('node:assert/strict'),fs=require('fs'),{open,root}=require('./story-v172-harness.cjs');
const injection=`window.skills259={data(){return {tech:MOB_DATA.techniqueCatalog,magic:MOB_DATA.magicCatalog,players:MOB_DATA.players};},async setup(){state.party=['yusha','pink','desert','money'].map(id=>[id,99]);state.meta.seenMemosV236=Object.fromEntries(MEMOS_V236.map(m=>[m.id,true]));startRound=processQueue=async()=>{};await beginBattle({mode:'training',party:state.party,enemyConfigs:[{id:'dc2-lilith',level:90,qty:3}]});state.speed=8;actionCutin=async()=>{};notice=()=>{};for(const e of state.battle.enemies){e.hp=e.maxHp=999999;e.evasion=0;}},async use(id,mp=999){const a=state.battle.allies[0],s=MOB_DATA.techniqueCatalog.find(s=>s.id===id),before=state.battle.enemies.map(e=>e.hp);a.mpNow=mp;const random=Math.random;Math.random=()=>.5;try{const result=await performSpecial(a,s);return {result,mp:a.mpNow,hits:state.battle.enemies.map((e,i)=>before[i]-e.hp),buff:a.soulEffectsV218,effective:{atk:effective('atk',a),def:effective('def',a),res:effective('res',a),mag:effective('mag',a),spd:effective('spd',a)},turn:state.battle.turn};}finally{Math.random=random;}},async expiry(){const a=state.battle.allies[0],v=[];v.push(soulEffectValueV218(a,'atk'));await endRound();v.push(soulEffectValueV218(a,'atk'));await endRound();v.push(soulEffectValueV218(a,'atk'));return v;},async spell(){const a=state.battle.allies[0],e=state.battle.enemies[0],s=MOB_DATA.magicCatalog.find(s=>s.id==='honomagma');window.targets259=[];const observer=new MutationObserver(ms=>ms.forEach(m=>m.addedNodes.forEach(n=>{if(n.dataset?.skill)targets259.push({id:n.dataset.skill,target:n.dataset.target});})));observer.observe(document.querySelector('#battleFxLayer'),{childList:true});await inEnemyFxV251(e,{special:s.name},false,()=>damageAlly(a,.01,'magic',false,'火'));observer.disconnect();return targets259;},learn(id,lv){return availableTechniqueSkillsV104({...player(id),level:lv}).map(s=>s.id);},play(id,target='enemy'){state.speed=1;const s=[...MOB_DATA.techniqueCatalog,...MOB_DATA.magicCatalog].find(s=>s.id===id);window.visualJob259=skillSprite(s.frames,target,s.mode);},atlas:SKILL_ATLASES_V259,style:atlasFrameStyleV251,load:loadAtlasV251};`;
(async()=>{const x=await open(injection);try{const p=x.page,d=await p.evaluate(()=>skills259.data());const added=d.tech.filter(t=>t.cartoonV259&&!t.exclusiveV260);assert.equal(added.length,33);assert.equal(d.tech.filter(t=>t.selfBuffV259).length,16);assert.equal(d.tech.filter(t=>t.cartoonV259&&!t.exclusiveV260&&t.target==='all').length,8);
 for(const s of added)for(const file of s.frames)assert(fs.existsSync(root+'/'+file),file);
 for(const p of d.players){assert.equal(new Set(p.learnset.technique.map(r=>r.id)).size,p.learnset.technique.length);for(const r of p.learnset.technique)assert(d.tech.some(s=>s.id===r.id),r.id);}
 const costs={honomagma:36,nepumachun:36,torumaden:38,goremagardy:38,hokumawing:36,neomanipool:40,miramazone:40,anomaun:32,'neo-meteor-power':64};for(const [id,cost]of Object.entries(costs))assert.equal(d.magic.find(s=>s.id===id).cost,cost);
 for(const pl of d.players)for(const row of pl.learnset.magic)if(costs[row.id])assert(row.level>=60);
 for(const pl of d.players)for(const r of pl.learnset.technique.filter(r=>added.some(s=>s.id===r.id))){assert(!(await p.evaluate(([id,lv])=>skills259.learn(id,lv),[pl.id,r.level-1])).includes(r.id));assert((await p.evaluate(([id,lv])=>skills259.learn(id,lv),[pl.id,r.level])).includes(r.id));}
 await p.evaluate(()=>skills259.setup());let r=await p.evaluate(()=>skills259.use('karamin',0));assert.equal(r.result,false);assert(r.hits.every(n=>n===0));assert(!r.buff?.length);
 for(const s of added){r=await p.evaluate(id=>skills259.use(id),s.id);assert.notEqual(r.result,false,s.name);assert.equal(r.mp,999-s.cost,s.name);if(s.target==='all')assert(r.hits.every(v=>v>0),s.name);else assert.equal(r.hits.filter(v=>v>0).length,1,s.name);if(s.selfBuffV259){const buff=r.buff.find(b=>b.sourceV259==='food259:'+s.selfBuffV259.family);assert(buff);assert.equal(buff.until-r.turn,2);assert(buff.value>=s.selfBuffV259.value);}}
 r=await p.evaluate(()=>skills259.use('toku-karamin'));assert.equal(r.buff.filter(b=>b.sourceV259==='food259:karamin').length,1);assert.equal(r.buff.find(b=>b.sourceV259==='food259:karamin').value,.15);
 const expiry=await p.evaluate(()=>skills259.expiry());assert.deepEqual(expiry,[.15,.15,0]);const targets=await p.evaluate(()=>skills259.spell());assert.deepEqual(targets,[{id:'honomagma',target:'yusha'}]);
 for(const [id,target]of [['karamin','enemy'],['toku-karamin','enemy'],['naminoslide','enemy-all'],['honomagma','pink']]){await p.evaluate(([id,t])=>skills259.play(id,t),[id,target]);await p.waitForSelector('.cartoon-skill-v259');await p.screenshot({path:'artifacts/skills-v259/'+id+'.png'});await p.evaluate(()=>visualJob259);assert.equal(await p.locator('.cartoon-skill-v259').count(),0);}
 assert.deepEqual(x.errors,[]);console.log('PASS 33 new skills, all learnsets, MP, targets, two-turn buffs, refresh, expiry, enemy fire on player, animation cleanup');
}finally{await x.browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});

