const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{open,root}=require('./story-v172-harness.cjs');
const seed=fs.readFileSync(path.join(__dirname,'story-v173.cjs'),'utf8').match(/const injection=`([\s\S]*?)`;/)[1].replaceAll('STORY_V173.events','STORY_V231.events');
const injection=seed+`
window.test231={
 traits(){const a=buildAlly(player('desert'),70),e=buildEnemyWave([{id:'n2-tiger',level:60}],4,'','')[0],random=Math.random;a.equipment={main:null,sub:null,medals:[]};a.figureEffects={};state.battle={enemies:[e],allies:[a],mainIds:[a.id],superIds:[],reserveIds:[],turn:1,queue:[{type:'ally',id:a.id}],queuePos:0,config:{},weaponAttackContext:{normal:false,element:'闇'}};Math.random=()=>TEMP_BALANCE.critRate+.025;try{const plain=calcDamage(a,'magic',1,0,e).crit;a.equipment.medals=['story-neomaster-medal'];const neon=calcDamage(a,'magic',1,0,e).crit,physical=calcDamage(a,'physical',1,0,e).crit;a.equipment.medals=['story-mira-medal'];const dark=calcDamage(a,'magic',1,0,e).crit;state.battle.weaponAttackContext.element='火';const fire=calcDamage(a,'magic',1,0,e).crit;a.equipment.medals=['story-dragon-medal'];return {plain,neon,physical,dark,fire,fireResist:weaponResistance(a,'火'),darkResist:weaponResistance(a,'闇'),waterResist:weaponResistance(a,'水')};}finally{Math.random=random;}},
 passive(){const a=buildAlly(player('desert'),70),e=buildEnemyWave([{id:'n2-tiger',level:60}],4,'','')[0];e.hp=e.maxHp=10000;e.evasion=0;e.statusResist.poison=1;state.battle={enemies:[e],allies:[a],mainIds:[a.id],superIds:[],reserveIds:[],turn:1,queue:[{type:'ally',id:a.id}],queuePos:0,config:{},weaponAttackContext:{normal:false,element:'闇'}};const saved={calcDamage,renderBattle,notice},calls=[];renderBattle=notice=()=>{};calcDamage=(a,type,power)=>{calls.push({power,type,normal:state.battle.weaponAttackContext.normal});return {value:1,crit:calls.length===1,miss:false};};try{applyEnemyDamageTo(a,e,1,'magic',0,false);return {calls,poison:e.status.poison,context:state.battle.weaponAttackContext};}finally{({calcDamage,renderBattle,notice}=saved);}},
 async scenes(){const spoken=await test173.walk();return {...spoken,counts:Object.fromEntries(Object.entries(STORY_MEDALS_V231).map(([w,m])=>[w,medalOwned(m.id)])),home:STORY_EVENTS['post:desert2:3'].forceHome,leftovers:document.querySelectorAll('.story-fx-v231,.transfer-orb-v231,.absorb-ghost-v231,.four-title-v231,.story-medal-v231').length};},
 async combat(){
 const saved={enemyStoryCutin,allyStoryCutin,actionCutin,renderBattle,fx,floatNumber,fixedDelay,startRound,storyDarkBattlePulse,sceneFxV231};
 enemyStoryCutin=allyStoryCutin=actionCutin=fixedDelay=storyDarkBattlePulse=sceneFxV231=async()=>{};renderBattle=fx=floatNumber=()=>{};startRound=()=>{};
 try{
  const neo=buildEnemyWave([{id:'boss-neomaster',level:70}],4,'','')[0],before={atk:neo.atk,hp:neo.maxHp,cut:neo.damageReduction||0};
  state.battle={mode:'adventure',config:{},enemies:[neo],allies:[],turn:1,storyHpFlags:{}};
  neo.hp=Math.floor(neo.maxHp*.69);await checkBattleHpDialogue();await checkBattleHpDialogue();const seventy={atk:neo.atk,hp:neo.maxHp,cut:neo.damageReduction,crit:neo.critBonusV231};neo.hp=Math.floor(neo.maxHp*.39);await checkBattleHpDialogue();await checkBattleHpDialogue();const forty={atk:neo.atk,cut:neo.damageReduction,actions:neo.actionCount,special:neo.specialChanceV231};
  const guards=buildEnemyWave([{id:'d2-miraearth',level:70},{id:'d2-mirakarami',level:70}],4,'',''),base=guards.map(e=>({atk:e.atk,mag:e.mag,maxHp:e.maxHp,cut:e.damageReduction||0}));state.battle={mode:'adventure',config:{},enemies:guards,allies:[],turn:1,storyHpFlags:{}};guards.forEach(e=>e.hp=Math.floor(e.maxHp*.49));await checkBattleHpDialogue();await checkBattleHpDialogue();const boosted=guards.map(e=>({atk:e.atk,mag:e.mag,maxHp:e.maxHp,cut:e.damageReduction,atkBuff:e.atkBuff||0}));
  const waves=MOB_DATA.adventureWorlds.find(w=>w.id==='desert2').areas[2].nextWaves;
  state.battle.pendingWaveConfigs=[waves[0]];state.battle.bg='';state.battle.fallbackBg='';await spawnNextEnemyWave();const pair=state.battle.enemies.map(e=>({id:e.id,mag:e.mag,cut:e.damageReduction}));
  const allies=state.party.map(([id])=>({...buildAlly(player(id),65),hp:10}));allies.at(-1).hp=0;allies.at(-1).dead=true;Object.assign(state.battle,{allies,mainIds:allies.slice(0,4).map(a=>a.id),superIds:[],reserveIds:allies.slice(4).map(a=>a.id),pendingWaveConfigs:[waves[1]]});await spawnNextEnemyWave();
  const result={before,seventy,forty,base,boosted,pair,revived:state.battle.enemies.map(e=>({hp:e.hp,maxHp:e.maxHp,actions:e.actionCount})),allies:allies.map(a=>({hp:a.hp,maxHp:a.maxHp,dead:a.dead}))};
  state.battle.enemies=buildEnemyWave([{id:'boss-dragon2',level:70}],4,'','');state.battle.pendingWaveConfigs=[[{id:'boss-gidora',level:75}]];await spawnNextEnemyWave();result.dragonPhase=state.battle.enemies[0].id;
  state.battle.enemies=buildEnemyWave([{id:'boss-mira-d2',level:70}],4,'','');state.battle.pendingWaveConfigs=[[{id:'boss-mira2-d2',level:75}]];await spawnNextEnemyWave();result.miraPhase=state.battle.enemies[0].id;return result;
 }finally{({enemyStoryCutin,allyStoryCutin,actionCutin,renderBattle,fx,floatNumber,fixedDelay,startRound,storyDarkBattlePulse,sceneFxV231}=saved);}
 },
 async poison(){const a=buildAlly(player('desert'),70);a.mpNow=100;const enemies=buildEnemyWave([{id:'d2-miraearth',level:60},{id:'d2-mirakarami',level:60}],4,'','');state.battle={enemies,allies:[a],mainIds:[a.id],superIds:[],reserveIds:[],turn:1,config:{}};const saved={actionCutin,miraChargeFxV120,skillSprite,applyEnemyDamageTo,applyEnemyStatusTo,renderBattle,delay},hits=[],poisons=[];actionCutin=miraChargeFxV120=skillSprite=delay=async()=>{};renderBattle=()=>{};applyEnemyDamageTo=(actor,e,power,type)=>{hits.push([e.id,power,type,state.battle.weaponAttackContext.element]);return {value:1,miss:false};};applyEnemyStatusTo=(e,...args)=>poisons.push([e.id,...args]);try{await performMiraMobPoisonV120(a,poisonV231);return {hits,poisons,mp:a.mpNow,cost:v120MagicCost(a,poisonV231).cost,skill:poisonV231.name};}finally{({actionCutin,miraChargeFxV120,skillSprite,applyEnemyDamageTo,applyEnemyStatusTo,renderBattle,delay}=saved);}},
 medals(){const first=Object.fromEntries(Object.entries(STORY_MEDALS_V231).map(([w,m])=>[w,medalOwned(m.id)]));for(const w of Object.keys(STORY_MEDALS_V231))grantStoryMedalV231(w);return {first,after:Object.fromEntries(Object.entries(STORY_MEDALS_V231).map(([w,m])=>[w,medalOwned(m.id)])),stats:Object.fromEntries(Object.entries(STORY_MEDALS_V231).map(([w,m])=>[w,weaponStatBonus({main:null,sub:null,medals:[m.id]})]))};},
 async preview(){state.battle=null;showScreen('adventure');await openStoryScene('desert2',2);await entranceV231(FOUR_V231,'four');return FOUR_V231.map(id=>({id,image:storyActorInfo(id).image,visible:!!storyAnchor(id)&&getComputedStyle(storyAnchor(id)).visibility!=='hidden'}));}
};`;
(async()=>{const data=JSON.parse(fs.readFileSync(path.join(root,'js/story-v231.json'),'utf8'));assert.equal(Object.keys(data.events).length,26);const all=Object.values(data.events).flatMap(e=>e.steps);for(const s of all.filter(s=>s[0]==='say'))assert(!/※|メダルステータス|してください|召喚演出|HP30%|パッシブⅡ:/.test(s[2]),s[2]);const x=await open(injection);try{
 const {page,errors}=x;await page.evaluate(()=>test173.seed());assert.deepEqual(errors,[]);
 const scenes=await page.evaluate(()=>test231.scenes());assert(scenes.party.includes('riro'));assert(scenes.awakened);assert(scenes.home);assert.equal(scenes.leftovers,0);assert.deepEqual(scenes.counts,{neon2:1,magma2:1,desert2:1});console.log('PASS 26 scenes, directions, join, awakening, medals, cleanup');
 const b=await page.evaluate(()=>test231.combat());assert.equal(b.seventy.atk,Math.round(b.before.atk*1.1));assert.equal(b.seventy.hp,Math.round(b.before.hp*1.1));assert(Math.abs(b.seventy.cut-b.before.cut-.1)<1e-8);assert.equal(b.seventy.crit,.1);assert.equal(b.forty.atk,b.seventy.atk);assert(Math.abs(b.forty.cut-b.before.cut-.2)<1e-8);assert.equal(b.forty.actions,3);assert.equal(b.forty.special,.8);b.boosted.forEach((e,i)=>{assert.equal(e.atk,Math.round(b.base[i].atk*1.2));assert.equal(e.mag,Math.round(b.base[i].mag*1.2));assert.equal(e.atkBuff,0);assert(Math.abs(e.cut-b.base[i].cut-.15)<1e-8);});assert(b.pair.every(e=>e.cut>=.15));assert.equal(b.revived.length,4);assert(b.revived.every(e=>e.hp===Math.round(e.maxHp*.3)&&[1,2].includes(e.actions)));assert(b.allies.filter(a=>!a.dead).every(a=>a.hp===Math.min(a.maxHp,10+Math.round(a.maxHp*.3))));assert.equal(b.allies.at(-1).hp,0);console.log('PASS thresholds once, all-stat buffs, two waves, four-way revival and 30% party healing');
 assert.equal(b.dragonPhase,'boss-gidora');assert.equal(b.miraPhase,'boss-mira2-d2');const p=await page.evaluate(()=>test231.poison());assert.equal(p.hits.length,2);assert.equal(p.poisons.length,2);assert(p.hits.every(h=>h[3]==='闇'));assert.equal(p.mp,100-p.cost);
 const traits=await page.evaluate(()=>test231.traits());assert.deepEqual(traits,{plain:false,neon:true,physical:false,dark:true,fire:false,fireResist:.15,darkResist:.15,waterResist:0});const passive=await page.evaluate(()=>test231.passive());assert(passive.calls.some(c=>c.power===1.2&&c.type==='physical'&&c.normal));assert.equal(passive.poison,3);assert.deepEqual(passive.context,{normal:false,element:'闇'});
 const m=await page.evaluate(()=>test231.medals());assert.deepEqual(m.first,m.after);assert.equal(m.stats.neon2.mag,5);assert.equal(m.stats.neon2.res,5);assert.equal(m.stats.neon2.maxMp,20);assert.equal(m.stats.magma2.atk,5);assert.equal(m.stats.magma2.maxHp,20);assert.equal(m.stats.desert2.atk,8);assert.equal(m.stats.desert2.spd,8);
 const actors=await page.evaluate(()=>test231.preview());assert(actors.every(a=>a.visible));actors.forEach((a,i)=>assert(a.image.includes('enemy/'+(37+i)+'.png')));await page.screenshot({path:path.join(require('node:os').tmpdir(),'mob-story-v231.png')});await page.reload();const loaded=await page.evaluate(()=>test231.medals());assert.deepEqual(loaded.first,{neon2:1,magma2:1,desert2:1});assert.deepEqual(loaded.after,loaded.first);assert.deepEqual(errors,[]);console.log('PASS all-target dark poison, 120% critical follow-up/poison immunity bypass, medal traits and stats, reload/repeat-safe awards, dragon/Mira transformations, four actors/assets, no browser errors');
}finally{await x.browser.close();}})().then(()=>process.exit(0),e=>{console.error(e);process.exit(1)});
