const assert=require('node:assert/strict'),path=require('node:path'),os=require('node:os'),fs=require('node:fs');
const {open}=require('./story-v172-harness.cjs');const out=path.join(os.tmpdir(),'mob-quest-v175');fs.mkdirSync(out,{recursive:true});
const injection=`window.test175={
 seed(){state.party=['yusha','pink','desert','denden','money','nyoro','nekoku'].map(id=>[id,90]);state.adventure=defaultAdventure();state.adventure.reportedWorlds=['grassland','desert','rural'];state.meta.trainingPlayed=true;state.meta.openingCompleted=true;state.meta.storyEventsV174={savanna:{}};state.meta.storyEventSeenV175={};state.training.mode='event';state.test.enabled=false;showScreen('training');eventViewV163='story';renderTraining();$('#trainingFeaturePopup').hidden=false;},
 reveal(){state.meta.storyEventSeenV175.savanna=true;savannaRecordsV174()[0]=true;renderEventQuestsV163();},
 async passive(){showScreen('battle');state.battle={turn:1,enemies:[],allies:[],config:{}};const result=[];for(const turn of [1,1,2]){state.battle.turn=turn;const t=performance.now();await passiveCutin(player('desert'),'サバクノマモリビト！');result.push({ms:performance.now()-t,text:$('#passiveCutinText').textContent});}return result;},
 async ultimate(){const saved={ultimateCutin,playUltimatePostAnimation,playerAoeDamage,delay,renderBattle,notice,heal};const hits=[],heals=[];ultimateCutin=async()=>{};playUltimatePostAnimation=async()=>{};delay=async()=>{};renderBattle=()=>{};notice=()=>{};playerAoeDamage=async(a,power)=>{for(const e of livingEnemies()){e.hp-=10;hits.push(e.uid);}return 30;};heal=(a,n)=>{heals.push({id:a.id,n,max:a.maxHp});a.hp=Math.min(a.maxHp,a.hp+Math.round(n));return Math.round(n);};try{const allies=state.party.map(([id,lv])=>buildAlly(player(id),lv));for(const a of allies){a.hp=100;a.ultCooldowns=a.ults.map(()=>0);}allies.at(-1).dead=true;allies.at(-1).hp=0;const enemies=buildEnemyWave(savannaWaveV174(0,0),4,'','');state.battle={allies,enemies,mainIds:allies.slice(0,4).map(a=>a.id),superIds:[allies[4].id],reserveIds:allies.slice(5).map(a=>a.id),enemy:enemies[0],targetEnemyId:enemies[0].uid,config:{},turn:1};const a=allies[0],u=a.ults[3];await performUltimate(a,u);const count=heals.length;const rejected=await performUltimate(a,u);return {hits,heals,count,rejected,kind:u.kind,desc:u.desc,dead:allies.at(-1).hp,cooldown:a.ultCooldowns[3]};}finally{({ultimateCutin,playUltimatePostAnimation,playerAoeDamage,delay,renderBattle,notice,heal}=saved);}}
};`;
(async()=>{const {browser,page,errors}=await open(injection);try{
await page.waitForFunction(()=>window.__mobV175Runtime);await page.evaluate(()=>test175.seed());assert.equal(await page.locator('.event-silhouette-v175').count(),5);await page.screenshot({path:path.join(out,'silhouettes.png')});await page.evaluate(()=>test175.reveal());assert.equal(await page.locator('.event-silhouette-v175').count(),2);
const passive=page.evaluate(()=>test175.passive());await page.waitForFunction(()=>document.querySelector('#passiveCutin')?.hidden===false);await page.waitForTimeout(500);await page.screenshot({path:path.join(out,'passive.png')});const p=await passive;assert(p.every(x=>x.text.includes('サバクノマモリビト')&&x.text.includes('20%軽減')));assert(p[0].ms>=2100&&p[1].ms<1100&&p[2].ms>=2100);
const u=await page.evaluate(()=>test175.ultimate());assert.equal(u.kind,'lowHpBurstAoe');assert.equal(u.hits.length,3);assert.equal(u.count,6);assert.equal(u.heals.length,6);assert(u.heals.every(x=>Math.abs(x.n-x.max*.1)<1e-8));assert.equal(u.dead,0);assert(u.cooldown>0);assert.equal(u.rejected,false);assert.deepEqual(errors,[]);console.log('PASS silhouettes, simultaneous passive effect, repeat timing, hero AoE + roster healing, cooldown rejection');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
