const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');const {open}=require('./story-v172-harness.cjs');const out=path.join(os.tmpdir(),'mob-v178');fs.mkdirSync(out,{recursive:true});
const injection=`window.t178={
 seed(){state.adventure=defaultAdventure();state.party=['yusha','pink','desert','denden','money','nyoro','nekoku','tetsu','jessie','riro'].map(id=>[id,80]);state.meta.trainingPlayed=true;state.meta.openingCompleted=true;state.meta.moneyStoryAwayV157=false;state.test.enabled=false;state.battle={enemies:[],allies:[],config:{},turn:1};showScreen('battle');},
 async timing(){const actor={uid:'repeat-test',name:'モブギドラ',image:'boss/11.png'},result=[];state.speed=5;for(const name of ['ドラゴンソウル','ドラゴンソウル','別のパッシブ']){const t=performance.now();await reactionV177(actor,name,'攻撃を50%軽減し、反撃する',{gidora:true});result.push(performance.now()-t);}state.battle={enemies:[],allies:[],config:{}};const t=performance.now();await reactionV177(actor,'ドラゴンソウル','効果',{gidora:true});result.push(performance.now()-t);return result;},
 async card(){const old=waitRealV100;waitRealV100=()=>new Promise(r=>this.release=r);try{await reactionV177({name:'モブファイト',image:'spenemy/39.png'},'ファイトイッパツ！','次に受ける攻撃を50%軽減し、反撃する');}finally{waitRealV100=old;}},
 async walk(){const base={storySay,storySayRed,storySayBigV94,storyNarrate,storyAdvanceWait,startDemonAceStoryBattle,animateV157,fixedDelay,storyFlash,storyImpact},spoken=[],pages=[];storySay=async(id,text)=>spoken.push([id,text]);storySayRed=async(id,text)=>spoken.push([id,text,'red']);storySayBigV94=async(id,text)=>spoken.push([id,text,'big']);storyNarrate=async text=>spoken.push(['narrator',text]);storyAdvanceWait=async()=>{const p=$('.castle-history-caption-v178 p')||$('.castle-black-v178 p');if(p)pages.push(p.textContent);};startDemonAceStoryBattle=async()=>true;animateV157=async()=>{};fixedDelay=async()=>{};storyFlash=async()=>{};storyImpact=async()=>{};try{showScreen('adventure');await runDemonCastleArrivalStory();await closeStoryScene(false);for(const key of ['pre:demonCastle:0','post:demonCastle:0','pre:demonCastle:1','post:demonCastle:1','post:demonCastle:2']){const ev=STORY_EVENTS[key];await openStoryScene(ev.worldId,ev.area);await runStorySteps(ev.steps);await closeStoryScene(false);}await demonFinalPreV89Final();const away=state.meta.moneyStoryAwayV157;await closeStoryScene(false);await demonFinalPostV89Final();return {spoken,pages,away,restored:!state.meta.moneyStoryAwayV157,unlocked:state.meta.moneyFriendsUnlocked,record:state.meta.record7Obtained,dessert:HOT_STORY_V177[2].post[0][2]};}finally{({storySay,storySayRed,storySayBigV94,storyNarrate,storyAdvanceWait,startDemonAceStoryBattle,animateV157,fixedDelay,storyFlash,storyImpact}=base);}},
 async ultimate(){const base={ultimateCutin,playUltimatePostAnimation,transformationFxV158,notice,renderBattle},a=buildAlly(player('money'),80);a.ultCooldowns=a.ults.map(()=>0);state.meta.moneyFriendsUnlocked=true;state.battle={allies:[a],enemies:[],mainIds:[a.id],superIds:[],reserveIds:[],config:{},turn:1};ultimateCutin=async()=>{};playUltimatePostAnimation=async()=>{};transformationFxV158=async(a,fn)=>fn();notice=()=>{};renderBattle=()=>{};try{await performUltimate(a,a.ults.find(u=>u.kind==='moneyFriends'));return {crit:a.moneyFriendsMagicCrit,status:a.moneyFriendsStatusResist,all:a.allBuff,desc:player('money').ults.find(u=>u.kind==='moneyFriends').desc};}finally{({ultimateCutin,playUltimatePostAnimation,transformationFxV158,notice,renderBattle}=base);}},
 async castleCombat(){const base={startRound,bossSpecial,damageAlly,beginEnemyLunge,enemySkillImageCutinV134,actionCutin,playEnemyProjectile,inflictAllyStatus,fixedDelay},random=Math.random,hits=[],lunges=[],statuses=[],specials=[];startRound=async()=>{};damageAlly=async(a,p,t,x,el)=>{hits.push([a.id,p,t,el]);return 1};beginEnemyLunge=async id=>lunges.push(id);enemySkillImageCutinV134=async()=>{};actionCutin=async()=>{};playEnemyProjectile=async()=>{};inflictAllyStatus=async(a,s)=>statuses.push(s);fixedDelay=async()=>{};try{await beginBattle({mode:'story',party:state.party,enemyConfigs:[{template:castleAceTemplateV178(),level:73}]});const b=state.battle,e=b.enemies[0];b.actingEnemyId=e.uid;bossSpecial=async s=>specials.push(s.special);await enemyAction(1,e.uid);bossSpecial=base.bossSpecial;await bossSpecial(e.specialOptions[1]);const ace={specials,hits:[...hits],lunges:lunges.length,field:livingField().length,level:e.level,min:e.v144ActionMin,max:e.v144ActionMax};e.id='boss-gladi';e.name='グラディモブ';lunges.length=0;for(let i=0;i<10;i++){const draws=[0,.1,(i+.1)/10];Math.random=()=>draws.shift()??.99;await bossNormal();}Math.random=()=>.99;await bossNormal();return {ace,statuses,gladiLunges:lunges.length};}finally{Math.random=random;({startRound,bossSpecial,damageAlly,beginEnemyLunge,enemySkillImageCutinV134,actionCutin,playEnemyProjectile,inflictAllyStatus,fixedDelay}=base);}},
 async gladi(){const base={startRound,enemyStoryCutin,actionCutin,bossSpecial,bossNormal};startRound=async()=>{};enemyStoryCutin=async()=>{};actionCutin=async()=>{};const actions=[];bossSpecial=async spec=>actions.push(spec.special);bossNormal=async()=>actions.push('normal');try{await beginBattle({mode:'training',party:state.party,enemyConfigs:[{id:'boss-gladi',level:73}]});const b=state.battle,e=b.enemies[0],cut=Number(e.damageReduction||0);e.hp=e.maxHp*.65;await checkBattleHpDialogue();const after=e.damageReduction;await checkBattleHpDialogue();const same=e.damageReduction;e.hp=e.maxHp*.45;await checkBattleHpDialogue();await enemyAction(1,e.uid);const beforeTurn=[...actions];b.turn++;await enemyAction(1,e.uid);return {cut,after,same,beforeTurn,actions};}finally{({startRound,enemyStoryCutin,actionCutin,bossSpecial,bossNormal}=base);}},
 async history(){showScreen('adventure');await openStoryScene('demonCastle',2);await storyShowGuest('boss-lilith-castle');await castleHistoryV178(['僕の目の前にいる']);},
 async skipFinal(){state.test.enabled=true;storyBusy=true;skipScopeV174='';skippedV174=false;try{await demonFinalPreV89Final();return state.meta.moneyStoryAwayV157;}finally{storyBusy=false;await closeStoryScene(false);}}
};`;
(async()=>{const {browser,page,errors}=await open(injection);try{await page.waitForFunction(()=>window.__mobV178Runtime);await page.evaluate(()=>t178.seed());const times=await page.evaluate(()=>t178.timing());assert(times[0]>=2250&&times[1]>=850&&times[1]<1300&&times[2]>=2250&&times[3]>=2250,JSON.stringify(times));
 for(const width of [320,390]){await page.setViewportSize({width,height:844});const card=page.evaluate(()=>t178.card());await page.locator('.reaction-v177').waitFor();const words=await page.locator('.reaction-card-v177 p span').allTextContents();assert(words.includes('反撃する'),words.join('|'));assert(!words.includes('る'));assert(await page.locator('.reaction-card-v177 p').evaluate(e=>e.scrollWidth<=e.clientWidth));await page.waitForTimeout(350);await page.screenshot({path:path.join(out,'passive-'+width+'.png')});await page.evaluate(()=>t178.release());await card;}
 const walk=await page.evaluate(()=>t178.walk());const text=walk.spoken.map(s=>s[1]).join('\n');for(const expected of ['モブジェシーが放ったのは\n回復魔法だ','必ず、魔王を倒してください！！','モブピンク、待て！','オイラ強いでやんすよ！\nモブマニー！！','魔法会心率を20%アップ'])assert(text.includes(expected),expected);assert(walk.pages.includes('いつまで寝ているのだ'));assert(walk.pages.includes('僕の目の前にいる'));assert(walk.spoken.some(x=>x[1]==='王に娘として育てられた魔女'&&x[2]==='red'));assert(walk.away&&walk.restored&&walk.unlocked&&walk.record);assert.equal(walk.dessert,'さすがにもう来ないだろう');
 const combat=await page.evaluate(()=>t178.castleCombat());assert.deepEqual(combat.ace.specials,['レーザー・パルス・ストレート']);assert.equal(combat.ace.level,73);assert.equal(combat.ace.min,2);assert.equal(combat.ace.max,3);assert.equal(combat.ace.hits.length,combat.ace.field);assert(combat.ace.hits.every(x=>x[3]==='光'));assert.equal(combat.gladiLunges,0);assert.deepEqual(combat.statuses,['poison','poison','burn','burn','paralyze','sleep','sleep','stun','stun','stun']);
 const gladi=await page.evaluate(()=>t178.gladi());assert(Math.abs(gladi.after-gladi.cut-.1)<1e-8);assert.equal(gladi.after,gladi.same);assert(!gladi.beforeTurn.includes('グラビディ・グラディエーター'));assert(gladi.actions.includes('グラビディ・グラディエーター'));
 const ult=await page.evaluate(()=>t178.ultimate());assert.deepEqual([ult.crit,ult.status,ult.all],[.2,.2,.2]);assert(ult.desc.includes('魔法会心率を20%'));await page.reload();await page.waitForFunction(()=>window.__mobV178Runtime);await page.evaluate(()=>t178.seed());const history=page.evaluate(()=>t178.history());await page.locator('.castle-history-caption-v178').waitFor();await page.screenshot({path:path.join(out,'history.png')});await page.mouse.click(200,600);await history;
 const skip=page.evaluate(()=>t178.skipFinal());await page.locator('#storySkipV174').click();assert(await skip);assert.equal(await page.locator('.castle-black-v178').count(),0);assert.deepEqual(errors,[]);console.log('PASS repeat timing/reset, 320/390px word boundaries, castle scripts/history/red text/rescue, Money return/reward/20% ultimate, final Area skip');
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1;});
