const assert=require('node:assert/strict'),path=require('node:path'),{open}=require('./story-v172-harness.cjs');
const injection=`
const realDelay220=fixedDelay;fixedDelay=ms=>realDelay220(Math.min(ms,15));
window.test220={
 setup:()=>{state.meta.openingCompleted=true;state.meta.trainingPlayed=true;worldCleared=()=>true;state.meta.bookCompleted=true;state.party=['pink','desert','denden','money'].map(id=>[id,60]);state.meta.figures={};for(const f of FIGURES)if(!f.pending)state.meta.figures[f.id]=1;state.meta.figureEquipment={pink:['01',null,null,null],desert:['02',null,null,null]};state.meta.subFiguresV218={desert:['03',null,null,null]};state.meta.figureShelfV218=['04'];state.meta.figurePlusV218={};dialog=async()=> 'yes';narrationDialog=async()=> 'yes';facilityTalk=async()=>{};},
 equip:()=>{equipmentPlayerId='pink';equipmentTab='figures';showScreen('equipment');renderEquipment();},
 snapshot:()=>({main:state.meta.figureEquipment,sub:state.meta.subFiguresV218,shelf:state.meta.figureShelfV218}),
 candidates:()=>equipmentCandidateFiguresV132('pink').map(f=>f.id),
 effects:()=>({main:figureGroupEffectsV220('pink','main'),sub:figureGroupEffectsV220('pink','sub')}),
 home:()=>{showScreen('home');renderHome();},
 gacha:()=>{showScreen('tavern');state.meta.diamonds=100;setRubyV115(10000);renderFigureGachaShopV98('001');$('#tavernFigurePopup').hidden=false;},
 pools:()=>FIGURE_GACHAS_V96.map(b=>({id:b.id,extra:b.extra})),
 patterns:()=>{const rank={R:0,SR:1,SSR:2,UR:3,MOB:4};return{bounds:[0,.59999,.6,.84499,.845,.96499,.965,.99499,.995,.99999].map(selectGachaPatternV220).map(x=>x.id),runs:FIGURE_GACHAS_V96.flatMap(b=>GACHA_PATTERNS_V220.map(p=>{const r=prepareGachaV220(b,10,p);return{id:p.id,banner:b.id,ranks:r.figs.map(f=>rank[f.rarity]),featured:r.figs.some(f=>gachaFeaturedV220(b).includes(f))};}))};},
 preview:async id=>{const p=GACHA_PATTERNS_V220.find(p=>p.id===id);await pinkGachaV220(p);},
 ruby:()=>rubyOwnedV115(),
 battle:async()=>{startRound=()=>{};allyStoryCutin=()=>Promise.resolve();actionCutin=()=>Promise.resolve();await startBattleLoaded({mode:'training',party:state.party,enemyConfigs:[{template:mochiTemplateV218(3,0),level:35}]});const b=state.battle;b.queue=b.allies.map(a=>({type:'ally',id:a.id}));b.queuePos=0;b.busy=false;await enemyAction(1,b.enemies[0].uid);renderBattle();},
 hit:()=>{const a=state.battle.allies[0],e=state.battle.enemies[0];const old=Math.random;Math.random=()=>.99;calcDamage=()=>({value:10,crit:false,miss:false});try{applyEnemyDamageTo(a,e,1);applyEnemyDamageTo(a,e,1);const two=figureSoulV218(a);advanceUltimateCooldowns(a);const afterTurn=figureSoulV218(a);e.hp=1;applyEnemyDamageTo(a,e,1);return{two,afterTurn,killed:figureSoulV218(a)};}finally{Math.random=old;}},
 skill:async()=>{const b=state.battle,a=b.allies[0],f=figureById('01');b.enemies[0].hp=500;b.finished=false;b.queuePos=0;a.figureEquipment=[f.id];a.soulPointsV220=10;a.hp=1;const before=b.queuePos,cost=f.soul.cost;await useFigureSoulV218(a,f.id);return{points:a.soulPointsV220,cost,hp:a.hp,turnSame:before===b.queuePos};},
 balance:()=>{const t={...LEGENDS_V218[0],id:'legend218-caramel',legendV218:LEGENDS_V218[0],category:'boss'},a=balanceBuildBaseV220(t,60),b=buildEnemyFromTemplate(t,60);return{hp:b.maxHp/a.maxHp,atk:b.atk/a.atk};}
};`;
(async()=>{const x=await open(injection);try{const {page,errors}=x;assert.deepEqual(errors,[]);await page.evaluate(()=>test220.setup());const candidates=await page.evaluate(()=>test220.candidates());for(const id of ['01','02','03','04'])assert(!candidates.includes(id));await page.evaluate(()=>test220.equip());await page.locator('[data-slot="1"]').click();await page.getByRole('searchbox').fill('ミカン');assert((await page.locator('[data-choose]').count())>0);await page.getByRole('searchbox').fill('');await page.locator('[data-choose="05"]').click();assert.equal((await page.evaluate(()=>test220.snapshot())).main.pink[1],null);assert(await page.locator('.figure-confirm-v220').isVisible());await page.locator('[data-commit]').click();assert.equal((await page.evaluate(()=>test220.snapshot())).main.pink[1],'05');await page.locator('[data-auto]').click();assert.equal((await page.evaluate(()=>test220.snapshot())).main.desert[0],'02');assert.equal((await page.evaluate(()=>test220.snapshot())).sub.desert[0],'03');assert.equal((await page.evaluate(()=>test220.snapshot())).main.pink[0],'01');await page.locator('[data-equipment-tab="subfigures"]').click();await page.locator('[data-slot="0"]').click();await page.locator('[data-choose="06"]').click();await page.locator('[data-commit]').click();assert.equal((await page.evaluate(()=>test220.snapshot())).sub.pink[0],'06');await page.waitForFunction(()=>!document.querySelector('.adjacency-up-v174')&&!document.querySelector('.figure-resonance-activation.show'));await page.screenshot({path:path.join(__dirname,'v220-sub.png'),animations:'disabled'});
await page.evaluate(()=>test220.home());assert.equal(await page.locator('#homeShelfV220 img').count(),1);assert(await page.locator('.brand-box #shelfButtonV218').isVisible());await page.locator('#shelfButtonV218').click();await page.locator('[data-choose="07"]').click();await page.locator('[data-commit]').click();await page.locator('#figureChooseV220 [data-close]').click();assert.equal(await page.locator('#homeShelfV220 img').count(),2);await page.screenshot({path:path.join(__dirname,'v220-shelf.png'),animations:'disabled'});
const patterns=await page.evaluate(()=>test220.patterns());assert.deepEqual(patterns.bounds,['wood','wood','choice','choice','gold','gold','rainbow','rainbow','rush','rush']);for(const run of patterns.runs){if(run.id==='gold')assert(run.ranks.some(n=>n>=2));if(run.id==='rainbow'||run.id==='rush')assert(run.featured);if(run.id==='rush')assert(run.ranks.every(n=>n>=2));}
await page.evaluate(()=>test220.gacha());await page.locator('[data-banner="001"]').click();assert.equal(await page.locator('.gacha-actions-v219 button').count(),5);await page.locator('[data-ruby-v220]').click();const ruby=await page.evaluate(()=>test220.ruby());await page.locator('[data-exchange]').first().click();assert(await page.locator('[data-confirm]').isVisible());await page.locator('[data-confirm]').click();await page.waitForFunction(n=>test220.ruby()<n,ruby);await page.evaluate(()=>test220.preview('choice'));await page.screenshot({path:path.join(__dirname,'v220-pink.png'),animations:'disabled'});
await page.evaluate(()=>{document.querySelector('.gacha-overlay-v219').hidden=true;});await page.evaluate(()=>test220.battle());assert.equal(await page.locator('.mochi-chief-v220').count(),1);assert.equal(await page.locator('.mochi-add-v220').count(),2);await page.screenshot({path:path.join(__dirname,'v220-mochi.png'),animations:'disabled'});assert.deepEqual(await page.evaluate(()=>test220.hit()),{two:2,afterTurn:2,killed:5});const sk=await page.evaluate(()=>test220.skill());assert.equal(sk.points,10-sk.cost);assert(sk.hp>1&&sk.turnSame);const balance=await page.evaluate(()=>test220.balance());assert(Math.abs(balance.hp-4/9)<.001);assert(Math.abs(balance.atk-1.3)<.01);assert.deepEqual(errors,[]);console.log('v220 PASS: equip confirmation/search, safe auto, independent sub tab, home shelf, five gacha patterns/guarantees, ruby confirmation, center boss + side adds, shared SOUL attack/kill/spend/no turn gain, raid balance');}finally{await x.browser.close();}})().then(()=>process.exit(0),e=>{console.error(e);process.exit(1)});
