const assert=require('node:assert/strict'),fs=require('fs'),{execFileSync}=require('child_process'),{open}=require('./story-v172-harness.cjs');
const old=JSON.parse(execFileSync('git',['show','HEAD:js/figure-catalog-v218.json'],{encoding:'utf8'}));
const now=JSON.parse(fs.readFileSync('js/figure-catalog-v218.json','utf8'));
for(const f of now.figures.filter(f=>f.soul)){const before=old.figures.find(x=>x.image===f.image);assert.equal(f.soul.cost,before.soul.cost-2,f.image);}
const seed=fs.readFileSync('tests/update-v220.cjs','utf8').match(/const injection=`([\s\S]*?)`;/)[1];
const injection=seed+`
window.test221={
 shelf:()=>{state.meta.figureShelfV218=[];const fs=FIGURES.filter(f=>f.rarity==='R'&&!f.pending).slice(0,10);const results=fs.map(f=>assignFigureV218(f.id,'shelf'));const dup=assignFigureV218(fs[0].id,'shelf');return{results,dup,count:state.meta.figureShelfV218.length,limits:shelfLimitsV218};},
 once:async()=>{const a=activeAlly(),id='01';a.soulPointsV220=100;const before=a.soulPointsV220,r=await useFigureSoulV218(a,id);renderBattle();return{r,spent:before-a.soulPointsV220,used:state.battle.figureSoulUsedV221,disabled:document.querySelector('[data-soul="01"]').disabled};},
 helpers:()=>HELPER_PLAYERS_V218.map(p=>{const a=buildAlly(p,60);return[a.ults.length,availableUlts(a).length];}),
 unlock:()=>{const out=[];for(const key of ['bookCompleted','moneyFriendsUnlocked','desertMiraPowerV120'])state.meta[key]=false;out.push(['yusha','money','desert','pink'].map(passiveTwoV221));state.meta.bookCompleted=state.meta.moneyFriendsUnlocked=state.meta.desertMiraPowerV120=true;out.push(['yusha','money','desert','pink'].map(passiveTwoV221));return out;},
 desert:()=>{const b=state.battle,a=buildAlly(player('desert'),60),e=b.enemies[0],oldCalc=calcDamage,oldRandom=Math.random;b.allies.push(a);e.hp=e.maxHp=10000;e.evasion=0;Math.random=()=>.99;let hits=0;calcDamage=()=>{hits++;return{value:10,crit:true,miss:false};};try{applyEnemyDamageTo(a,e,1);return{hits,poison:e.status.poison};}finally{calcDamage=oldCalc;Math.random=oldRandom;}},
 fresh:()=>{const a=activeAlly(),old=state.battle.figureSoulUsedV221;state.battle.figureSoulUsedV221=[];a.soulPointsV220=100;renderBattle();const enabled=!document.querySelector('[data-soul="01"]').disabled;state.battle.figureSoulUsedV221=old;return enabled;},
 party:async()=>{const b=state.battle;ultimateCutin=async()=>{};playUltimatePostAnimation=async()=>{};transformationFxV158=async(a,fn)=>fn();delay=async()=>{};const a=buildAlly(player('money'),60);b.allies=[a];b.mainIds=[a.id];b.superIds=[];b.queue=[{type:'ally',id:a.id}];b.queuePos=0;a.ultCooldowns=a.ults.map(()=>0);a.mpNow=a.maxMp;a.transformedMoney=true;const hits=[];const base=playerAoeDamage;playerAoeDamage=async(a,p)=>{hits.push(p);return 1;};try{await performUltimate(a,a.ults[1]);}finally{playerAoeDamage=base;}return{hits,kind:a.ults[1].kind,descs:PARTY_SPEC_V221.map(p=>[p.id,p.ults.length,p.passive])};},
 legend:async()=>{const b=state.battle;b.config.legendV218='caramel';b.finished=false;b.enemies[0].legendV218=LEGENDS_V218[0];const promise=finishBattle(true);const cinematic=!!document.querySelector('.legend-victory-v221');await promise;const rewarded=legendRecordV218(LEGENDS_V218[0]).rewarded;return{cinematic,rewarded,result:!!document.querySelector('.victory-result-v221')};}
};`;
(async()=>{const x=await open(injection);try{const {page,errors}=x;await page.evaluate(()=>test220.setup());assert.deepEqual(await page.evaluate(()=>test221.helpers()),Array(7).fill([0,0]));const shelf=await page.evaluate(()=>test221.shelf());assert.deepEqual(shelf.results,[true,true,true,true,true,true,true,true,true,false]);assert.equal(shelf.dup,false);assert.equal(shelf.count,9);assert.deepEqual(shelf.limits,{MOB:1,UR:3,SSR:5,SR:7,R:9});await page.evaluate(()=>test220.home());await page.locator('#shelfButtonV218').click();assert(await page.getByText('棚で発動中の効果（合計の30%）',{exact:true}).isVisible());await page.screenshot({path:'tests/v221-shelf-effects.png'});await page.locator('[data-choose="01"]').click();await page.locator('[data-commit]').click();assert(await page.getByText('棚がいっぱいだ！',{exact:true}).isVisible());await page.locator('[data-unshelf]').click();await page.locator('#figureChooseV220 [data-close]').click();await page.screenshot({path:'tests/v221-shelf.png'});
assert.deepEqual(await page.evaluate(()=>test221.unlock()),[[false,false,false,false],[true,true,true,false]]);await page.evaluate(()=>test220.battle());await page.evaluate(()=>test220.skill());const once=await page.evaluate(()=>test221.once());assert.equal(once.r,false);assert.equal(once.spent,0);assert(once.used.includes('01')&&once.disabled);assert(await page.evaluate(()=>test221.fresh()));assert.deepEqual(await page.evaluate(()=>test221.desert()),{hits:2,poison:3});const party=await page.evaluate(()=>test221.party());assert.deepEqual(party.hits,[2.72]);assert.equal(party.kind,'damage');assert(party.descs.every(p=>p[1]>=4&&p[2]));assert.deepEqual(await page.evaluate(()=>test221.legend()),{cinematic:true,rewarded:true,result:true});await page.screenshot({path:'tests/v221-legend-result.png'});await page.evaluate(()=>test220.preview('rainbow'));await page.screenshot({path:'tests/v221-gacha.png',animations:'disabled'});assert.deepEqual(errors,[]);console.log('v221 PASS: 272 source costs, shelf capacity/duplicate/remove/effect UI, helper ult exclusion, once per battle/reset, story passive gates, Desert crit followup/poison, transformed Money AOE, legend cinematic/reward');}finally{await x.browser.close();}})().then(()=>process.exit(0),e=>{console.error(e);process.exit(1)});
