const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const game=fs.readFileSync(path.join(root,'js/game.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const ok=(v,m)=>{if(!v)throw new Error(m)};
ok(html.includes('<div class="title-version">v198</div>'),'title is not v198');
ok(game.includes("window.__mobBuildVersion='v198'"),'runtime version is not v198');
ok(game.includes('window.__mobV197LilithRestoreAfterFormation=true'),'v198 marker missing');
const start=game.indexOf('async function isolatedSplitV195()');
const end=game.indexOf('async function runDemonCastleLilithPreV195()',start);
ok(start>=0&&end>start,'isolated split function not found');
const split=game.slice(start,end);
const done=split.indexOf("shell.addEventListener('mob-v196-split-done'");
const hide=split.indexOf('hideIsolationV195();',done);
const nyoro=split.indexOf("await storySay('nyoro','素晴らしい采配ニョロ！')",done);
const desert=split.indexOf("await storySay('desert','では、まずBパーティーの出陣だ！')",done);
ok(done>=0&&hide>done,'white layer is not removed after formation confirmation');
ok(nyoro>hide&&desert>nyoro,'normal dialogue must run after white layer is removed');
ok(!split.slice(done).includes("isolationMarkupV195('nyoro')"),'Nyoro dialogue still renders in white layer');
ok(!split.slice(done).includes("isolationMarkupV195('desert')"),'Desert dialogue still renders in white layer');
ok(!split.slice(done).includes("isolationMarkupV195('loading')"),'battle loading still renders in white layer');
console.log('update-v198 restore-after-formation tests: OK');
