const fs=require('node:fs'),path=require('node:path');
const root=path.join(__dirname,'..');
const game=fs.readFileSync(path.join(root,'js','game.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const ok=(v,m)=>{if(!v)throw new Error(m)};
ok(html.includes('<div class="title-version">v198</div>'),'title is not v198');
ok(game.includes("window.__mobBuildVersion='v198'"),'runtime version is not v198');
ok(game.includes('window.__mobV198LilithNext=true'),'Lilith NEXT marker missing');
ok(game.includes('window.__mobV198TestAreaJump=true'),'test AREA marker missing');
const waveStart=game.indexOf('async function spawnNextEnemyWave()');
const waveEnd=game.indexOf('async function handleForcedEnemyPhase()',waveStart);
ok(waveStart>=0&&waveEnd>waveStart,'spawnNextEnemyWave range missing');
const wave=game.slice(waveStart,waveEnd);
ok(wave.includes('if(isLilithPartyA){await waitLilithPartyNextV198();switchBattleToLilithPartyA();}'),'B -> A transition does not wait for NEXT');
ok(!wave.includes("Bパーティー勝利！ 次はAパーティーであります！"),'old automatic B -> A cutin remains');
const nextStart=game.indexOf('function waitLilithPartyNextV198()');
const nextEnd=game.indexOf('window.__mobV198LilithNext=true',nextStart);
ok(nextStart>=0&&nextEnd>nextStart,'NEXT helper missing');
const next=game.slice(nextStart,nextEnd);
ok(next.includes('data-v198-next'),'NEXT button missing');
ok(next.includes('B PARTY CLEAR!')&&next.includes('次はAパーティーの出陣です！'),'intermission presentation missing');
ok(next.includes("btn.addEventListener('click',finish,{once:true})"),'NEXT must require an explicit click');
ok(!next.includes('setTimeout(()=>finish'),'NEXT helper must not auto-advance');
const applyStart=game.indexOf('function applyTestChapter()');
const applyEnd=game.indexOf('function grantTestItemsMax()',applyStart);
ok(applyStart>=0&&applyEnd>applyStart,'applyTestChapter range missing');
const apply=game.slice(applyStart,applyEnd);
ok(apply.includes('state.adventure.areaIndex=ai'),'selected AREA is not assigned');
ok(apply.includes('state.adventure.storyFlags[`arrival:${id}`]=true'),'real arrival flag is not set for skipped AREA1');
ok(!apply.includes('`arrive:${id}`'),'obsolete arrive flag still present');
console.log('update-v198 Lilith NEXT + Test AREA jump tests: OK');
