const fs=require('fs'),assert=require('assert'),path=require('path');
const root=path.resolve(__dirname,'..');
const game=fs.readFileSync(path.join(root,'js/game.js'),'utf8');
const data=fs.readFileSync(path.join(root,'js/data.js'),'utf8');
const css=fs.readFileSync(path.join(root,'css/style.css'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
assert(game.includes('UPDATE_V208_BEGIN'),'v208 runtime patch missing');
assert(game.includes("currentWorld()?.id==='unfinishedBook'"),'book adventure guard missing');
assert(!game.includes("currentWorld()?.id==='unfinishedBook'&&!state.meta?.bookCompleted&&!state.test?.enabled"),'test mode must not bypass book adventure guard');
assert(game.includes("state.meta?.bookCompleted===true"),'book clear hard lock missing');
assert(game.includes('ensureBookCompletionRewardsBaseV208'),'premature book reward migration guard missing');
assert(game.includes('wi===bookIndex'),'test Reading Book lock reset missing');
assert(game.includes('bookDisplacedPartyMemberV208'),'displaced party visual preservation missing');
assert(game.includes('matrixOverlayV208'),'matrix upgrade missing');
assert(css.includes('bookHeroFlyToNaviV208'),'Hero-to-Navi staging CSS missing');
assert(css.includes('matrix-col-v208'),'asynchronous matrix columns missing');
assert(data.includes('t.hp=[330,1800,2150]'),'Kaijin HP rebalance missing');
assert(html.includes('<div class="title-version">v208</div>'),'v208 title missing');
console.log('v208 static checks: PASS');
