const assert=require('node:assert/strict'),path=require('node:path'),{open}=require('./story-v172-harness.cjs');
const injection=`
window.test218={
 setup:()=>{state.meta.openingCompleted=true;state.meta.trainingPlayed=true;state.party=['yusha','pink','desert','denden','money','jessie','tetsu','nyoro','nekoku','kaijin'].map(id=>[id,90]);state.meta.figureMigrationV218=false;state.meta.figures={'01':12,'02':3};state.meta.figureEquipment={pink:['01','02'],desert:['01']};state.meta.figurePlusV218={};migrateFiguresV218();worldCleared=()=>true;fixedDelay=()=>Promise.resolve();actionCutin=()=>Promise.resolve();startRound=()=>{};},
 inventory:()=>({figures:clone(state.meta.figures),plus:clone(state.meta.figurePlusV218),equipment:clone(state.meta.figureEquipment)}),
 catalogue:()=>({count:CATALOG_V218.figures.length,missing:CATALOG_V218.figures.filter(f=>f.assetMissingV218||f.conflictV218),legend:[51,52,53,54,55].map(n=>figureByImageV96('eventfig/'+n+'.png')?.name),umi:trainingEnemyCatalog().find(e=>e.name==='モブウミナイト')?.image}),
 scaling:()=>({low:scaleFigureEffectsV218({stats:{atk:3,maxHp:5},damageCut:.03,magicCut:.05}),plus:rawFigureEffectsV218('02').stats}),
 shelf:()=>{assignFigureV218('02','shelf');return{eq:figureEquipmentFor('pink'),shelf:state.meta.figureShelfV218,effects:figureEffectsFor('desert').stats};},
 sub:()=>{assignFigureV218('02','sub','desert',0);return{eq:state.meta.subFiguresV218,shelf:state.meta.figureShelfV218};},
 menu:(view,key=null)=>{eventViewV163=view;selectedStoryV179=key;renderEventQuestsV163();$('#trainingFeaturePopup').hidden=false;showScreen('training');},
 mochi:async()=>{const t=mochiTemplateV218(3,0);await startBattleLoaded({mode:'training',party:state.party.slice(0,4),enemyConfigs:[{template:t,level:35}]});state.battle.turn=1;allyStoryCutin=()=>Promise.resolve();await enemyAction(1,state.battle.enemies[0].uid);return state.battle.enemies.map(e=>({name:e.name,hp:e.hp,max:e.maxHp,kind:e.mochiV218}));},
 rewards:()=>{recordsV179('mochi')[0]=0;eventRunV174={storyV179:'mochi',difficulty:0,area:3,rewarded:false};const a=rewardV179();eventRunV174.rewarded=false;const b=rewardV179();const open=openV179('mochi',0);eventRunV174=null;return{a:a.awarded.map(x=>x.f.image),b:b.awarded.map(x=>x.f.image),open};},
 legend:async()=>{await startLegendV218(LEGENDS_V218[0],['dolphin','coach']);const b=state.battle,e=b.enemies[0];e.hp=Math.ceil(e.maxHp*.1);saveLegendV218(b);const t=buildEnemyFromTemplate({...LEGENDS_V218[0],id:'legend218-caramel',legendV218:LEGENDS_V218[0],category:'boss'},60);return{allies:b.allies.length,main:b.mainIds.length,helpers:b.allies.filter(a=>a.helperV218).length,ratio:t.hp/t.maxHp};},
 win:()=>{finishBattle(true);return{record:legendRecordV218(LEGENDS_V218[0]),owned:figureOwned(figureByImageV96('eventfig/51.png').id)};},
 soul:async()=>{const a=buildAlly(player('pink'),30),e=buildEnemyFromTemplate(trainingEnemyCatalog()[0],30);e.hp=e.maxHp=10000;state.battle.allies=[a];state.battle.enemies=[e];state.battle.enemy=e;state.battle.mainIds=[a.id];state.battle.targetEnemyId=e.uid;state.battle.finished=false;a.hp=1;a.mpNow=0;await applySoulTextV218(figureById('01'),a,[a],[e],'味方全体のHPを50回復する');await applySoulTextV218(figureById('02'),a,[a],[e],'自分のATKを2ターンの間10%アップする');const hp=a.hp,buff=soulEffectValueV218(a,'atk');return{hp,buff};},
 poisonHit:()=>{const a=state.battle.allies[0],e=state.battle.enemies[0];e.evasion=0;calcDamage=()=>({value:10,crit:false,miss:false});applyEnemyDamageTo(a,e,1,'magic',0,false);renderBattle();return !!enemyVisual(e.uid)?.closest('.enemy-unit')?.classList.contains('impact-v218');}
};`;
(async()=>{let x;try{x=await open(injection);const{page,errors}=x;page.on('console',m=>{if(m.type()==='error')console.log(m.text(),m.location().url)});assert.deepEqual(errors,[]);await page.evaluate(()=>test218.setup());const inv=await page.evaluate(()=>test218.inventory());assert.equal(inv.figures['01'],1);assert.equal(inv.plus['01'],9);assert.equal(inv.plus['02'],2);assert.equal(inv.equipment.desert[0],null);const c=await page.evaluate(()=>test218.catalogue());assert.equal(c.count,318);assert.deepEqual(c.missing,[]);assert.deepEqual(c.legend,['モブキャロル','モブムゥクラブ','モブジーン','モブマグナム','モブアノコ']);assert.equal(c.umi,'enemy/119.png');const scaling=await page.evaluate(()=>test218.scaling());assert.deepEqual(scaling.low,{stats:{atk:0,maxHp:1},damageCut:0,magicCut:.01});assert.equal(scaling.plus.atk,3);const shelf=await page.evaluate(()=>test218.shelf());assert(!shelf.eq.includes('02'));assert(shelf.shelf.includes('02'));const sub=await page.evaluate(()=>test218.sub());assert.equal(sub.eq.desert[0],'02');assert(!sub.shelf.includes('02'));
await page.evaluate(()=>test218.menu('boss'));await page.screenshot({path:path.join(__dirname,'v218-book.png')});await page.locator('.legend-door-v218').click();assert(await page.getByText('レジェンドボス',{exact:true}).isVisible());await page.evaluate(()=>test218.menu('story','mochi'));assert(await page.getByText('初回報酬：フィギュア30 / 2回目報酬：フィギュア31').isVisible());const mochi=await page.evaluate(()=>test218.mochi());assert.equal(mochi.filter(e=>e.kind===4).length,2);assert(mochi[0].max>mochi[1].max);assert.deepEqual(await page.evaluate(()=>test218.rewards()),{a:['eventfig/30.png'],b:['eventfig/31.png'],open:false});const raid=await page.evaluate(()=>test218.legend());console.log('raid',raid);assert.equal(raid.allies,12);assert.equal(raid.main,12);assert.equal(raid.helpers,2);assert(raid.ratio>=.3&&raid.ratio<.301);const win=await page.evaluate(()=>test218.win());assert(win.record.rewarded);assert.equal(win.owned,1);assert.deepEqual(await page.evaluate(()=>test218.soul()),{hp:51,buff:.1});assert(await page.evaluate(()=>test218.poisonHit()));assert.deepEqual(errors,[]);console.log('v218 PASS: migration, +9, scaling, shelf/sub, catalogue, book UI, Mochi summon/rewards, 12-member raid, saved HP floor, first reward, SOUL effects, persistent hit reaction');}finally{if(x){console.log('Browser errors:',x.errors);await x.browser.close();}}})().then(()=>process.exit(0),e=>{console.error(e);process.exit(1)});
