const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..');
const src=fs.readFileSync(path.join(root,'js/update-v190.js'),'utf8');
const game=fs.readFileSync(path.join(root,'js/game.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
assert(src.includes("async function runDemonCastleLilithPreV190()"));
assert(src.includes("await demonLilithSummonV106();"),'sisters must use visual-only summon');
assert(!src.includes("await lilithFamilyRoseSummonV180()"),'must never call old early-split summon hook');
const family=src.indexOf('await demonLilithSummonV106();');
const money=src.indexOf("await storySay('money','リリスがいる方は3体\\n戦力の分け方が大事ね！');");
const narr=src.indexOf("await storyNarrate('パーティーを2つ作ってください");
const form=src.indexOf('await chooseLilithSplitV190();',narr);
const nyoro=src.indexOf("await storySay('nyoro','素晴らしい采配ニョロ！');");
const desert=src.indexOf("await storySay('desert','では、まずBパーティーの出陣だ！');");
assert(family>=0&&money>family&&narr>money&&form>narr&&nyoro>form&&desert>nyoro,'flow order regression');
assert(src.includes("party:split.B"),'B party must start first');
assert(src.includes("lilithSplitBattle:true"),'battle must retain B->A wave switch contract');
assert(game.includes('// UPDATE_V190_BEGIN')&&game.includes('// UPDATE_V190_END'));
assert(html.includes('<div class="title-version">v190</div>'));
assert(html.includes('// UPDATE_V190_BEGIN'));
console.log('v190 Lilith single-flow contract: OK');
