const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{open,root}=require('./story-v172-harness.cjs');
const injection=`
const delay219=fixedDelay;fixedDelay=ms=>delay219(Math.min(ms,10));
window.test219={
 setup:()=>{selectGachaPatternV220=()=>GACHA_PATTERNS_V220[0];state.meta.openingCompleted=true;state.meta.trainingPlayed=true;state.meta.bookCompleted=true;worldCleared=()=>true;state.party=['yusha','pink','desert','denden','money','jessie','tetsu','nyoro','nekoku','kaijin'].map(id=>[id,80]);state.autoBattle=false;passiveChance=()=>false;},
 audit:()=>({gachas:FIGURE_GACHAS_V96.map(b=>({id:b.id,images:[...COMMON_GACHA_V219,...b.extra],pool:gachaPoolV96(b).map(f=>f.image)})),worlds:MOB_DATA.adventureWorlds.map(w=>w.id),rates:['R','SR','SSR','UR','MOB'].map(rarity=>figureOverflowRubyV115({rarity}))}),
 locks:()=>{worldCleared=id=>id==='grassland';state.meta.bookCompleted=false;const ids=FIGURE_GACHAS_V96.filter(b=>b.unlock()).map(b=>b.id);worldCleared=()=>true;state.meta.bookCompleted=true;return ids;},
 shop:()=>{showScreen('tavern');state.meta.diamonds=100;renderFigureGachaShopV98('005');$('#tavernFigurePopup').hidden=false;window.messages219=[];dialog=async(...args)=>{messages219.push(args[0]);return'yes';};facilityTalk=async text=>messages219.push(text);},
 low:()=>{state.meta.diamonds=0;},
 money:()=>({diamonds:state.meta.diamonds,messages:window.messages219,busy:gachaBusyV110}),
 funds:()=>{state.meta.diamonds=100;},
 full:()=>{const f=gachaPoolV96(FIGURE_GACHAS_V96[0])[0];state.meta.figures[f.id]=1;state.meta.figurePlusV218[f.id]=9;gachaRollV96=()=>f;},
 raid:async(key='caramel')=>{initiativeSpeed=e=>e.type==='enemy'?1:10000;await startLegendV218(LEGENDS_V218.find(q=>q.key===key),['dolphin','coach']);window.bossActions219=[];enemyAction=async i=>bossActions219.push(i);},
 snap:()=>({turn:state.battle.turn,actions:window.bossActions219,queue:state.battle.queue.map(x=>x.type),count:state.battle.legendAllyActionsV219||0,active:activeAlly()?.id,busy:state.battle.busy}),
 act:()=>act('guard'),
 resetHp:()=>{const e=state.battle.enemies[0];e.hp=10;saveLegendV218(state.battle);const n=buildEnemyFromTemplate({...LEGENDS_V218[0],id:'legend218-caramel',legendV218:LEGENDS_V218[0],category:'boss'},60);return n.hp===n.maxHp;},
 force:()=>{state.battle.enemies[0].legendShieldV218=.5;},
 suppress:()=>{advanceUltimateCooldowns(activeAlly());return state.battle.legendAllyActionsV219||0;},
 cancel:async()=>{const old=dialog,before=state.meta.diamonds;dialog=async()=> 'no';try{await drawGachaV96(FIGURE_GACHAS_V96[0],10);return state.meta.diamonds===before;}finally{dialog=old;}}
};`;
(async()=>{const x=await open(injection);try{const {page,errors}=x,consoleErrors=[];page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});assert.deepEqual(errors,[]);await page.evaluate(()=>test219.setup());const a=await page.evaluate(()=>test219.audit());assert.equal(a.gachas.length,14);assert.deepEqual(a.rates,[1,2,5,10,20]);for(const b of a.gachas){assert(fs.existsSync(path.join(root,'gacha',b.id+'.png')));for(const p of b.images){assert(fs.existsSync(path.join(root,p)),p);assert(b.pool.includes(p),'catalogue missing '+p);}assert.equal(new Set(b.pool).size,b.pool.length);}assert.deepEqual(await page.evaluate(()=>test219.locks()),['001']);
await page.evaluate(()=>test219.shop());assert(await page.evaluate(()=>test219.cancel()));await page.screenshot({path:path.join(__dirname,'v219-gacha.png'),animations:'disabled'});await page.locator('[data-banner="001"]').click();assert.equal(await page.locator('.gacha-actions-v219 button').count(),5);await page.locator('[data-lineup]').click();await page.locator('[data-figure]').first().click();await page.locator('[data-detail-close]').click();assert(await page.locator('[data-back]').isVisible());await page.locator('[data-back]').click();await page.evaluate(()=>test219.low());await page.locator('[data-one]').click();await page.waitForFunction(()=>!test219.money().busy);assert.deepEqual((await page.evaluate(()=>test219.money())).messages,['このガチャを引くの？','ダイヤが足りないよ！']);assert.equal((await page.evaluate(()=>test219.money())).diamonds,0);
await page.evaluate(()=>test219.funds());await page.locator('[data-banner="001"]').click();await page.locator('[data-ten]').click();await page.locator('[data-results-close]').waitFor();assert.equal(await page.locator('[data-result]').count(),10);assert.equal((await page.evaluate(()=>test219.money())).diamonds,50);await page.screenshot({path:path.join(__dirname,'v219-ten.png'),animations:'disabled'});await page.locator('[data-result]').first().click();await page.locator('[data-detail-close]').click();assert.equal(await page.locator('[data-result]').count(),10);await page.locator('[data-result]').nth(1).click();await page.locator('[data-detail-close]').click();await page.locator('[data-results-close]').click();await page.waitForFunction(()=>!test219.money().busy);assert(await page.locator('[data-banner="001"]').isVisible());
await page.evaluate(()=>test219.full());await page.locator('[data-banner="001"]').click();await page.locator('[data-one]').click();await page.locator('[data-results-close]').waitFor();assert.equal(await page.locator('[data-result]').count(),1);assert(await page.locator('.converted-v219').isVisible());await page.locator('[data-results-close]').click();await page.waitForFunction(()=>!test219.money().busy);await page.locator('#tavernFigureCloseBtn').click();
await page.evaluate(()=>test219.raid());assert((await page.evaluate(()=>test219.snap())).queue.every(x=>x==='ally'));assert(await page.evaluate(()=>test219.resetHp()));assert.equal(await page.evaluate(()=>test219.suppress()),0);await page.screenshot({path:path.join(__dirname,'v219-raid.png'),animations:'disabled'});for(let i=0;i<3;i++)await page.evaluate(()=>test219.act());assert.deepEqual((await page.evaluate(()=>test219.snap())).actions,[]);await page.evaluate(()=>test219.act());assert.deepEqual((await page.evaluate(()=>test219.snap())).actions,[1,2,3]);await page.evaluate(()=>test219.force());for(let i=0;i<4;i++)await page.evaluate(()=>test219.act());assert.deepEqual((await page.evaluate(()=>test219.snap())).actions,[1,2,3,1,2,3,4,5]);assert.deepEqual(errors,[]);assert.deepEqual(consoleErrors,[]);console.log('v219 PASS: 14 exact pools/assets/unlocks, new rates, four choices, confirmation before insufficient funds, ten simultaneous results, separate detail close, single ruby conversion, fresh raid HP, 4 actions -> 3/5 boss actions; no cooldown-only count');}finally{await x.browser.close();}})().then(()=>process.exit(0),e=>{console.error(e);process.exit(1)});
