const assert=require('node:assert/strict'),path=require('node:path'),os=require('node:os'),fs=require('node:fs');
const {open}=require('./story-v172-harness.cjs');
const out=path.join(os.tmpdir(),'mob-v177');fs.mkdirSync(out,{recursive:true});
const injection=`window.t177={
 seed(){state.adventure=defaultAdventure();state.adventure.reportedWorlds=['grassland','desert','rural','magma','neon'];state.party=['yusha','pink','desert','denden'].map(id=>[id,90]);state.meta.trainingPlayed=true;state.meta.openingCompleted=true;state.meta.storyEventsV174={};state.test.enabled=false;state.training.mode='event';state.coins=0;state.meta.coins=0;state.meta.diamonds=0;showScreen('training');eventViewV163='story';renderTraining();$('#trainingFeaturePopup').hidden=false;},
 audit(){return [0,1,2].map(d=>[0,1,2,3].map(a=>buildEnemyWave(hotWaveV177(a,d),4,'','').map(e=>({name:e.name,kind:e.hotKindV177,image:e.image,level:e.level,cut:e.damageReduction,min:e.v144ActionMin,max:e.v144ActionMax,status:e.statusResist,crit:e.critDamageReduction}))))},
 async setupEnemy(kind='fight'){startRound=async()=>{};actionCutin=async()=>{};await beginBattle({mode:'training',party:state.party,enemyConfigs:hotWaveV177(kind==='passion'?3:1,0)});return state.battle.enemies.find(e=>e.hotKindV177===kind).uid;},
 async timings(){const b=state.battle,e=b.enemies[0];state.speed=5;e.name='モブギドラ';enemyPassiveNoticeV142(e,'ドラゴンソウル / ダメージ軽減+10%・全属性耐性+10%');let start=performance.now();await drainReactionsV177();const passive=performance.now()-start,a=b.allies[0],base={weaponElementAttackFx,applyEnemyDamage};let attackAt,damageAt;weaponElementAttackFx=async()=>{attackAt=performance.now()-start};applyEnemyDamage=()=>{damageAt=performance.now()-start};start=performance.now();try{await weaponFollowupV177(a,.5,'physical');return {passive,attackAt,damageAt,total:performance.now()-start,context:b.weaponAttackContext??null};}finally{({weaponElementAttackFx,applyEnemyDamage}=base);}},
 async passive(){const b=state.battle,e=b.enemies.find(x=>x.hotKindV177==='passion'),a=b.allies[0],base={damageAlly,beginEnemyLunge,reactionV177},random=Math.random,damage=[],counter=[];e.hp=e.maxHp=10000000;Math.random=()=>.99;damageAlly=async(a,p,t)=>counter.push({p,t});beginEnemyLunge=async()=>{};reactionV177=async()=>{};try{for(let i=0;i<3;i++)damage.push(applyEnemyDamageTo(a,e,1).value);const ready=e.hotShieldV177;await drainReactionsV177();damage.push(applyEnemyDamageTo(a,e,1).value);await drainReactionsV177();return {ready,damage,counter,armed:e.hotShieldV177};}finally{Math.random=random;({damageAlly,beginEnemyLunge,reactionV177}=base);}},
 detail(){const box=document.createElement('div');box.id='testDetail177';box.style='position:fixed;inset:80px 10px auto;z-index:2147483600';box.innerHTML=figureDetailMarkupV96(figureByImageV96('eventfig/17.png'));document.body.appendChild(box);return getComputedStyle(box.querySelector('p')).color;},
 async start(d){savannaSceneV174=async()=>{};startRound=async()=>{};return startHotV177(d)},
 async win(){const b=state.battle;for(const e of b.enemies){e.hp=0;recordEnemyDefeat(e)}await finishBattle(true);return {text:eventOverlayV163().innerText,area:eventRunV174.area}},
 async next(){eventRunV174.area++;await startSavannaAreaV174()},
 finish(){const result={repeat:rewardHotV177(),coins:state.coins,diamonds:state.meta.diamonds,records:{...hotRecordsV177()},medal:medalOwned('hot-fight'),figures:[21,22].map(n=>figureOwned('event0'+n))};returnSavannaV174();return result;},
 async action(){const b=state.battle,e=b.enemies.find(e=>e.hotKindV177==='passion'),a=b.allies[0],base={aoeHit,enemySkillImageCutinV134,reactionV177};let hits=[];aoeHit=async(...x)=>hits.push(x);enemySkillImageCutinV134=async()=>{};reactionV177=async()=>{};const before=playerBaseElementResistanceV104(a,'火');try{await enemyAction(1,e.uid);const down=before-playerBaseElementResistanceV104(a,'火');b.turn+=5;return {hits,down,restored:playerBaseElementResistanceV104(a,'火')===before}}finally{({aoeHit,enemySkillImageCutinV134,reactionV177}=base)}},
 async scene(){eventRunV174={hotV177:true,difficulty:0,area:3};state.test.enabled=true;await savannaSceneV174('pre');}
};`;
(async()=>{const {browser,page,errors}=await open(injection);try{
 await page.waitForFunction(()=>window.__mobV177Runtime);await page.evaluate(()=>t177.seed());
 assert.equal(await page.locator('[data-story177]').count(),2);await page.locator('[data-story177="hot"]').click();assert.equal(await page.locator('[data-hot177]:enabled').count(),1);assert.equal(await page.locator('.event-silhouette-v175').count(),4);await page.screenshot({path:path.join(out,'event.png')});
 const waves=await page.evaluate(()=>t177.audit());for(const d of waves){assert.deepEqual(d.map(x=>x.length),[1,1,1,3]);assert.equal(d[3][1].kind,'passion');assert.equal(d[3][1].max,3);assert.equal(d[3][1].crit,.5);assert(Object.values(d[3][1].status).every(x=>x===1));}assert.equal(waves[2][3][1].level,90);
 const color=await page.evaluate(()=>t177.detail());assert.equal(color,'rgb(37, 27, 16)');await page.screenshot({path:path.join(out,'detail.png')});await page.locator('#testDetail177').evaluate(e=>e.remove());
 await page.evaluate(()=>t177.setupEnemy());const timing=page.evaluate(()=>t177.timings());await page.locator('.reaction-v177.gidora').waitFor();const times=await timing;assert(times.passive>=2250);assert(times.attackAt>=1150);assert(times.total-times.damageAt>=600);assert.equal(times.context,null);
 await page.evaluate(()=>t177.setupEnemy('passion'));const p=await page.evaluate(()=>t177.passive());assert(p.ready&&!p.armed);assert(Math.abs(p.damage[3]-p.damage[2]*.5)<=1,JSON.stringify(p));assert.deepEqual(p.counter,[{p:1.8,t:'physical'}]);
 const action=await page.evaluate(()=>t177.action());assert.equal(action.hits[0][1],'physical');assert.equal(action.hits[0][2],'火');assert(Math.abs(action.down-.2)<1e-8);assert(action.restored);
 await page.evaluate(()=>t177.seed());for(let d=0;d<3;d++){assert(await page.evaluate(d=>t177.start(d),d));for(let a=0;a<4;a++){const w=await page.evaluate(()=>t177.win());assert(w.text.includes('CLEAR'));if(a<3)await page.evaluate(()=>t177.next());}const r=await page.evaluate(()=>t177.finish());assert.equal(r.repeat,null);assert(r.records[d]);if(d===2){assert.equal(r.diamonds,90);assert(r.coins>=65000);assert.equal(r.medal,1);assert.deepEqual(r.figures,[1,1]);}}
 assert.deepEqual(errors,[]);console.log('PASS 12 Areas with authored rewards, unlock/replay/reward-once, 3-hit guard/counter, AoE/fire debuff, real-time passive/followup waits, detail contrast');
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
