const fs=require('node:fs'),path=require('node:path'),root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),write=(p,s)=>fs.writeFileSync(path.join(root,p),s);
const chunks=read('イベントクエスト/イベントクエスト ネオン街の悪夢.txt').replace(/\r/g,'').trim().split(/\n\s*\n/).map(s=>s.trim());
if(chunks[5]!=='ネオン街の悪夢'||!chunks[147].startsWith('Area 4')||chunks[205]!=='クリア演出')throw Error('Nightmare script structure changed; review scene directions before importing.');
const names={'モブジェシー':'jessie','モブエース':'ace','モブマニー':'money','モブジョーンズ':'jones','モブウェイブ':'wave','ミラモブ':'mira','モブネオンキング':'king','モブドラゴン':'dragon','グラディモブ':'gladi','ヤミモブマニー':'yami','モブネプチューン':'nepu','モブネオンマスター':'master','？？？':'unknown','ナレーション':'narration'};
const actions={17:'jessie',19:'moneyRun',22:'moneyJump',27:'aceWalk',31:'moneyJump',37:'explosion',42:'sleep',47:'invaders',53:'knights',60:'retreat',65:'kingDuelSetup',66:'kingDuel',74:'gladiRush',80:'kingHit',86:'darkSurround',87:'tremble',89:'moneyLight',92:'gladiBlown',94:'gladiGone',97:'transform',101:'shieldFormation',103:'planetDragon',104:'yamiAbove',108:'threeArmies',114:'closeups',115:'moneyVoice',120:'stepBack',124:'armyDuel',129:'gladiFinish',131:'faceYami',135:'chargeWords',136:'kingSacrifice',140:'kingParticles',142:'nepuGuard',147:'nepuDuel',157:'knightsBlown',171:'master',179:'sealFormation',180:'seal',181:'black',187:'farewell',198:'aceExit',199:'sealedEnding'};
function rows(lo,hi){const out=[];for(let i=lo;i<=hi;i++){if(actions[i]){out.push(['action',actions[i]]);continue;}const lines=chunks[i].replace(/^討伐後\n/,'').split('\n'),key=names[lines[0]];if(key){const raw=lines.slice(1).join('\n'),big=/（巨大文字/.test(raw);out.push(['say',key,raw.replace(/（巨大文字[^）]*）/g,''),big?'big':'']);}else if(![38,109,110,111,112,125,182].includes(i))throw Error('Unmapped staging '+i+': '+chunks[i]);}return out;}
const data={intro:chunks.slice(5,16),pre:[rows(17,46),rows(47,57),rows(65,76),rows(147,149)],post:[[],rows(59,64),rows(78,146),rows(156,204)],turn3:rows(152,154)};
write('js/nightmare-script-v239.json',JSON.stringify(data,null,2)+'\n');
let game=read('js/game.js');
const old='b.config?.legendV218?5:dynamicBookRage?4:3';if(!game.includes('b.config?.nightmareV239?4:')){if(!game.includes(old))throw Error('Queue cap hook missing');game=game.replace(old,'b.config?.legendV218?5:b.config?.nightmareV239?4:dynamicBookRage?4:3');}
// Hide the battle field before its first render, then reuse the tested entrance animation.
game=game.replace("const mintEntrance=config.storyV179==='mint';","const mintEntrance=config.storyV179==='mint'||!!config.nightmareV239;");
const block='// UPDATE_V239_BEGIN\nconst NIGHTMARE_SCRIPT_V239='+JSON.stringify(data)+';\n'+read('js/nightmare-v239.js')+'\n'+read('js/nightmare-scenes-v239.js')+'\n// UPDATE_V239_END';
if(game.includes('// UPDATE_V239_BEGIN'))game=game.replace(/\/\/ UPDATE_V239_BEGIN[\s\S]*?\/\/ UPDATE_V239_END/,()=>block);else{const i=game.lastIndexOf('})();');game=game.slice(0,i)+block+'\n'+game.slice(i);}write('js/game.js',game);
let css=read('css/style.css'),style='/* UPDATE_V239_BEGIN */\n'+read('css/nightmare-v239.css')+'\n/* UPDATE_V239_END */';if(css.includes('/* UPDATE_V239_BEGIN */'))css=css.replace(/\/\* UPDATE_V239_BEGIN \*\/[\s\S]*?\/\* UPDATE_V239_END \*\//,()=>style);else css+='\n'+style;write('css/style.css',css);
write('index.html',read('index.html').replace(/<div class="title-version">v\d+<\/div>/,'<div class="title-version">v239</div>'));require('./sync-inline.cjs');
