const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..');const read=p=>fs.readFileSync(path.join(root,p),'utf8'),write=(p,s)=>fs.writeFileSync(path.join(root,p),s);let game=read('js/game.js');
function patch(a,b){if(game.includes(b))return;if(!game.includes(a))throw Error('Missing hook '+a.slice(0,90));game=game.replace(a,()=>b);}
patch('function normalizeFigureEquipmentRecord(v){const seen=new Set();return Array.from({length:4}', 'function normalizeFigureEquipmentRecord(v){const seen=new Set();return Array.from({length:figureSlotsV248()}');
patch('index=clamp(Number(index)||0,0,3);const eq=figureEquipmentFor(pid)', 'index=Number(index);if(!Number.isInteger(index)||index<0||index>=figureSlotsV248())return false;const eq=figureEquipmentFor(pid)');
patch('if(!player(pid)||index<0||index>3)return false;', 'if(!player(pid)||!Number.isInteger(index)||index<0||index>=figureSlotsV248())return false;');
patch("const row=state.meta.subFiguresV218[pid]??=[null,null,null,null];row[index]", "const row=state.meta.subFiguresV218[pid]??=Array(figureSlotsV248()).fill(null);row[index]");
const groupStart=game.indexOf('function renderFigureGroupV220('),groupEnd=game.indexOf('function openFigureChooseV220(',groupStart);let group=game.slice(groupStart,groupEnd);group=group.replaceAll('length:4','length:figureSlotsV248()').replaceAll('ids.length<4','ids.length<figureSlotsV248()').replaceAll('[null,null,null,null]','Array(figureSlotsV248()).fill(null)');game=game.slice(0,groupStart)+group+game.slice(groupEnd);
patch("(b.config?.nightmareV239||b.config?.storyV179==='macaron')?4", "(b.config?.nightmareV239||b.config?.storyV179==='macaron'||e.finaleV248?.actions)?4");
patch("if(next.some(x=>x.id==='dc2-enma2')){const old=(b.enemies||[]).find(x=>x.id==='dc2-enma');if(old)await enemyStoryCutin(old,'見せてやろう！真の力を！');await storyDarkBattlePulse();}","if(next.some(x=>x.id==='dc2-enma2')){await finaleEnmaLinesV248(b,2);await storyDarkBattlePulse();}");
patch("if(next.some(x=>x.id==='dc2-enma3')){const old=(b.enemies||[]).find(x=>x.id==='dc2-enma2');if(old)await enemyStoryCutin(old,'地獄の業火に焼かれるがいい！');await storyDarkBattlePulse();}","if(next.some(x=>x.id==='dc2-enma3')){await finaleEnmaLinesV248(b,3);await storyDarkBattlePulse();}");
patch("await actionCutin(is2?'見せてやろう！真の力を！':'地獄の業火に焼かれるがいい！','danger',2000);", "// Updated dialogue is played once by finaleEnmaLinesV248 in the wave transition.");
const data=JSON.parse(read('js/finale-dialogue-v248.json'));const block='// UPDATE_V248_BEGIN\nconst FINALE_SCRIPT_V248='+JSON.stringify(data)+';\n'+['js/finale-story-v248.js','js/finale-combat-v248.js','js/finale-ending-v248.js'].map(read).join('\n')+'\n// UPDATE_V248_END';if(game.includes('// UPDATE_V248_BEGIN'))game=game.replace(/\/\/ UPDATE_V248_BEGIN[\s\S]*?\/\/ UPDATE_V248_END/,()=>block);else{const i=game.lastIndexOf('})();');game=game.slice(0,i)+block+'\n'+game.slice(i);}write('js/game.js',game);let css=read('css/style.css'),style='/* UPDATE_V248_BEGIN */\n'+read('css/finale-v248.css')+'\n/* UPDATE_V248_END */';css=css.includes('/* UPDATE_V248_BEGIN */')?css.replace(/\/\* UPDATE_V248_BEGIN \*\/[\s\S]*?\/\* UPDATE_V248_END \*\//,()=>style):css+'\n'+style;write('css/style.css',css);write('index.html',read('index.html').replace(/<div class="title-version">v\d+<\/div>/,'<div class="title-version">v248</div>'));require('./sync-inline.cjs');

