// User-provided recordings. No generated replacement tones; missing 008 remains unmapped.
function createSoundSystem({host=globalThis,storage,now=()=>Date.now(),key='mob-story:se:v1',base='audio/user/'}={}){
 const files={select:'013.wav',confirm:'013.wav',back:'003.wav',error:'004.wav',attack:'054.mp3',hit:'053.mp3',critical:'62.wav',heal:'038.wav',buff:'007.mp3',debuff:'066.mp3',breath:'052.mp3',slashAll:'065.mp3',item:'067.mp3',guard:'019.wav',win:'005.mp3',lose:'004.wav',defeat:'019.wav',reward:'005.mp3',start:'006.mp3',summon:'101.wav',fusion:'055.mp3',navigate:'006.mp3',deckAdd:'013.wav',deckRemove:'003.wav',deckArrange:'013.wav',starter:'007.mp3',dialogue:'100.wav'};
 const elementFiles={'火':'031.mp3','水':'037.mp3','雷':'045.wav','地':'035.mp3','風':'027.mp3','光':'049.mp3','闇':'033.mp3','無':'028.mp3'};
 let ctx,master,bgmGain,bgmSource=null,bgmWanted=false,bgmLoading=null,bgmEpoch=0,initialized=false,serial=0,epoch=0,unlocked=false,saveFailed=false,scopeSerial=0;
 let settings={volume:.55,muted:false,bgmVolume:.3,bgmMuted:false};const bgmVoices=new Set();const voices=new Map(),cache=new Map(),loading=new Map(),scopes=new Set(),recent=new Map(),seen=new Set(),history=[];const stats={played:0,suppressed:0,errors:0,maxVoices:0,lateDropped:0};
 const store=()=>storage===undefined?host.localStorage:storage;
 function init(legacySound){if(initialized)return;initialized=true;try{const s=JSON.parse(store()?.getItem(key)||'null');if(s?.version===1)for(const k of Object.keys(settings)){if(typeof s[k]===typeof settings[k])settings[k]=typeof s[k]==='number'?Math.max(0,Math.min(1,s[k])):s[k];}else if(legacySound===false)settings.muted=true;}catch{saveFailed=true;}}
 function stopVoice(v){voices.delete(v.id);try{v.source.onended=null;v.source.stop();v.source.disconnect();v.gain.disconnect();}catch{}}
 function stopAll(){epoch++;for(const v of [...voices.values()])stopVoice(v);}
 function stopScope(s){epoch++;for(const v of [...voices.values()])if(v.scope===s)stopVoice(v);}
 function beginScope(label){const s=label+':'+(++scopeSerial);scopes.add(s);return s;}
 function endScope(s){stopScope(s);scopes.delete(s);for(const k of seen)if(k.startsWith(s+'|'))seen.delete(k);}
 function stopBgm(){bgmEpoch++;bgmLoading=null;for(const v of [...bgmVoices]){try{v.source.onended=null;v.source.stop();v.source.disconnect();v.gain.disconnect()}catch{}}bgmVoices.clear();bgmSource=null;}
 function setSettings(patch){init();for(const k of Object.keys(settings))if(typeof patch[k]===typeof settings[k]&&(typeof patch[k]!=='number'||Number.isFinite(patch[k])))settings[k]=typeof patch[k]==='number'?Math.max(0,Math.min(1,patch[k])):patch[k];if(settings.muted||!settings.volume)stopAll();if(settings.bgmMuted||!settings.bgmVolume)stopBgm();try{master?.gain.setTargetAtTime(settings.muted?0:settings.volume*.6,ctx.currentTime,.015);bgmGain?.gain.setTargetAtTime(settings.bgmMuted?0:settings.bgmVolume*.55,ctx.currentTime,.04);store()?.setItem(key,JSON.stringify({version:1,...settings}));saveFailed=false;}catch{saveFailed=true;}if(bgmWanted&&!bgmSource)void startBgm();return{...settings};}
 async function load(file){if(cache.has(file))return cache.get(file);if(loading.has(file))return loading.get(file);if(!ctx)return null;const own=ctx;const task=(async()=>{try{const r=await host.fetch(base+file);if(!r.ok)throw Error('audio unavailable');let b=await own.decodeAudioData(await r.arrayBuffer());if(own!==ctx)return null;if(file.startsWith('bgm-')){const n=Math.min(Math.round(b.sampleRate*.08),Math.floor(b.length/8)),out=own.createBuffer(b.numberOfChannels,b.length-n,b.sampleRate);for(let ch=0;ch<b.numberOfChannels;ch++){const x=b.getChannelData(ch),y=out.getChannelData(ch);y.set(x.subarray(n,x.length-n));for(let i=0;i<n;i++){const w=i/(n-1);y[y.length-n+i]=x[x.length-n+i]*(1-w)+x[i]*w;}}b=out;const keys=[...cache.keys()].filter(k=>k.startsWith('bgm-'));while(keys.length>=3)cache.delete(keys.shift());}cache.set(file,b);return b;}catch{stats.errors++;return null;}finally{loading.delete(file);}})();loading.set(file,task);return task;}
 async function preload(){const all=[...new Set([...Object.values(files),...Object.values(elementFiles)])];let i=0;await Promise.all(Array.from({length:4},async()=>{while(i<all.length)await load(all[i++]);}));}
 async function unlock(){init();if(host.document?.hidden)return false;try{if(!ctx||ctx.state==='closed'){const C=host.AudioContext||host.webkitAudioContext;if(!C)return false;ctx=new C();master=ctx.createGain();bgmGain=ctx.createGain();master.gain.value=settings.muted?0:settings.volume*.6;bgmGain.gain.value=settings.bgmMuted?0:settings.bgmVolume*.55;const limiter=ctx.createDynamicsCompressor();limiter.threshold.value=-10;limiter.ratio.value=10;master.connect(limiter);bgmGain.connect(limiter);limiter.connect(ctx.destination);}if(ctx.state!=='running')await ctx.resume();unlocked=ctx.state==='running';void preload();if(bgmWanted)void startBgm();return unlocked;}catch{stats.errors++;return false;}}
 function resolve(cue,o){if(/ポーションシャワー/.test(o.name||''))return files.item;if(/ブレス|breath/i.test(o.name||''))return files.breath;if(/地獄の斬撃/.test(o.name||'')||o.all&&o.attackType==='physical'&&/斬|剣|刀|slash|sword/i.test(o.name||''))return files.slashAll;if(cue==='skill')return o.healing?files.heal:elementFiles[o.attribute]||elementFiles['無'];return cue==='guard'&&o.special?files.critical:files[cue];}
 function play(cue,o={}){init();const file=resolve(cue,o),scope=o.scope||'ui';if(!file||!ctx||ctx.state!=='running'||settings.muted||!settings.volume||host.document?.hidden||scope!=='ui'&&!scopes.has(scope))return false;const t=now(),id=o.eventId==null?null:scope+'|'+o.eventId,k=scope+'|'+file;if(id&&seen.has(id)||t-(recent.get(k)??-Infinity)<80){stats.suppressed++;return false;}recent.set(k,t);if(recent.size>256)recent.delete(recent.keys().next().value);if(id){seen.add(id);if(seen.size>512)seen.delete(seen.values().next().value);}const mark=epoch;
 const start=b=>{if(!b)return false;if(mark!==epoch||host.document?.hidden||scope!=='ui'&&!scopes.has(scope)||ctx.state!=='running'||settings.muted){stats.lateDropped++;return false;}if(voices.size>=4)stopVoice(voices.values().next().value);const source=ctx.createBufferSource(),gain=ctx.createGain(),n=++serial,at=ctx.currentTime+.002,duration=Math.min(b.duration,Math.max(.12,o.durationLimit||2.5));source.buffer=b;source.connect(gain);gain.connect(master);gain.gain.setValueAtTime(1,at);gain.gain.setValueAtTime(1,at+Math.max(0,duration-.025));gain.gain.linearRampToValueAtTime(0,at+duration);const v={id:n,scope,source,gain};voices.set(n,v);source.onended=()=>{voices.delete(n);try{source.disconnect();gain.disconnect()}catch{}};source.start(at,0,duration);stats.played++;stats.maxVoices=Math.max(stats.maxVoices,voices.size);history.push({cue,file,scope,duration,time:now(),attribute:o.attribute,eventId:o.eventId});if(history.length>100)history.shift();return true;};
 if(cache.has(file))return start(cache.get(file));void load(file).then(b=>{if(now()-t<=180)start(b);else stats.lateDropped++;});return false;}
 async function startBgm(){const track=bgmWanted;if(!track||bgmSource?.track===track||bgmLoading===track||!ctx||ctx.state!=='running'||host.document?.hidden||settings.bgmMuted||!settings.bgmVolume)return;const mark=++bgmEpoch;bgmLoading=track;const b=await load(track);if(mark!==bgmEpoch)return;bgmLoading=null;if(!b||bgmWanted!==track||host.document?.hidden||ctx.state!=='running'||settings.bgmMuted||!settings.bgmVolume)return;const source=ctx.createBufferSource(),gain=ctx.createGain(),at=ctx.currentTime,old=bgmSource,v={source,gain,track};source.buffer=b;source.loop=true;source.loopStart=0;source.loopEnd=b.duration;source.connect(gain);gain.connect(bgmGain);gain.gain.setValueAtTime(0,at);gain.gain.linearRampToValueAtTime(1,at+.4);bgmVoices.add(v);source.onended=()=>{bgmVoices.delete(v);try{source.disconnect();gain.disconnect()}catch{}};source.start(at);bgmSource=v;if(old){old.gain.gain.cancelScheduledValues(at);old.gain.gain.setValueAtTime(old.gain.gain.value,at);old.gain.gain.linearRampToValueAtTime(0,at+.4);try{old.source.stop(at+.42)}catch{}}for(const extra of [...bgmVoices])if(extra!==v&&extra!==old){try{extra.source.stop()}catch{}}}
 function setBgm(track){track=track===true?'bgm-002.mp3':typeof track==='string'&&/^bgm-\d{3}\.mp3$/.test(track)?track:false;if(track===bgmWanted){if(track&&!bgmSource)void startBgm();return;}bgmWanted=track;bgmEpoch++;bgmLoading=null;if(!track)stopBgm();else void startBgm();}
 function background(){stopAll();stopBgm();try{ctx?.suspend()?.catch(()=>{})}catch{}}
 function foreground(){if(unlocked)void unlock();}
 function dispose(){stopAll();bgmWanted=false;stopBgm();cache.clear();scopes.clear();try{ctx?.close()?.catch(()=>{})}catch{}ctx=null;}
 return{init,unlock,preload,play,stopAll,stopScope,beginScope,endScope,setSettings,getSettings:()=>{init();return{...settings}},setBgm,stopBgm,background,foreground,dispose,debug:()=>({...stats,voices:voices.size,cache:cache.size,scopes:scopes.size,state:ctx?.state||'locked',saveFailed,bgmPlaying:!!bgmSource,bgmTrack:bgmSource?.track||null,bgmVoices:bgmVoices.size,bgmLoading,bgmWanted,history:[...history]})};
}
